from pprint import pprint
import re
import sublime
import sublime_plugin


INHIBIT_DEFAULTS = sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS
property_name_rx = re.compile(r"(?P<prop_name>[-a-z]+):")


class CSS6Completions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        trigger_start = locations[0] - len(prefix)

        # Completions is a list of (<trigger>, <completion>) tuples. Completions
        # are only offered for properties and values.
        completions = []
        if view.match_selector(trigger_start, "meta.property-name.css"):
            completions = property_names
        elif view.match_selector(trigger_start, "meta.value.css"):
            trigger_start = locations[0] - len(prefix)
            line = view.substr(view.line(trigger_start)).strip()
            matches = property_name_rx.search(line)
            if matches is not None:
                prop_name = matches.group("prop_name")
                if prop_name in property_values:
                    completions = property_values[prop_name] + all_values

        return completions, INHIBIT_DEFAULTS


property_names = [
    ("-moz-box-sizing", "-moz-box-sizing: ${0};"),
    ("-moz-column-count", "-moz-column-count: ${0};"),
    ("-moz-column-fill", "-moz-column-fill: ${0};"),
    ("-moz-column-gap", "-moz-column-gap: ${0};"),
    ("-moz-column-rule", "-moz-column-rule: ${0};"),
    ("-moz-column-rule-color", "-moz-column-rule-color: ${0};"),
    ("-moz-column-rule-style", "-moz-column-rule-style: ${0};"),
    ("-moz-column-rule-width", "-moz-column-rule-width: ${0};"),
    ("-moz-column-span", "-moz-column-span: ${0};"),
    ("-moz-column-width", "-moz-column-width: ${0};"),
    ("-moz-columns", "-moz-columns: ${0};"),
    ("-moz-font-feature-settings", "-moz-font-feature-settings: ${0};"),
    ("-moz-font-language-override", "-moz-font-language-override: ${0};"),
    ("-moz-hyphens", "-moz-hyphens: ${0};"),
    ("-moz-text-align-last", "-moz-text-align-last: ${0};"),
    ("-moz-text-decoration-color", "-moz-text-decoration-color: ${0};"),
    ("-moz-text-decoration-line", "-moz-text-decoration-line: ${0};"),
    ("-moz-text-decoration-style", "-moz-text-decoration-style: ${0};"),
    ("-ms-flow-from", "-ms-flow-from: ${0};"),
    ("-ms-flow-into", "-ms-flow-into: ${0};"),
    ("-ms-grid-column", "-ms-grid-column: ${0};"),
    ("-ms-grid-row", "-ms-grid-row: ${0};"),
    ("-ms-hyphens", "-ms-hyphens: ${0};"),
    ("-ms-ime-mode", "-ms-ime-mode: ${0};"),
    ("-ms-overflow-style", "-ms-overflow-style: ${0};"),
    ("-ms-overflow-x", "-ms-overflow-x: ${0};"),
    ("-ms-overflow-y", "-ms-overflow-y: ${0};"),
    ("-ms-text-align-last", "-ms-text-align-last: ${0};"),
    ("-ms-text-justify", "-ms-text-justify: ${0};"),
    ("-ms-transform", "-ms-transform: ${0};"),
    ("-ms-transform-origin", "-ms-transform-origin: ${0};"),
    ("-ms-transform-style", "-ms-transform-style: ${0};"),
    ("-ms-word-wrap", "-ms-word-wrap: ${0};"),
    ("-ms-wrap-flow", "-ms-wrap-flow: ${0};"),
    ("-ms-wrap-through", "-ms-wrap-through: ${0};"),
    ("-ms-writing-mode", "-ms-writing-mode: ${0};"),
    ("-webkit-align-content", "-webkit-align-content: ${0};"),
    ("-webkit-align-items", "-webkit-align-items: ${0};"),
    ("-webkit-align-self", "-webkit-align-self: ${0};"),
    ("-webkit-animation", "-webkit-animation: ${0};"),
    ("-webkit-animation-delay", "-webkit-animation-delay: ${0};"),
    ("-webkit-animation-direction", "-webkit-animation-direction: ${0};"),
    ("-webkit-animation-duration", "-webkit-animation-duration: ${0};"),
    ("-webkit-animation-fill-mode", "-webkit-animation-fill-mode: ${0};"),
    ("-webkit-animation-iteration-count", "-webkit-animation-iteration-count: ${0};"),
    ("-webkit-animation-name", "-webkit-animation-name: ${0};"),
    ("-webkit-animation-play-state", "-webkit-animation-play-state: ${0};"),
    ("-webkit-animation-timing-function", "-webkit-animation-timing-function: ${0};"),
    ("-webkit-backface-visibility", "-webkit-backface-visibility: ${0};"),
    ("-webkit-border-image", "-webkit-border-image: ${0};"),
    ("-webkit-break-after", "-webkit-break-after: ${0};"),
    ("-webkit-break-before", "-webkit-break-before: ${0};"),
    ("-webkit-break-inside", "-webkit-break-inside: ${0};"),
    ("-webkit-column-count", "-webkit-column-count: ${0};"),
    ("-webkit-column-fill", "-webkit-column-fill: ${0};"),
    ("-webkit-column-gap", "-webkit-column-gap: ${0};"),
    ("-webkit-column-rule", "-webkit-column-rule: ${0};"),
    ("-webkit-column-rule-color", "-webkit-column-rule-color: ${0};"),
    ("-webkit-column-rule-style", "-webkit-column-rule-style: ${0};"),
    ("-webkit-column-rule-width", "-webkit-column-rule-width: ${0};"),
    ("-webkit-column-span", "-webkit-column-span: ${0};"),
    ("-webkit-column-width", "-webkit-column-width: ${0};"),
    ("-webkit-columns", "-webkit-columns: ${0};"),
    ("-webkit-flex", "-webkit-flex: ${0};"),
    ("-webkit-flex-basis", "-webkit-flex-basis: ${0};"),
    ("-webkit-flex-direction", "-webkit-flex-direction: ${0};"),
    ("-webkit-flex-flow", "-webkit-flex-flow: ${0};"),
    ("-webkit-flex-grow", "-webkit-flex-grow: ${0};"),
    ("-webkit-flex-shrink", "-webkit-flex-shrink: ${0};"),
    ("-webkit-flex-wrap", "-webkit-flex-wrap: ${0};"),
    ("-webkit-flow-from", "-webkit-flow-from: ${0};"),
    ("-webkit-flow-into", "-webkit-flow-into: ${0};"),
    ("-webkit-font-feature-settings", "-webkit-font-feature-settings: ${0};"),
    ("-webkit-font-kerning", "-webkit-font-kerning: ${0};"),
    ("-webkit-font-size-delta", "-webkit-font-size-delta: ${0};"),
    ("-webkit-font-variant-ligatures", "-webkit-font-variant-ligatures: ${0};"),
    ("-webkit-grid-column", "-webkit-grid-column: ${0};"),
    ("-webkit-grid-row", "-webkit-grid-row: ${0};"),
    ("-webkit-hyphens", "-webkit-hyphens: ${0};"),
    ("-webkit-justify-content", "-webkit-justify-content: ${0};"),
    ("-webkit-order", "-webkit-order: ${0};"),
    ("-webkit-perspective", "-webkit-perspective: ${0};"),
    ("-webkit-perspective-origin", "-webkit-perspective-origin: ${0};"),
    ("-webkit-region-fragment", "-webkit-region-fragment: ${0};"),
    ("-webkit-transform", "-webkit-transform: ${0};"),
    ("-webkit-transform-origin", "-webkit-transform-origin: ${0};"),
    ("-webkit-transform-style", "-webkit-transform-style: ${0};"),
    ("-webkit-transition", "-webkit-transition: ${0};"),
    ("-webkit-transition-delay", "-webkit-transition-delay: ${0};"),
    ("-webkit-transition-duration", "-webkit-transition-duration: ${0};"),
    ("-webkit-transition-property", "-webkit-transition-property: ${0};"),
    ("-webkit-transition-timing-function", "-webkit-transition-timing-function: ${0};"),
    ("additive-symbols", "additive-symbols: ${0};"),
    ("align-content", "align-content: ${0};"),
    ("align-items", "align-items: ${0};"),
    ("align-self", "align-self: ${0};"),
    ("alignment", "alignment: ${0};"),
    ("alignment-adjust", "alignment-adjust: ${0};"),
    ("alignment-baseline", "alignment-baseline: ${0};"),
    ("all", "all: ${0};"),
    ("anchor-point", "anchor-point: ${0};"),
    ("animation", "animation: ${0};"),
    ("animation-delay", "animation-delay: ${0};"),
    ("animation-direction", "animation-direction: ${0};"),
    ("animation-duration", "animation-duration: ${0};"),
    ("animation-fill-mode", "animation-fill-mode: ${0};"),
    ("animation-iteration-count", "animation-iteration-count: ${0};"),
    ("animation-name", "animation-name: ${0};"),
    ("animation-play-state", "animation-play-state: ${0};"),
    ("animation-timing-function", "animation-timing-function: ${0};"),
    ("backface-visibility", "backface-visibility: ${0};"),
    ("background", "background: ${0};"),
    ("background-attachment", "background-attachment: ${0};"),
    ("background-clip", "background-clip: ${0};"),
    ("background-color", "background-color: ${0};"),
    ("background-image", "background-image: ${0};"),
    ("background-origin", "background-origin: ${0};"),
    ("background-position", "background-position: ${0};"),
    ("background-repeat", "background-repeat: ${0};"),
    ("background-size", "background-size: ${0};"),
    ("baseline-shift", "baseline-shift: ${0};"),
    ("bleed", "bleed: ${0};"),
    ("bookmark-label", "bookmark-label: ${0};"),
    ("bookmark-level", "bookmark-level: ${0};"),
    ("bookmark-state", "bookmark-state: ${0};"),
    ("border", "border: ${0};"),
    ("border-bottom", "border-bottom: ${0};"),
    ("border-bottom-color", "border-bottom-color: ${0};"),
    ("border-bottom-left-radius", "border-bottom-left-radius: ${0};"),
    ("border-bottom-right-radius", "border-bottom-right-radius: ${0};"),
    ("border-bottom-style", "border-bottom-style: ${0};"),
    ("border-bottom-width", "border-bottom-width: ${0};"),
    ("border-clip", "border-clip: ${0};"),
    ("border-clip-bottom", "border-clip-bottom: ${0};"),
    ("border-clip-left", "border-clip-left: ${0};"),
    ("border-clip-right", "border-clip-right: ${0};"),
    ("border-clip-top", "border-clip-top: ${0};"),
    ("border-collapse", "border-collapse: ${0};"),
    ("border-color", "border-color: ${0};"),
    ("border-image", "border-image: ${0};"),
    ("border-image-outset", "border-image-outset: ${0};"),
    ("border-image-repeat", "border-image-repeat: ${0};"),
    ("border-image-slice", "border-image-slice: ${0};"),
    ("border-image-source", "border-image-source: ${0};"),
    ("border-image-width", "border-image-width: ${0};"),
    ("border-left", "border-left: ${0};"),
    ("border-left-color", "border-left-color: ${0};"),
    ("border-left-style", "border-left-style: ${0};"),
    ("border-left-width", "border-left-width: ${0};"),
    ("border-limit", "border-limit: ${0};"),
    ("border-radius", "border-radius: ${0};"),
    ("border-right", "border-right: ${0};"),
    ("border-right-color", "border-right-color: ${0};"),
    ("border-right-style", "border-right-style: ${0};"),
    ("border-right-width", "border-right-width: ${0};"),
    ("border-spacing", "border-spacing: ${0};"),
    ("border-style", "border-style: ${0};"),
    ("border-top", "border-top: ${0};"),
    ("border-top-color", "border-top-color: ${0};"),
    ("border-top-left-radius", "border-top-left-radius: ${0};"),
    ("border-top-right-radius", "border-top-right-radius: ${0};"),
    ("border-top-style", "border-top-style: ${0};"),
    ("border-top-width", "border-top-width: ${0};"),
    ("border-width", "border-width: ${0};"),
    ("bottom", "bottom: ${0};"),
    ("box-decoration-break", "box-decoration-break: ${0};"),
    ("box-shadow", "box-shadow: ${0};"),
    ("box-sizing", "box-sizing: ${0};"),
    ("box-snap", "box-snap: ${0};"),
    ("break-after", "break-after: ${0};"),
    ("break-before", "break-before: ${0};"),
    ("break-inside", "break-inside: ${0};"),
    ("caption-side", "caption-side: ${0};"),
    ("chains", "chains: ${0};"),
    ("child-align", "child-align: ${0};"),
    ("clear", "clear: ${0};"),
    ("clear-after", "clear-after: ${0};"),
    ("clear-side", "clear-side: ${0};"),
    ("clip-path", "clip-path: ${0};"),
    ("clip-rule", "clip-rule: ${0};"),
    ("color", "color: ${0};"),
    ("color-correction", "color-correction: ${0};"),
    ("color-interpolation-filters", "color-interpolation-filters: ${0};"),
    ("column-count", "column-count: ${0};"),
    ("column-fill", "column-fill: ${0};"),
    ("column-gap", "column-gap: ${0};"),
    ("column-rule", "column-rule: ${0};"),
    ("column-rule-color", "column-rule-color: ${0};"),
    ("column-rule-style", "column-rule-style: ${0};"),
    ("column-rule-width", "column-rule-width: ${0};"),
    ("column-span", "column-span: ${0};"),
    ("column-width", "column-width: ${0};"),
    ("columns", "columns: ${0};"),
    ("contain", "contain: ${0};"),
    ("content", "content: ${0};"),
    ("corner-shape", "corner-shape: ${0};"),
    ("corners", "corners: ${0};"),
    ("counter-increment", "counter-increment: ${0};"),
    ("counter-reset", "counter-reset: ${0};"),
    ("counter-set", "counter-set: ${0};"),
    ("crop", "crop: ${0};"),
    ("cue", "cue: ${0};"),
    ("cue-after", "cue-after: ${0};"),
    ("cue-before", "cue-before: ${0};"),
    ("cursor", "cursor: ${0};"),
    ("direction", "direction: ${0};"),
    ("display", "display: ${0};"),
    ("display-box", "display-box: ${0};"),
    ("display-extras", "display-extras: ${0};"),
    ("display-inside", "display-inside: ${0};"),
    ("display-outside", "display-outside: ${0};"),
    ("dominant-baseline", "dominant-baseline: ${0};"),
    ("empty-cells", "empty-cells: ${0};"),
    ("fallback", "fallback: ${0};"),
    ("filter", "filter: ${0};"),
    ("flex", "flex: ${0};"),
    ("flex-basis", "flex-basis: ${0};"),
    ("flex-direction", "flex-direction: ${0};"),
    ("flex-flow", "flex-flow: ${0};"),
    ("flex-grow", "flex-grow: ${0};"),
    ("flex-shrink", "flex-shrink: ${0};"),
    ("flex-wrap", "flex-wrap: ${0};"),
    ("float", "float: ${0};"),
    ("float-defer-column", "float-defer-column: ${0};"),
    ("float-defer-page", "float-defer-page: ${0};"),
    ("float-displace", "float-displace: ${0};"),
    ("float-offset", "float-offset: ${0};"),
    ("float-wrap", "float-wrap: ${0};"),
    ("flood-color", "flood-color: ${0};"),
    ("flood-opacity", "flood-opacity: ${0};"),
    ("flow", "flow: ${0};"),
    ("flow-from", "flow-from: ${0};"),
    ("flow-into", "flow-into: ${0};"),
    ("font", "font: ${0};"),
    ("font-family", "font-family: ${0};"),
    ("font-feature-settings", "font-feature-settings: ${0};"),
    ("font-kerning", "font-kerning: ${0};"),
    ("font-language-override", "font-language-override: ${0};"),
    ("font-size", "font-size: ${0};"),
    ("font-size-adjust", "font-size-adjust: ${0};"),
    ("font-stretch", "font-stretch: ${0};"),
    ("font-style", "font-style: ${0};"),
    ("font-synthesis", "font-synthesis: ${0};"),
    ("font-variant", "font-variant: ${0};"),
    ("font-variant-alternates", "font-variant-alternates: ${0};"),
    ("font-variant-caps", "font-variant-caps: ${0};"),
    ("font-variant-east-asian", "font-variant-east-asian: ${0};"),
    ("font-variant-ligatures", "font-variant-ligatures: ${0};"),
    ("font-variant-numeric", "font-variant-numeric: ${0};"),
    ("font-variant-position", "font-variant-position: ${0};"),
    ("font-weight", "font-weight: ${0};"),
    ("footnote-display", "footnote-display: ${0};"),
    ("footnote-policy", "footnote-policy: ${0};"),
    ("grid", "grid: ${0};"),
    ("grid-area", "grid-area: ${0};"),
    ("grid-auto-columns", "grid-auto-columns: ${0};"),
    ("grid-auto-flow", "grid-auto-flow: ${0};"),
    ("grid-auto-rows", "grid-auto-rows: ${0};"),
    ("grid-column", "grid-column: ${0};"),
    ("grid-column-end", "grid-column-end: ${0};"),
    ("grid-column-start", "grid-column-start: ${0};"),
    ("grid-row", "grid-row: ${0};"),
    ("grid-row-end", "grid-row-end: ${0};"),
    ("grid-row-start", "grid-row-start: ${0};"),
    ("grid-template", "grid-template: ${0};"),
    ("grid-template-areas", "grid-template-areas: ${0};"),
    ("grid-template-columns", "grid-template-columns: ${0};"),
    ("grid-template-rows", "grid-template-rows: ${0};"),
    ("hanging-punctuation", "hanging-punctuation: ${0};"),
    ("height", "height: ${0};"),
    ("hyphens", "hyphens: ${0};"),
    ("icon", "icon: ${0};"),
    ("image-orientation", "image-orientation: ${0};"),
    ("image-rendering", "image-rendering: ${0};"),
    ("image-resolution", "image-resolution: ${0};"),
    ("ime-mode", "ime-mode: ${0};"),
    ("indent-edge-reset", "indent-edge-reset: ${0};"),
    ("initial-letters", "initial-letters: ${0};"),
    ("inline-box-align", "inline-box-align: ${0};"),
    ("justify-content", "justify-content: ${0};"),
    ("justify-items", "justify-items: ${0};"),
    ("justify-self", "justify-self: ${0};"),
    ("left", "left: ${0};"),
    ("letter-spacing", "letter-spacing: ${0};"),
    ("lighting-color", "lighting-color: ${0};"),
    ("line-box-contain", "line-box-contain: ${0};"),
    ("line-break", "line-break: ${0};"),
    ("line-grid", "line-grid: ${0};"),
    ("line-height", "line-height: ${0};"),
    ("line-slack", "line-slack: ${0};"),
    ("line-snap", "line-snap: ${0};"),
    ("line-stacking", "line-stacking: ${0};"),
    ("line-stacking-ruby", "line-stacking-ruby: ${0};"),
    ("line-stacking-shift", "line-stacking-shift: ${0};"),
    ("line-stacking-strategy", "line-stacking-strategy: ${0};"),
    ("list-style", "list-style: ${0};"),
    ("list-style-image", "list-style-image: ${0};"),
    ("list-style-position", "list-style-position: ${0};"),
    ("list-style-type", "list-style-type: ${0};"),
    ("margin", "margin: ${0};"),
    ("margin-bottom", "margin-bottom: ${0};"),
    ("margin-left", "margin-left: ${0};"),
    ("margin-right", "margin-right: ${0};"),
    ("margin-top", "margin-top: ${0};"),
    ("marker-side", "marker-side: ${0};"),
    ("marks", "marks: ${0};"),
    ("marquee-direction", "marquee-direction: ${0};"),
    ("marquee-play-count", "marquee-play-count: ${0};"),
    ("marquee-speed", "marquee-speed: ${0};"),
    ("marquee-style", "marquee-style: ${0};"),
    ("mask", "mask: ${0};"),
    ("mask-border", "mask-border: ${0};"),
    ("mask-border-outset", "mask-border-outset: ${0};"),
    ("mask-border-repeat", "mask-border-repeat: ${0};"),
    ("mask-border-slice", "mask-border-slice: ${0};"),
    ("mask-border-source", "mask-border-source: ${0};"),
    ("mask-border-width", "mask-border-width: ${0};"),
    ("mask-clip", "mask-clip: ${0};"),
    ("mask-composite", "mask-composite: ${0};"),
    ("mask-image", "mask-image: ${0};"),
    ("mask-mode", "mask-mode: ${0};"),
    ("mask-origin", "mask-origin: ${0};"),
    ("mask-position", "mask-position: ${0};"),
    ("mask-repeat", "mask-repeat: ${0};"),
    ("mask-size", "mask-size: ${0};"),
    ("mask-type", "mask-type: ${0};"),
    ("max-height", "max-height: ${0};"),
    ("max-lines", "max-lines: ${0};"),
    ("max-width", "max-width: ${0};"),
    ("max-zoom", "max-zoom: ${0};"),
    ("min-height", "min-height: ${0};"),
    ("min-width", "min-width: ${0};"),
    ("min-zoom", "min-zoom: ${0};"),
    ("move-to", "move-to: ${0};"),
    ("nav-down", "nav-down: ${0};"),
    ("nav-index", "nav-index: ${0};"),
    ("nav-left", "nav-left: ${0};"),
    ("nav-right", "nav-right: ${0};"),
    ("nav-up", "nav-up: ${0};"),
    ("negative", "negative: ${0};"),
    ("object-fit", "object-fit: ${0};"),
    ("object-position", "object-position: ${0};"),
    ("offset-after", "offset-after: ${0};"),
    ("offset-before", "offset-before: ${0};"),
    ("offset-end", "offset-end: ${0};"),
    ("offset-start", "offset-start: ${0};"),
    ("opacity", "opacity: ${0};"),
    ("order", "order: ${0};"),
    ("orientation", "orientation: ${0};"),
    ("orphans", "orphans: ${0};"),
    ("outline", "outline: ${0};"),
    ("outline-color", "outline-color: ${0};"),
    ("outline-offset", "outline-offset: ${0};"),
    ("outline-style", "outline-style: ${0};"),
    ("outline-width", "outline-width: ${0};"),
    ("overflow", "overflow: ${0};"),
    ("overflow-style", "overflow-style: ${0};"),
    ("overflow-wrap", "overflow-wrap: ${0};"),
    ("overflow-x", "overflow-x: ${0};"),
    ("overflow-y", "overflow-y: ${0};"),
    ("pad", "pad: ${0};"),
    ("padding", "padding: ${0};"),
    ("padding-bottom", "padding-bottom: ${0};"),
    ("padding-left", "padding-left: ${0};"),
    ("padding-right", "padding-right: ${0};"),
    ("padding-top", "padding-top: ${0};"),
    ("page", "page: ${0};"),
    ("page-break-after", "page-break-after: ${0};"),
    ("page-break-before", "page-break-before: ${0};"),
    ("page-break-inside", "page-break-inside: ${0};"),
    ("page-policy", "page-policy: ${0};"),
    ("pause", "pause: ${0};"),
    ("pause-after", "pause-after: ${0};"),
    ("pause-before", "pause-before: ${0};"),
    ("perspective", "perspective: ${0};"),
    ("perspective-origin", "perspective-origin: ${0};"),
    ("pointer-events", "pointer-events: ${0};"),
    ("position", "position: ${0};"),
    ("prefix", "prefix: ${0};"),
    ("presentation-level", "presentation-level: ${0};"),
    ("quotes", "quotes: ${0};"),
    ("range", "range: ${0};"),
    ("region-fragment", "region-fragment: ${0};"),
    ("resize", "resize: ${0};"),
    ("resolution", "resolution: ${0};"),
    ("rest", "rest: ${0};"),
    ("rest-after", "rest-after: ${0};"),
    ("rest-before", "rest-before: ${0};"),
    ("right", "right: ${0};"),
    ("rotation", "rotation: ${0};"),
    ("rotation-point", "rotation-point: ${0};"),
    ("ruby-align", "ruby-align: ${0};"),
    ("ruby-merge", "ruby-merge: ${0};"),
    ("ruby-position", "ruby-position: ${0};"),
    ("running", "running: ${0};"),
    ("shape-image-threshold", "shape-image-threshold: ${0};"),
    ("shape-margin", "shape-margin: ${0};"),
    ("shape-outside", "shape-outside: ${0};"),
    ("size", "size: ${0};"),
    ("speak", "speak: ${0};"),
    ("speak-as", "speak-as: ${0};"),
    ("src", "src: ${0};"),
    ("string-set", "string-set: ${0};"),
    ("suffix", "suffix: ${0};"),
    ("symbols", "symbols: ${0};"),
    ("system", "system: ${0};"),
    ("tab-size", "tab-size: ${0};"),
    ("table-layout", "table-layout: ${0};"),
    ("target", "target: ${0};"),
    ("target-name", "target-name: ${0};"),
    ("target-new", "target-new: ${0};"),
    ("target-position", "target-position: ${0};"),
    ("text-align", "text-align: ${0};"),
    ("text-align-last", "text-align-last: ${0};"),
    ("text-combine-upright", "text-combine-upright: ${0};"),
    ("text-decoration", "text-decoration: ${0};"),
    ("text-decoration-color", "text-decoration-color: ${0};"),
    ("text-decoration-line", "text-decoration-line: ${0};"),
    ("text-decoration-skip", "text-decoration-skip: ${0};"),
    ("text-decoration-style", "text-decoration-style: ${0};"),
    ("text-emphasis", "text-emphasis: ${0};"),
    ("text-emphasis-color", "text-emphasis-color: ${0};"),
    ("text-emphasis-position", "text-emphasis-position: ${0};"),
    ("text-emphasis-style", "text-emphasis-style: ${0};"),
    ("text-height", "text-height: ${0};"),
    ("text-indent", "text-indent: ${0};"),
    ("text-justify", "text-justify: ${0};"),
    ("text-orientation", "text-orientation: ${0};"),
    ("text-overflow", "text-overflow: ${0};"),
    ("text-shadow", "text-shadow: ${0};"),
    ("text-transform", "text-transform: ${0};"),
    ("text-underline-position", "text-underline-position: ${0};"),
    ("top", "top: ${0};"),
    ("transform", "transform: ${0};"),
    ("transform-origin", "transform-origin: ${0};"),
    ("transform-style", "transform-style: ${0};"),
    ("transition", "transition: ${0};"),
    ("transition-delay", "transition-delay: ${0};"),
    ("transition-duration", "transition-duration: ${0};"),
    ("transition-property", "transition-property: ${0};"),
    ("transition-timing-function", "transition-timing-function: ${0};"),
    ("unicode-bidi", "unicode-bidi: ${0};"),
    ("unicode-range", "unicode-range: ${0};"),
    ("user-zoom", "user-zoom: ${0};"),
    ("vertical-align", "vertical-align: ${0};"),
    ("visibility", "visibility: ${0};"),
    ("voice-balance", "voice-balance: ${0};"),
    ("voice-duration", "voice-duration: ${0};"),
    ("voice-family", "voice-family: ${0};"),
    ("voice-pitch", "voice-pitch: ${0};"),
    ("voice-range", "voice-range: ${0};"),
    ("voice-rate", "voice-rate: ${0};"),
    ("voice-stress", "voice-stress: ${0};"),
    ("voice-volume", "voice-volume: ${0};"),
    ("white-space", "white-space: ${0};"),
    ("widows", "widows: ${0};"),
    ("width", "width: ${0};"),
    ("will-change", "will-change: ${0};"),
    ("word-break", "word-break: ${0};"),
    ("word-spacing", "word-spacing: ${0};"),
    ("word-wrap", "word-wrap: ${0};"),
    ("wrap-flow", "wrap-flow: ${0};"),
    ("wrap-through", "wrap-through: ${0};"),
    ("writing-mode", "writing-mode: ${0};"),
    ("z-index", "z-index: ${0};"),
    ("zoom", "zoom: ${0}; ")
]


all_values = [
    ("inherit",),
    ("initial",),
    ("unset",),
    ("attr()", "attr(${1:attribute-name})"),
    ("toggle()", "toggle(${1})"),
    ("var()", "var(--${1:custom-name}, ${2:value})")
]
box_sizing = [("border-box",), ("content-box",), ("padding-box",)]
calc = ("calc()", "calc(${1:expression})")
color = [
    ("aliceblue",),
    ("antiquewhite",),
    ("aqua",),
    ("aquamarine",),
    ("azure",),
    ("beige",),
    ("bisque",),
    ("black",),
    ("blanchedalmond",),
    ("blue",),
    ("blueviolet",),
    ("brown",),
    ("burlywood",),
    ("cadetblue",),
    ("chartreuse",),
    ("chocolate",),
    ("coral",),
    ("cornflowerblue",),
    ("cornsilk",),
    ("crimson",),
    ("currentColor",),
    ("cyan",),
    ("darkblue",),
    ("darkcyan",),
    ("darkgoldenrod",),
    ("darkgray",),
    ("darkgreen",),
    ("darkgrey",),
    ("darkkhaki",),
    ("darkmagenta",),
    ("darkolivegreen",),
    ("darkorange",),
    ("darkorchid",),
    ("darkred",),
    ("darksalmon",),
    ("darkseagreen",),
    ("darkslateblue",),
    ("darkslategray",),
    ("darkslategrey",),
    ("darkturquoise",),
    ("darkviolet",),
    ("deeppink",),
    ("deepskyblue",),
    ("dimgray",),
    ("dimgrey",),
    ("dodgerblue",),
    ("firebrick",),
    ("floralwhite",),
    ("forestgreen",),
    ("fuchsia",),
    ("gainsboro",),
    ("ghostwhite",),
    ("gold",),
    ("goldenrod",),
    ("gray",),
    ("green",),
    ("greenyellow",),
    ("grey",),
    ("honeydew",),
    ("hotpink",),
    ("hsl()", "hsl(${1:0}, ${2:0}, ${3:0})"),
    ("hsla()", "hsl(${1:0}, ${2:0}, ${3:0}, ${4:0.0})"),
    ("indianred",),
    ("indigo",),
    ("ivory",),
    ("khaki",),
    ("lavender",),
    ("lavenderblush",),
    ("lawngreen",),
    ("lemonchiffon",),
    ("lightblue",),
    ("lightcoral",),
    ("lightcyan",),
    ("lightgoldenrodyellow",),
    ("lightgray",),
    ("lightgreen",),
    ("lightgrey",),
    ("lightpink",),
    ("lightsalmon",),
    ("lightseagreen",),
    ("lightskyblue",),
    ("lightslategray",),
    ("lightslategrey",),
    ("lightsteelblue",),
    ("lightyellow",),
    ("lime",),
    ("limegreen",),
    ("linen",),
    ("magenta",),
    ("maroon",),
    ("mediumaquamarine",),
    ("mediumblue",),
    ("mediumorchid",),
    ("mediumpurple",),
    ("mediumseagreen",),
    ("mediumslateblue",),
    ("mediumspringgreen",),
    ("mediumturquoise",),
    ("mediumvioletred",),
    ("midnightblue",),
    ("mintcream",),
    ("mistyrose",),
    ("moccasin",),
    ("navajowhite",),
    ("navy",),
    ("oldlace",),
    ("olive",),
    ("olivedrab",),
    ("orange",),
    ("orangered",),
    ("orchid",),
    ("palegoldenrod",),
    ("palegreen",),
    ("paleturquoise",),
    ("palevioletred",),
    ("papayawhip",),
    ("peachpuff",),
    ("peru",),
    ("pink",),
    ("plum",),
    ("powderblue",),
    ("purple",),
    ("rebeccapurple",),
    ("red",),
    ("rgb()", "rgb(${1:0}, ${2:0}, ${3:0})"),
    ("rgba()", "rgb(${1:0}, ${2:0}, ${3:0}, ${4:0.0})"),
    ("rosybrown",),
    ("royalblue",),
    ("saddlebrown",),
    ("salmon",),
    ("sandybrown",),
    ("seagreen",),
    ("seashell",),
    ("sienna",),
    ("silver",),
    ("skyblue",),
    ("slateblue",),
    ("slategray",),
    ("slategrey",),
    ("snow",),
    ("springgreen",),
    ("steelblue",),
    ("tan",),
    ("teal",),
    ("thistle",),
    ("tomato",),
    ("transparent",),
    ("turquoise",),
    ("violet",),
    ("wheat",),
    ("white",),
    ("whitesmoke",),
    ("yellow",),
    ("yellowgreen",),
]
columns = [("auto",), calc, integer, length, ("medium",), ("thick",), ("thin",)]
column_count = [("auto",), calc, integer]
column_fill = [("auto",), ("balance",)]
column_gap = [calc, length, ("normal",)]
# Sorting is necessary because the list of colors is mixed in.
column_rule = list(sorted([calc, length, ("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",)] + color))
column_rule_style = [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)]
column_rule_width = [calc, length, ("medium",), ("thick",), ("thin",)]
column_span = [("all",), ("none",)]
column_width = [("auto",), calc, length]
flow_from = [("content",), ("element",), ("<ident>",), ("none",)]
flow_into = [("<ident>",), ("none",)]
font_feature_settings = [calc, ("<integer>",), ("off",), ("on",), ("normal",), ("<string>", '"${1:aaaa}"')]
font_language_override = [("normal",), ("<string>", '"${1:aaa}"')]
grid_column = grid_row = [("auto",), ident, integer, ("span",)]
hyphens = [("auto",), ("manual",), ("none",)]
ime_mode = [("active",), ("auto",), ("disabled",), ("inactive",), ("inherit",), ("normal",)]
integer = ("<integer>", "${1:<integer>}")
ident = ("<ident>", "${1:<ident>}")
length = ("<length>", "${1:<length>}")
matrix      = ("matrix()", "matrix(${1:0}, ${2:0}, ${3:0}, ${4:0}, ${5:0}, ${6:0})")
matrix3d    = ("matrix3d()", "matrix3d(${1:0}, ${2:0}, ${3:0}, ${4:0}, ${5:0}, ${6:0}, ${7:0}, ${8:0}, ${9:0}, ${10:0}, ${11:0}, ${12:0}, ${13:0}, ${14:0}, ${15:0}, ${16:0})")
overflow_style = [("auto",), ("marquee-block",), ("marquee-line",)]
overflow_x = overflow_y = [("auto",), ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)]
percentage = ("<percentage>", "${1:0}%")
perspective = ("perspective()", "perspective(${1:<length>})")
rotate      = ("rotate()", "rotate(${1:<angle>})")
rotate3d    = ("rotate3d()", "rotate3d(${1:0}, ${2:0}, ${3:0}, ${4:<angle>})")
rotateX     = ("rotateX()", "rotateX(${1:<angle>})")
rotateY     = ("rotateY()", "rotateY(${1:<angle>})")
rotateZ     = ("rotateZ()", "rotateZ(${1:<angle>})")
scale       = ("scale()", "scale(${1:0}${2:, ${3:0}})")
scale3d     = ("scale3d()", "scale3d(${1:0}, ${2:0}, ${3:0})")
scaleX      = ("scaleX()", "scaleX(${1:0})")
scaleY      = ("scaleY()", "scaleY(${1:0})")
scaleZ      = ("scaleZ()", "scaleZ(${1:0})")
skew        = ("skew()", "skew(${1:<angle>}${2:, ${3:<angle>}})")
skewX       = ("skewX()", "skewX(${1:<angle>})")
skewY       = ("skewY()", "skewY(${1:<angle>})")
text_align_last = [("auto",), ("center",), ("end",), ("justify",), ("left",), ("right",), ("start",)]
text_justify = [("auto",), ("distribute",), ("inter-word",), ("none",)]
text_decoration_line = [("line-through blink",), ("none",), ("overline",), ("underline",)]
text_decoration_style = [("dashed",), ("dotted",), ("double",), ("solid",), ("wavy",)]
transform = [matrix, matrix3d, perspective, rotate, rotate3d, rotateX, rotateY, rotateZ, scale, scale3d, scaleX, scaleY, scaleZ, skew, skewX, skewY, translate, translate3d, translateX, translateY, translateZ]
transform_origin = [("bottom",), ("center",), ("left",), length, percentage, ("right",), ("top",)]
transform_style = [("flat",), ("preserve-3d",)]
translate   = ("translate()", "translate(${1:<length>}${2:, ${3:<length>}})")
translate3d = ("translate3d()", "translate3d(${1:<length>}, ${2:<length>}, ${3:<length>})")
translateX  = ("translateX()", "translateX(${1:<length>})")
translateY  = ("translateY()", "translateY(${1:<length>})")
translateZ  = ("translateZ()", "translateX(${1:<length>})")
word_wrap = [("break-word",), ("normal",)]
wrap_flow = [("auto",), ("both",), ("clear",), ("end",), ("maximum",), ("minimum",), ("start",)]
wrap_through = [("none",), ("wrap",)]
writing_mode = [("horizontal-tb",), ("vertical-lr",), ("vertical-rl",)]



property_values = {
    "-moz-box-sizing": box_sizing,
    "-moz-column-count": column_count,
    "-moz-column-fill": column_fill,
    "-moz-column-gap": column_gap,
    "-moz-column-rule": column_rule,
    "-moz-column-rule-color": color,
    "-moz-column-rule-style": column_rule_style,    # TODO: can this be replaced by column width?
    "-moz-column-rule-width": column_rule_width,    # TODO: can this be replaced by column width?
    "-moz-column-span": column_span,
    "-moz-column-width": column_width,
    "-moz-columns": columns,
    "-moz-font-feature-settings": font_feature_settings,
    "-moz-font-language-override": font_language_override,
    "-moz-hyphens": hyphens,
    "-moz-text-align-last": text_align_last,
    "-moz-text-decoration-color": color,
    "-moz-text-decoration-line": text_decoration_line,
    "-moz-text-decoration-style": text_decoration_style,
    "-ms-flow-from": flow_from,
    "-ms-flow-into": flow_into,
    "-ms-grid-column": grid_column,
    "-ms-grid-row": grid_row,
    "-ms-hyphens": hyphens,
    "-ms-ime-mode": ime_mode,
    "-ms-overflow-style": overflow_style,
    "-ms-overflow-x": overflow_x,
    "-ms-overflow-y": overflow_y,
    "-ms-text-align-last": text_align_last,
    "-ms-text-justify": text_justify,
    "-ms-transform": transform,
    "-ms-transform-origin": transform_origin,
    "-ms-transform-style": transform_style,
    "-ms-word-wrap": word_wrap,
    "-ms-wrap-flow": wrap_flow,
    "-ms-wrap-through": wrap_through,
    "-ms-writing-mode": writing_mode,
    "-webkit-align-content": [],
    "-webkit-align-items": [],
    "-webkit-align-self": [],
    "-webkit-animation": [],
    "-webkit-animation-delay": [],
    "-webkit-animation-direction": [],
    "-webkit-animation-duration": [],
    "-webkit-animation-fill-mode": [],
    "-webkit-animation-iteration-count": [],
    "-webkit-animation-name": [],
    "-webkit-animation-play-state": [],
    "-webkit-animation-timing-function": [],
    "-webkit-backface-visibility": [],
    "-webkit-border-image": [],
    "-webkit-break-after": [],
    "-webkit-break-before": [],
    "-webkit-break-inside": [],
    "-webkit-column-count": column_count,
    "-webkit-column-fill": column_fill,
    "-webkit-column-gap": column_gap,
    "-webkit-column-rule": column_rule,
    "-webkit-column-rule-color": color,
    "-webkit-column-rule-style": column_rule_style, # TODO: can this be replaced by border_width?
    "-webkit-column-rule-width": column_rule_width, # TODO: can this be replaced by column width?
    "-webkit-column-span": column_span,
    "-webkit-column-width": column_width,
    "-webkit-columns": columns,
    "-webkit-flex": [],
    "-webkit-flex-basis": [],
    "-webkit-flex-direction": [],
    "-webkit-flex-flow": [],
    "-webkit-flex-grow": [],
    "-webkit-flex-shrink": [],
    "-webkit-flex-wrap": [],
    "-webkit-flow-from": flow_from,
    "-webkit-flow-into": flow_into,
    "-webkit-font-feature-settings": font_feature_settings,
    "-webkit-font-kerning": [],
    "-webkit-font-size-delta": [],
    "-webkit-font-variant-ligatures": [],
    "-webkit-grid-column": [],
    "-webkit-grid-row": [],
    "-webkit-hyphens": hyphens,
    "-webkit-justify-content": [],
    "-webkit-order": [],
    "-webkit-perspective": [],
    "-webkit-perspective-origin": [],
    "-webkit-region-fragment": [],
    "-webkit-transform": transform,
    "-webkit-transform-origin": transform_origin,
    "-webkit-transform-style": transform_style,
    "-webkit-transition": [],
    "-webkit-transition-delay": [],
    "-webkit-transition-duration": [],
    "-webkit-transition-property": [],
    "-webkit-transition-timing-function": [],
    "additive-symbols": [],
    "align-content": [],
    "align-items": [],
    "align-self": [],
    "alignment": [],
    "alignment-adjust": [],
    "alignment-baseline": [],
    "all": [],
    "anchor-point": [],
    "animation": [],
    "animation-delay": [],
    "animation-direction": [],
    "animation-duration": [],
    "animation-fill-mode": [],
    "animation-iteration-count": [],
    "animation-name": [],
    "animation-play-state": [],
    "animation-timing-function": [],
    "backface-visibility": [],
    "background": [],
    "background-attachment": [],
    "background-clip": [],
    "background-color": [],
    "background-image": [],
    "background-origin": [],
    "background-position": [],
    "background-repeat": [],
    "background-size": [],
    "baseline-shift": [],
    "bleed": [],
    "bookmark-label": [],
    "bookmark-level": [],
    "bookmark-state": [],
    "border": [],
    "border-bottom": [],
    "border-bottom-color": [],
    "border-bottom-left-radius": [],
    "border-bottom-right-radius": [],
    "border-bottom-style": [],
    "border-bottom-width": [],
    "border-clip": [],
    "border-clip-bottom": [],
    "border-clip-left": [],
    "border-clip-right": [],
    "border-clip-top": [],
    "border-collapse": [],
    "border-color": [],
    "border-image": [],
    "border-image-outset": [],
    "border-image-repeat": [],
    "border-image-slice": [],
    "border-image-source": [],
    "border-image-width": [],
    "border-left": [],
    "border-left-color": [],
    "border-left-style": [],
    "border-left-width": [],
    "border-limit": [],
    "border-radius": [],
    "border-right": [],
    "border-right-color": [],
    "border-right-style": [],
    "border-right-width": [],
    "border-spacing": [],
    "border-style": [],
    "border-top": [],
    "border-top-color": [],
    "border-top-left-radius": [],
    "border-top-right-radius": [],
    "border-top-style": [],
    "border-top-width": [],
    "border-width": [],
    "bottom": [],
    "box-decoration-break": [],
    "box-shadow": [],
    "box-sizing": box_sizing,
    "box-snap": [],
    "break-after": [],
    "break-before": [],
    "break-inside": [],
    "caption-side": [],
    "chains": [],
    "child-align": [],
    "clear": [],
    "clear-after": [],
    "clear-side": [],
    "clip-path": [],
    "clip-rule": [],
    "color": [],
    "color-correction": [],
    "color-interpolation-filters": [],
    "column-count": column_count,
    "column-fill": column_fill,
    "column-gap": column_gap,
    "column-rule": column_rule,
    "column-rule-color": color,
    "column-rule-style": column_rule_style,     # TODO: can this be replaced by border_width?
    "column-rule-width": column_rule_width,     # TODO: can this be replaced by border_width?
    "column-span": column_span,
    "column-width": column_width,
    "columns": [],
    "contain": [],
    "content": [],
    "corner-shape": [],
    "corners": [],
    "counter-increment": [],
    "counter-reset": [],
    "counter-set": [],
    "crop": [],
    "cue": [],
    "cue-after": [],
    "cue-before": [],
    "cursor": [],
    "direction": [],
    "display": [],
    "display-box": [],
    "display-extras": [],
    "display-inside": [],
    "display-outside": [],
    "dominant-baseline": [],
    "empty-cells": [],
    "fallback": [],
    "filter": [],
    "flex": [],
    "flex-basis": [],
    "flex-direction": [],
    "flex-flow": [],
    "flex-grow": [],
    "flex-shrink": [],
    "flex-wrap": [],
    "float": [],
    "float-defer-column": [],
    "float-defer-page": [],
    "float-displace": [],
    "float-offset": [],
    "float-wrap": [],
    "flood-color": [],
    "flood-opacity": [],
    "flow": [],
    "flow-from": flow_from,
    "flow-into": flow_into,
    "font": [],
    "font-family": [],
    "font-feature-settings": font_feature_settings,
    "font-kerning": [],
    "font-language-override": font_language_override,
    "font-size": [],
    "font-size-adjust": [],
    "font-stretch": [],
    "font-style": [],
    "font-synthesis": [],
    "font-variant": [],
    "font-variant-alternates": [],
    "font-variant-caps": [],
    "font-variant-east-asian": [],
    "font-variant-ligatures": [],
    "font-variant-numeric": [],
    "font-variant-position": [],
    "font-weight": [],
    "footnote-display": [],
    "footnote-policy": [],
    "grid": [],
    "grid-area": [],
    "grid-auto-columns": [],
    "grid-auto-flow": [],
    "grid-auto-rows": [],
    "grid-column": grid_column,
    "grid-column-end": [],
    "grid-column-start": [],
    "grid-row": grid_row,
    "grid-row-end": [],
    "grid-row-start": [],
    "grid-template": [],
    "grid-template-areas": [],
    "grid-template-columns": [],
    "grid-template-rows": [],
    "hanging-punctuation": [],
    "height": [],
    "hyphens": hyphens,
    "icon": [],
    "image-orientation": [],
    "image-rendering": [],
    "image-resolution": [],
    "ime-mode": ime_mode,
    "indent-edge-reset": [],
    "initial-letters": [],
    "inline-box-align": [],
    "justify-content": [],
    "justify-items": [],
    "justify-self": [],
    "left": [],
    "letter-spacing": [],
    "lighting-color": [],
    "line-box-contain": [],
    "line-break": [],
    "line-grid": [],
    "line-height": [],
    "line-slack": [],
    "line-snap": [],
    "line-stacking": [],
    "line-stacking-ruby": [],
    "line-stacking-shift": [],
    "line-stacking-strategy": [],
    "list-style": [],
    "list-style-image": [],
    "list-style-position": [],
    "list-style-type": [],
    "margin": [],
    "margin-bottom": [],
    "margin-left": [],
    "margin-right": [],
    "margin-top": [],
    "marker-side": [],
    "marks": [],
    "marquee-direction": [],
    "marquee-play-count": [],
    "marquee-speed": [],
    "marquee-style": [],
    "mask": [],
    "mask-border": [],
    "mask-border-outset": [],
    "mask-border-repeat": [],
    "mask-border-slice": [],
    "mask-border-source": [],
    "mask-border-width": [],
    "mask-clip": [],
    "mask-composite": [],
    "mask-image": [],
    "mask-mode": [],
    "mask-origin": [],
    "mask-position": [],
    "mask-repeat": [],
    "mask-size": [],
    "mask-type": [],
    "max-height": [],
    "max-lines": [],
    "max-width": [],
    "max-zoom": [],
    "min-height": [],
    "min-width": [],
    "min-zoom": [],
    "move-to": [],
    "nav-down": [],
    "nav-index": [],
    "nav-left": [],
    "nav-right": [],
    "nav-up": [],
    "negative": [],
    "object-fit": [],
    "object-position": [],
    "offset-after": [],
    "offset-before": [],
    "offset-end": [],
    "offset-start": [],
    "opacity": [],
    "order": [],
    "orientation": [],
    "orphans": [],
    "outline": [],
    "outline-color": [],
    "outline-offset": [],
    "outline-style": [],
    "outline-width": [],
    "overflow": [],
    "overflow-style": overflow_style,
    "overflow-wrap": word_wrap,
    "overflow-x": overflow_x,
    "overflow-y": overflow_y,
    "pad": [],
    "padding": [],
    "padding-bottom": [],
    "padding-left": [],
    "padding-right": [],
    "padding-top": [],
    "page": [],
    "page-break-after": [],
    "page-break-before": [],
    "page-break-inside": [],
    "page-policy": [],
    "pause": [],
    "pause-after": [],
    "pause-before": [],
    "perspective": [],
    "perspective-origin": [],
    "pointer-events": [],
    "position": [],
    "prefix": [],
    "presentation-level": [],
    "quotes": [],
    "range": [],
    "region-fragment": [],
    "resize": [],
    "resolution": [],
    "rest": [],
    "rest-after": [],
    "rest-before": [],
    "right": [],
    "rotation": [],
    "rotation-point": [],
    "ruby-align": [],
    "ruby-merge": [],
    "ruby-position": [],
    "running": [],
    "shape-image-threshold": [],
    "shape-margin": [],
    "shape-outside": [],
    "size": [],
    "speak": [],
    "speak-as": [],
    "src": [],
    "string-set": [],
    "suffix": [],
    "symbols": [],
    "system": [],
    "tab-size": [],
    "table-layout": [],
    "target": [],
    "target-name": [],
    "target-new": [],
    "target-position": [],
    "text-align": [],
    "text-align-last": text_align_last,
    "text-combine-upright": [],
    "text-decoration": [],
    "text-decoration-color": color,
    "text-decoration-line": text_decoration_line,
    "text-decoration-skip": [],
    "text-decoration-style": text_decoration_style,
    "text-emphasis": [],
    "text-emphasis-color": [],
    "text-emphasis-position": [],
    "text-emphasis-style": [],
    "text-height": [],
    "text-indent": [],
    "text-justify": text_justify,
    "text-orientation": [],
    "text-overflow": [],
    "text-shadow": [],
    "text-transform": [],
    "text-underline-position": [],
    "top": [],
    "transform": transform,
    "transform-origin": transform_origin,
    "transform-style": transform_style,
    "transition": [],
    "transition-delay": [],
    "transition-duration": [],
    "transition-property": [],
    "transition-timing-function": [],
    "unicode-bidi": [],
    "unicode-range": [],
    "user-zoom": [],
    "vertical-align": [],
    "visibility": [],
    "voice-balance": [],
    "voice-duration": [],
    "voice-family": [],
    "voice-pitch": [],
    "voice-range": [],
    "voice-rate": [],
    "voice-stress": [],
    "voice-volume": [],
    "white-space": [],
    "widows": [],
    "width": [],
    "will-change": [],
    "word-break": [],
    "word-spacing": [],
    "word-wrap": word_wrap,
    "wrap-flow": wrap_flow,
    "wrap-through": wrap_through,
    "writing-mode": writing_mode,
    "z-index": [],
    "zoom": []
}

# TODO
#   add property values for all prefixed props
#   break properties and values into different files and import them
