import re
import sublime
import sublime_plugin


INHIBIT_DEFAULTS = sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS
property_name_rx = re.compile(r"(?P<prop_name>[-a-z]+):")


class CSS6Completions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        trigger_start = locations[0] - len(prefix)

        # Completions is a list of (<trigger>, <completion>) tuples. Completions
        # are only offered for properties and values.
        completions = []
        if view.match_selector(trigger_start, "meta.property-name.css"):
            completions = property_names
        elif view.match_selector(trigger_start, "meta.value.css"):
            trigger_start = locations[0] - len(prefix)
            line = view.substr(view.line(trigger_start)).strip()
            matches = property_name_rx.search(line)
            if matches is not None:
                prop_name = matches.group("prop_name")
                if prop_name in property_values:
                    completions = property_values[prop_name] + all_values

        return completions, INHIBIT_DEFAULTS


property_names = [
    ("additive-symbols", "additive-symbols: ${0};"),
    ("align-content", "align-content: ${0};"),
    ("align-items", "align-items: ${0};"),
    ("align-self", "align-self: ${0};"),
    ("alignment", "alignment: ${0};"),
    ("alignment-adjust", "alignment-adjust: ${0};"),
    ("alignment-baseline", "alignment-baseline: ${0};"),
    ("all", "all: ${0};"),
    ("animation", "animation: ${0};"),
    ("animation-delay", "animation-delay: ${0};"),
    ("animation-direction", "animation-direction: ${0};"),
    ("animation-duration", "animation-duration: ${0};"),
    ("animation-fill-mode", "animation-fill-mode: ${0};"),
    ("animation-iteration-count", "animation-iteration-count: ${0};"),
    ("animation-name", "animation-name: ${0};"),
    ("animation-play-state", "animation-play-state: ${0};"),
    ("animation-timing-function", "animation-timing-function: ${0};"),
    ("backface-visibility", "backface-visibility: ${0};"),
    ("background", "background: ${0};"),
    ("background-attachment", "background-attachment: ${0};"),
    ("background-clip", "background-clip: ${0};"),
    ("background-color", "background-color: ${0};"),
    ("background-image", "background-image: ${0};"),
    ("background-origin", "background-origin: ${0};"),
    ("background-position", "background-position: ${0};"),
    ("background-repeat", "background-repeat: ${0};"),
    ("background-size", "background-size: ${0};"),
    ("baseline-shift", "baseline-shift: ${0};"),
    ("bleed", "bleed: ${0};"),
    ("bookmark-label", "bookmark-label: ${0};"),
    ("bookmark-level", "bookmark-level: ${0};"),
    ("bookmark-state", "bookmark-state: ${0};"),
    ("border", "border: ${0};"),
    ("border-bottom", "border-bottom: ${0};"),
    ("border-bottom-color", "border-bottom-color: ${0};"),
    ("border-bottom-left-radius", "border-bottom-left-radius: ${0};"),
    ("border-bottom-right-radius", "border-bottom-right-radius: ${0};"),
    ("border-bottom-style", "border-bottom-style: ${0};"),
    ("border-bottom-width", "border-bottom-width: ${0};"),
    ("border-clip", "border-clip: ${0};"),
    ("border-clip-bottom", "border-clip-bottom: ${0};"),
    ("border-clip-left", "border-clip-left: ${0};"),
    ("border-clip-right", "border-clip-right: ${0};"),
    ("border-clip-top", "border-clip-top: ${0};"),
    ("border-collapse", "border-collapse: ${0};"),
    ("border-color", "border-color: ${0};"),
    ("border-image", "border-image: ${0};"),
    ("border-image-outset", "border-image-outset: ${0};"),
    ("border-image-repeat", "border-image-repeat: ${0};"),
    ("border-image-slice", "border-image-slice: ${0};"),
    ("border-image-source", "border-image-source: ${0};"),
    ("border-image-width", "border-image-width: ${0};"),
    ("border-left", "border-left: ${0};"),
    ("border-left-color", "border-left-color: ${0};"),
    ("border-left-style", "border-left-style: ${0};"),
    ("border-left-width", "border-left-width: ${0};"),
    ("border-limit", "border-limit: ${0};"),
    ("border-radius", "border-radius: ${0};"),
    ("border-right", "border-right: ${0};"),
    ("border-right-color", "border-right-color: ${0};"),
    ("border-right-style", "border-right-style: ${0};"),
    ("border-right-width", "border-right-width: ${0};"),
    ("border-spacing", "border-spacing: ${0};"),
    ("border-style", "border-style: ${0};"),
    ("border-top", "border-top: ${0};"),
    ("border-top-color", "border-top-color: ${0};"),
    ("border-top-left-radius", "border-top-left-radius: ${0};"),
    ("border-top-right-radius", "border-top-right-radius: ${0};"),
    ("border-top-style", "border-top-style: ${0};"),
    ("border-top-width", "border-top-width: ${0};"),
    ("border-width", "border-width: ${0};"),
    ("bottom", "bottom: ${0};"),
    ("box-decoration-break", "box-decoration-break: ${0};"),
    ("box-shadow", "box-shadow: ${0};"),
    ("box-sizing", "box-sizing: ${0};"),
    ("box-snap", "box-snap: ${0};"),
    ("break-after", "break-after: ${0};"),
    ("break-before", "break-before: ${0};"),
    ("break-inside", "break-inside: ${0};"),
    ("caption-side", "caption-side: ${0};"),
    ("chains", "chains: ${0};"),
    ("child-align", "child-align: ${0};"),
    ("clear", "clear: ${0};"),
    ("clear-after", "clear-after: ${0};"),
    ("clear-side", "clear-side: ${0};"),
    ("clip-path", "clip-path: ${0};"),
    ("clip-rule", "clip-rule: ${0};"),
    ("color", "color: ${0};"),
    ("color-correction", "color-correction: ${0};"),
    ("color-interpolation", "color-interpolation: ${0};"),
    ("color-interpolation-filters", "color-interpolation-filters: ${0};"),
    ("column-count", "column-count: ${0};"),
    ("column-fill", "column-fill: ${0};"),
    ("column-gap", "column-gap: ${0};"),
    ("column-rule", "column-rule: ${0};"),
    ("column-rule-color", "column-rule-color: ${0};"),
    ("column-rule-style", "column-rule-style: ${0};"),
    ("column-rule-width", "column-rule-width: ${0};"),
    ("column-span", "column-span: ${0};"),
    ("column-width", "column-width: ${0};"),
    ("columns", "columns: ${0};"),
    ("contain", "contain: ${0};"),
    ("content", "content: ${0};"),
    ("corner-shape", "corner-shape: ${0};"),
    ("corners", "corners: ${0};"),
    ("counter-increment", "counter-increment: ${0};"),
    ("counter-reset", "counter-reset: ${0};"),
    ("counter-set", "counter-set: ${0};"),
    ("cue", "cue: ${0};"),
    ("cue-after", "cue-after: ${0};"),
    ("cue-before", "cue-before: ${0};"),
    ("cursor", "cursor: ${0};"),
    ("direction", "direction: ${0};"),
    ("display", "display: ${0};"),
    ("display-box", "display-box: ${0};"),
    ("display-extras", "display-extras: ${0};"),
    ("display-inside", "display-inside: ${0};"),
    ("display-outside", "display-outside: ${0};"),
    ("dominant-baseline", "dominant-baseline: ${0};"),
    ("empty-cells", "empty-cells: ${0};"),
    ("fallback", "fallback: ${0};"),
    ("filter", "filter: ${0};"),
    ("flex", "flex: ${0};"),
    ("flex-basis", "flex-basis: ${0};"),
    ("flex-direction", "flex-direction: ${0};"),
    ("flex-flow", "flex-flow: ${0};"),
    ("flex-grow", "flex-grow: ${0};"),
    ("flex-shrink", "flex-shrink: ${0};"),
    ("flex-wrap", "flex-wrap: ${0};"),
    ("float", "float: ${0};"),
    ("float-defer-column", "float-defer-column: ${0};"),
    ("float-defer-page", "float-defer-page: ${0};"),
    ("float-displace", "float-displace: ${0};"),
    ("float-offset", "float-offset: ${0};"),
    ("float-wrap", "float-wrap: ${0};"),
    ("flood-color", "flood-color: ${0};"),
    ("flood-opacity", "flood-opacity: ${0};"),
    ("flow", "flow: ${0};"),
    ("flow-from", "flow-from: ${0};"),
    ("flow-into", "flow-into: ${0};"),
    ("font", "font: ${0};"),
    ("font-family", "font-family: ${0};"),
    ("font-feature-settings", "font-feature-settings: ${0};"),
    ("font-kerning", "font-kerning: ${0};"),
    ("font-language-override", "font-language-override: ${0};"),
    ("font-size", "font-size: ${0};"),
    ("font-size-adjust", "font-size-adjust: ${0};"),
    ("font-stretch", "font-stretch: ${0};"),
    ("font-style", "font-style: ${0};"),
    ("font-synthesis", "font-synthesis: ${0};"),
    ("font-variant", "font-variant: ${0};"),
    ("font-variant-alternates", "font-variant-alternates: ${0};"),
    ("font-variant-caps", "font-variant-caps: ${0};"),
    ("font-variant-east-asian", "font-variant-east-asian: ${0};"),
    ("font-variant-ligatures", "font-variant-ligatures: ${0};"),
    ("font-variant-numeric", "font-variant-numeric: ${0};"),
    ("font-variant-position", "font-variant-position: ${0};"),
    ("font-weight", "font-weight: ${0};"),
    ("footnote-display", "footnote-display: ${0};"),
    ("footnote-policy", "footnote-policy: ${0};"),
    ("grid", "grid: ${0};"),
    ("grid-area", "grid-area: ${0};"),
    ("grid-auto-columns", "grid-auto-columns: ${0};"),
    ("grid-auto-flow", "grid-auto-flow: ${0};"),
    ("grid-auto-rows", "grid-auto-rows: ${0};"),
    ("grid-column", "grid-column: ${0};"),
    ("grid-column-end", "grid-column-end: ${0};"),
    ("grid-column-start", "grid-column-start: ${0};"),
    ("grid-row", "grid-row: ${0};"),
    ("grid-row-end", "grid-row-end: ${0};"),
    ("grid-row-start", "grid-row-start: ${0};"),
    ("grid-template", "grid-template: ${0};"),
    ("grid-template-areas", "grid-template-areas: ${0};"),
    ("grid-template-columns", "grid-template-columns: ${0};"),
    ("grid-template-rows", "grid-template-rows: ${0};"),
    ("hanging-punctuation", "hanging-punctuation: ${0};"),
    ("height", "height: ${0};"),
    ("hyphens", "hyphens: ${0};"),
    ("icon", "icon: ${0};"),
    ("image-orientation", "image-orientation: ${0};"),
    ("image-rendering", "image-rendering: ${0};"),
    ("image-resolution", "image-resolution: ${0};"),
    ("ime-mode", "ime-mode: ${0};"),
    ("indent-edge-reset", "indent-edge-reset: ${0};"),
    ("initial-letters", "initial-letters: ${0};"),
    ("inline-box-align", "inline-box-align: ${0};"),
    ("justify-content", "justify-content: ${0};"),
    ("justify-items", "justify-items: ${0};"),
    ("justify-self", "justify-self: ${0};"),
    ("left", "left: ${0};"),
    ("letter-spacing", "letter-spacing: ${0};"),
    ("lighting-color", "lighting-color: ${0};"),
    ("line-box-contain", "line-box-contain: ${0};"),
    ("line-break", "line-break: ${0};"),
    ("line-grid", "line-grid: ${0};"),
    ("line-height", "line-height: ${0};"),
    ("line-slack", "line-slack: ${0};"),
    ("line-snap", "line-snap: ${0};"),
    ("line-stacking", "line-stacking: ${0};"),
    ("line-stacking-ruby", "line-stacking-ruby: ${0};"),
    ("line-stacking-shift", "line-stacking-shift: ${0};"),
    ("line-stacking-strategy", "line-stacking-strategy: ${0};"),
    ("list-style", "list-style: ${0};"),
    ("list-style-image", "list-style-image: ${0};"),
    ("list-style-position", "list-style-position: ${0};"),
    ("list-style-type", "list-style-type: ${0};"),
    ("margin", "margin: ${0};"),
    ("margin-bottom", "margin-bottom: ${0};"),
    ("margin-left", "margin-left: ${0};"),
    ("margin-right", "margin-right: ${0};"),
    ("margin-top", "margin-top: ${0};"),
    ("marker-side", "marker-side: ${0};"),
    ("marks", "marks: ${0};"),
    ("marquee-direction", "marquee-direction: ${0};"),
    ("marquee-play-count", "marquee-play-count: ${0};"),
    ("marquee-speed", "marquee-speed: ${0};"),
    ("marquee-style", "marquee-style: ${0};"),
    ("mask", "mask: ${0};"),
    ("mask-border", "mask-border: ${0};"),
    ("mask-border-outset", "mask-border-outset: ${0};"),
    ("mask-border-repeat", "mask-border-repeat: ${0};"),
    ("mask-border-slice", "mask-border-slice: ${0};"),
    ("mask-border-source", "mask-border-source: ${0};"),
    ("mask-border-width", "mask-border-width: ${0};"),
    ("mask-clip", "mask-clip: ${0};"),
    ("mask-composite", "mask-composite: ${0};"),
    ("mask-image", "mask-image: ${0};"),
    ("mask-mode", "mask-mode: ${0};"),
    ("mask-origin", "mask-origin: ${0};"),
    ("mask-position", "mask-position: ${0};"),
    ("mask-repeat", "mask-repeat: ${0};"),
    ("mask-size", "mask-size: ${0};"),
    ("mask-type", "mask-type: ${0};"),
    ("max-height", "max-height: ${0};"),
    ("max-lines", "max-lines: ${0};"),
    ("max-width", "max-width: ${0};"),
    ("max-zoom", "max-zoom: ${0};"),
    ("min-height", "min-height: ${0};"),
    ("min-width", "min-width: ${0};"),
    ("min-zoom", "min-zoom: ${0};"),
    ("move-to", "move-to: ${0};"),
    ("nav-down", "nav-down: ${0};"),
    ("nav-index", "nav-index: ${0};"),
    ("nav-left", "nav-left: ${0};"),
    ("nav-right", "nav-right: ${0};"),
    ("nav-up", "nav-up: ${0};"),
    ("negative", "negative: ${0};"),
    ("object-fit", "object-fit: ${0};"),
    ("object-position", "object-position: ${0};"),
    ("offset-after", "offset-after: ${0};"),
    ("offset-before", "offset-before: ${0};"),
    ("offset-end", "offset-end: ${0};"),
    ("offset-start", "offset-start: ${0};"),
    ("opacity", "opacity: ${0};"),
    ("order", "order: ${0};"),
    ("orientation", "orientation: ${0};"),
    ("orphans", "orphans: ${0};"),
    ("outline", "outline: ${0};"),
    ("outline-color", "outline-color: ${0};"),
    ("outline-offset", "outline-offset: ${0};"),
    ("outline-style", "outline-style: ${0};"),
    ("outline-width", "outline-width: ${0};"),
    ("overflow", "overflow: ${0};"),
    ("overflow-style", "overflow-style: ${0};"),
    ("overflow-wrap", "overflow-wrap: ${0};"),
    ("overflow-x", "overflow-x: ${0};"),
    ("overflow-y", "overflow-y: ${0};"),
    ("pad", "pad: ${0};"),
    ("padding", "padding: ${0};"),
    ("padding-bottom", "padding-bottom: ${0};"),
    ("padding-left", "padding-left: ${0};"),
    ("padding-right", "padding-right: ${0};"),
    ("padding-top", "padding-top: ${0};"),
    ("page", "page: ${0};"),
    ("page-break-after", "page-break-after: ${0};"),
    ("page-break-before", "page-break-before: ${0};"),
    ("page-break-inside", "page-break-inside: ${0};"),
    ("page-policy", "page-policy: ${0};"),
    ("pause", "pause: ${0};"),
    ("pause-after", "pause-after: ${0};"),
    ("pause-before", "pause-before: ${0};"),
    ("perspective", "perspective: ${0};"),
    ("perspective-origin", "perspective-origin: ${0};"),
    ("pointer-events", "pointer-events: ${0};"),
    ("position", "position: ${0};"),
    ("prefix", "prefix: ${0};"),
    ("presentation-level", "presentation-level: ${0};"),
    ("quotes", "quotes: ${0};"),
    ("range", "range: ${0};"),
    ("region-fragment", "region-fragment: ${0};"),
    ("resize", "resize: ${0};"),
    ("resolution", "resolution: ${0};"),
    ("rest", "rest: ${0};"),
    ("rest-after", "rest-after: ${0};"),
    ("rest-before", "rest-before: ${0};"),
    ("right", "right: ${0};"),
    ("rotation", "rotation: ${0};"),
    ("rotation-point", "rotation-point: ${0};"),
    ("ruby-align", "ruby-align: ${0};"),
    ("ruby-merge", "ruby-merge: ${0};"),
    ("ruby-position", "ruby-position: ${0};"),
    ("running", "running: ${0};"),
    ("shape-image-threshold", "shape-image-threshold: ${0};"),
    ("shape-margin", "shape-margin: ${0};"),
    ("shape-outside", "shape-outside: ${0};"),
    ("size", "size: ${0};"),
    ("speak", "speak: ${0};"),
    ("speak-as", "speak-as: ${0};"),
    ("src", "src: ${0};"),
    ("string-set", "string-set: ${0};"),
    ("suffix", "suffix: ${0};"),
    ("symbols", "symbols: ${0};"),
    ("system", "system: ${0};"),
    ("tab-size", "tab-size: ${0};"),
    ("table-layout", "table-layout: ${0};"),
    ("target", "target: ${0};"),
    ("target-name", "target-name: ${0};"),
    ("target-new", "target-new: ${0};"),
    ("target-position", "target-position: ${0};"),
    ("text-align", "text-align: ${0};"),
    ("text-align-last", "text-align-last: ${0};"),
    ("text-combine-upright", "text-combine-upright: ${0};"),
    ("text-decoration", "text-decoration: ${0};"),
    ("text-decoration-color", "text-decoration-color: ${0};"),
    ("text-decoration-line", "text-decoration-line: ${0};"),
    ("text-decoration-skip", "text-decoration-skip: ${0};"),
    ("text-decoration-style", "text-decoration-style: ${0};"),
    ("text-emphasis", "text-emphasis: ${0};"),
    ("text-emphasis-color", "text-emphasis-color: ${0};"),
    ("text-emphasis-position", "text-emphasis-position: ${0};"),
    ("text-emphasis-style", "text-emphasis-style: ${0};"),
    ("text-height", "text-height: ${0};"),
    ("text-indent", "text-indent: ${0};"),
    ("text-justify", "text-justify: ${0};"),
    ("text-orientation", "text-orientation: ${0};"),
    ("text-overflow", "text-overflow: ${0};"),
    ("text-shadow", "text-shadow: ${0};"),
    ("text-transform", "text-transform: ${0};"),
    ("text-underline-position", "text-underline-position: ${0};"),
    ("top", "top: ${0};"),
    ("transform", "transform: ${0};"),
    ("transform-origin", "transform-origin: ${0};"),
    ("transform-style", "transform-style: ${0};"),
    ("transition", "transition: ${0};"),
    ("transition-delay", "transition-delay: ${0};"),
    ("transition-duration", "transition-duration: ${0};"),
    ("transition-property", "transition-property: ${0};"),
    ("transition-timing-function", "transition-timing-function: ${0};"),
    ("unicode-bidi", "unicode-bidi: ${0};"),
    ("unicode-range", "unicode-range: ${0};"),
    ("user-zoom", "user-zoom: ${0};"),
    ("vertical-align", "vertical-align: ${0};"),
    ("visibility", "visibility: ${0};"),
    ("voice-balance", "voice-balance: ${0};"),
    ("voice-duration", "voice-duration: ${0};"),
    ("voice-family", "voice-family: ${0};"),
    ("voice-pitch", "voice-pitch: ${0};"),
    ("voice-range", "voice-range: ${0};"),
    ("voice-rate", "voice-rate: ${0};"),
    ("voice-stress", "voice-stress: ${0};"),
    ("voice-volume", "voice-volume: ${0};"),
    ("white-space", "white-space: ${0};"),
    ("widows", "widows: ${0};"),
    ("width", "width: ${0};"),
    ("will-change", "will-change: ${0};"),
    ("word-break", "word-break: ${0};"),
    ("word-spacing", "word-spacing: ${0};"),
    ("word-wrap", "word-wrap: ${0};"),
    ("wrap-flow", "wrap-flow: ${0};"),
    ("wrap-through", "wrap-through: ${0};"),
    ("writing-mode", "writing-mode: ${0};"),
    ("z-index", "z-index: ${0};"),
    ("zoom", "zoom: ${0}; "),
    ("-moz-box-sizing", "-moz-box-sizing: ${0};"),
    ("-moz-column-count", "-moz-column-count: ${0};"),
    ("-moz-column-fill", "-moz-column-fill: ${0};"),
    ("-moz-column-gap", "-moz-column-gap: ${0};"),
    ("-moz-column-rule", "-moz-column-rule: ${0};"),
    ("-moz-column-rule-color", "-moz-column-rule-color: ${0};"),
    ("-moz-column-rule-style", "-moz-column-rule-style: ${0};"),
    ("-moz-column-rule-width", "-moz-column-rule-width: ${0};"),
    ("-moz-column-span", "-moz-column-span: ${0};"),
    ("-moz-column-width", "-moz-column-width: ${0};"),
    ("-moz-columns", "-moz-columns: ${0};"),
    ("-moz-font-feature-settings", "-moz-font-feature-settings: ${0};"),
    ("-moz-font-language-override", "-moz-font-language-override: ${0};"),
    ("-moz-hyphens", "-moz-hyphens: ${0};"),
    ("-moz-text-align-last", "-moz-text-align-last: ${0};"),
    ("-moz-text-decoration-color", "-moz-text-decoration-color: ${0};"),
    ("-moz-text-decoration-line", "-moz-text-decoration-line: ${0};"),
    ("-moz-text-decoration-style", "-moz-text-decoration-style: ${0};"),
    ("-ms-flow-from", "-ms-flow-from: ${0};"),
    ("-ms-flow-into", "-ms-flow-into: ${0};"),
    ("-ms-grid-column", "-ms-grid-column: ${0};"),
    ("-ms-grid-row", "-ms-grid-row: ${0};"),
    ("-ms-hyphens", "-ms-hyphens: ${0};"),
    ("-ms-ime-mode", "-ms-ime-mode: ${0};"),
    ("-ms-overflow-style", "-ms-overflow-style: ${0};"),
    ("-ms-overflow-x", "-ms-overflow-x: ${0};"),
    ("-ms-overflow-y", "-ms-overflow-y: ${0};"),
    ("-ms-text-align-last", "-ms-text-align-last: ${0};"),
    ("-ms-text-justify", "-ms-text-justify: ${0};"),
    ("-ms-transform", "-ms-transform: ${0};"),
    ("-ms-transform-origin", "-ms-transform-origin: ${0};"),
    ("-ms-transform-style", "-ms-transform-style: ${0};"),
    ("-ms-word-wrap", "-ms-word-wrap: ${0};"),
    ("-ms-wrap-flow", "-ms-wrap-flow: ${0};"),
    ("-ms-wrap-through", "-ms-wrap-through: ${0};"),
    ("-ms-writing-mode", "-ms-writing-mode: ${0};"),
    ("-webkit-align-content", "-webkit-align-content: ${0};"),
    ("-webkit-align-items", "-webkit-align-items: ${0};"),
    ("-webkit-align-self", "-webkit-align-self: ${0};"),
    ("-webkit-animation", "-webkit-animation: ${0};"),
    ("-webkit-animation-delay", "-webkit-animation-delay: ${0};"),
    ("-webkit-animation-direction", "-webkit-animation-direction: ${0};"),
    ("-webkit-animation-duration", "-webkit-animation-duration: ${0};"),
    ("-webkit-animation-fill-mode", "-webkit-animation-fill-mode: ${0};"),
    ("-webkit-animation-iteration-count", "-webkit-animation-iteration-count: ${0};"),
    ("-webkit-animation-name", "-webkit-animation-name: ${0};"),
    ("-webkit-animation-play-state", "-webkit-animation-play-state: ${0};"),
    ("-webkit-animation-timing-function", "-webkit-animation-timing-function: ${0};"),
    ("-webkit-backface-visibility", "-webkit-backface-visibility: ${0};"),
    ("-webkit-border-image", "-webkit-border-image: ${0};"),
    ("-webkit-break-after", "-webkit-break-after: ${0};"),
    ("-webkit-break-before", "-webkit-break-before: ${0};"),
    ("-webkit-break-inside", "-webkit-break-inside: ${0};"),
    ("-webkit-column-count", "-webkit-column-count: ${0};"),
    ("-webkit-column-fill", "-webkit-column-fill: ${0};"),
    ("-webkit-column-gap", "-webkit-column-gap: ${0};"),
    ("-webkit-column-rule", "-webkit-column-rule: ${0};"),
    ("-webkit-column-rule-color", "-webkit-column-rule-color: ${0};"),
    ("-webkit-column-rule-style", "-webkit-column-rule-style: ${0};"),
    ("-webkit-column-rule-width", "-webkit-column-rule-width: ${0};"),
    ("-webkit-column-span", "-webkit-column-span: ${0};"),
    ("-webkit-column-width", "-webkit-column-width: ${0};"),
    ("-webkit-columns", "-webkit-columns: ${0};"),
    ("-webkit-flex", "-webkit-flex: ${0};"),
    ("-webkit-flex-basis", "-webkit-flex-basis: ${0};"),
    ("-webkit-flex-direction", "-webkit-flex-direction: ${0};"),
    ("-webkit-flex-flow", "-webkit-flex-flow: ${0};"),
    ("-webkit-flex-grow", "-webkit-flex-grow: ${0};"),
    ("-webkit-flex-shrink", "-webkit-flex-shrink: ${0};"),
    ("-webkit-flex-wrap", "-webkit-flex-wrap: ${0};"),
    ("-webkit-flow-from", "-webkit-flow-from: ${0};"),
    ("-webkit-flow-into", "-webkit-flow-into: ${0};"),
    ("-webkit-font-feature-settings", "-webkit-font-feature-settings: ${0};"),
    ("-webkit-font-kerning", "-webkit-font-kerning: ${0};"),
    ("-webkit-font-variant-ligatures", "-webkit-font-variant-ligatures: ${0};"),
    ("-webkit-grid-column", "-webkit-grid-column: ${0};"),
    ("-webkit-grid-row", "-webkit-grid-row: ${0};"),
    ("-webkit-hyphens", "-webkit-hyphens: ${0};"),
    ("-webkit-justify-content", "-webkit-justify-content: ${0};"),
    ("-webkit-order", "-webkit-order: ${0};"),
    ("-webkit-perspective", "-webkit-perspective: ${0};"),
    ("-webkit-perspective-origin", "-webkit-perspective-origin: ${0};"),
    ("-webkit-region-fragment", "-webkit-region-fragment: ${0};"),
    ("-webkit-transform", "-webkit-transform: ${0};"),
    ("-webkit-transform-origin", "-webkit-transform-origin: ${0};"),
    ("-webkit-transform-style", "-webkit-transform-style: ${0};"),
    ("-webkit-transition", "-webkit-transition: ${0};"),
    ("-webkit-transition-delay", "-webkit-transition-delay: ${0};"),
    ("-webkit-transition-duration", "-webkit-transition-duration: ${0};"),
    ("-webkit-transition-property", "-webkit-transition-property: ${0};"),
    ("-webkit-transition-timing-function", "-webkit-transition-timing-function: ${0};")
]

auto = ("auto",)
calc = ("calc()", "calc(${1:expression})")
content = ("content()", "content(${1})")
counter = ("counter()", "counter(${1:<identifier>}${2:, ${3:<list-style-type>}})")
counters = ("counters()", "counters(${1:<identifier>}, \"${2:<string>}\"${3:, ${4:<list-style-type>}})")
decibel = ("<decibel>", "${1:0}dB")
flex = ("<flex>", "${1:0}fr")
ident = ("<ident>", "${1:<ident>}")
integer = ("<integer>", "${1:<integer>}")
length = ("<length>", "${1:<length>}")
matrix = ("matrix()", "matrix(${1:0}, ${2:0}, ${3:0}, ${4:0}, ${5:0}, ${6:0})")
matrix3d = ("matrix3d()", "matrix3d(${1:0}, ${2:0}, ${3:0}, ${4:0}, ${5:0}, ${6:0}, ${7:0}, ${8:0}, ${9:0}, ${10:0}, ${11:0}, ${12:0}, ${13:0}, ${14:0}, ${15:0}, ${16:0})")
minmax = ("minmax()", "minmax(${1:<track-breadth>}, ${2:<track-breadth>})")
none = ("none",)
number = ("<number>", "${1:<number>}")
percentage = ("<percentage>", "${1:0}%")
perspective = ("perspective()", "perspective(${1:<length>})")
repeat = ("repeat()", "repeat(${1})")
rotate = ("rotate()", "rotate(${1:<angle>})")
rotate3d = ("rotate3d()", "rotate3d(${1:0}, ${2:0}, ${3:0}, ${4:<angle>})")
rotateX = ("rotateX()", "rotateX(${1:<angle>})")
rotateY = ("rotateY()", "rotateY(${1:<angle>})")
rotateZ = ("rotateZ()", "rotateZ(${1:<angle>})")
scale = ("scale()", "scale(${1:0}${2:, ${3:0}})")
scale3d = ("scale3d()", "scale3d(${1:0}, ${2:0}, ${3:0})")
scaleX = ("scaleX()", "scaleX(${1:0})")
scaleY = ("scaleY()", "scaleY(${1:0})")
scaleZ = ("scaleZ()", "scaleZ(${1:0})")
skew = ("skew()", "skew(${1:<angle>}${2:, ${3:<angle>}})")
skewX = ("skewX()", "skewX(${1:<angle>})")
skewY = ("skewY()", "skewY(${1:<angle>})")
string = ("<string>", "\"${1}\"")
time = ("<time>", "${1:<time>}")
url = ("url()", "url(${1})")
align_content = [("center",), ("flex-end",), ("flex-start",), ("space-around",), ("space-between",), ("stretch",)]
align_items = [("baseline",), ("center",), ("flex-end",), ("flex-start",), ("stretch",)]
align_self = [auto, ("baseline",), ("center",), ("flex-end",), ("flex-start",), ("stretch",)]
all_values = [("inherit",), ("initial",), ("unset",), ("attr()", "attr(${1:attribute-name})"), ("toggle()", "toggle(${1})"), ("var()", "var(--${1:custom-name}, ${2:value})") ]
single_transition_timing_function = [
    ("cubic-bezier()", "cubic-bezier(${1:0}, ${2:0}, ${3:0}, ${4:0})"),
    ("ease",),
    ("ease-in",),
    ("ease-in-out",),
    ("ease-out",),
    ("linear",),
    ("step-end",),
    ("step-start",),
    ("steps()", "steps(${1})")
]
animation_direction = [("alternate",), ("alternate-reverse",), ("normal",), ("reverse",)]
animation_fill_mode = [("backwards",), ("both",), ("forwards",), none]
animation_delay = [calc, time]
animation_duration = animation_delay
animation_iteration_count = [calc, ("infinite",), number]
animation_name = [ident, none]
animation_play_state = [("paused",), ("running",)]
animation = sorted([time, calc] + animation_direction + animation_fill_mode + animation_iteration_count + [ident] + animation_play_state + single_transition_timing_function)
backface_visibility = [("hidden",), ("visible",)]
image = [
    ("conic-gradient()", "conic-gradient(${1})"),
    ("cross-fade()", "cross-fade(${1})"),
    ("element()", "element(#${1})"),
    ("filter()", "filter(${1})"),
    ("image()", "image(${1})"),
    ("image-set()", "image-set(${1})"),
    ("linear-gradient()", "linear-gradient(${1})"),
    ("radial-gradient()", "radial-gradient(${1})"),
    ("repeating-conic-gradient()", "repeating-conic-gradient(${1})"),
    ("repeating-linear-gradient()", "repeating-linear-gradient(${1})"),
    ("repeating-radial-gradient()", "repeating-radial-gradient(${1})"),
    url
]
color = [
    ("aliceblue",),
    ("antiquewhite",),
    ("aqua",),
    ("aquamarine",),
    ("azure",),
    ("beige",),
    ("bisque",),
    ("black",),
    ("blanchedalmond",),
    ("blue",),
    ("blueviolet",),
    ("brown",),
    ("burlywood",),
    ("cadetblue",),
    ("chartreuse",),
    ("chocolate",),
    ("coral",),
    ("cornflowerblue",),
    ("cornsilk",),
    ("crimson",),
    ("currentColor",),
    ("cyan",),
    ("darkblue",),
    ("darkcyan",),
    ("darkgoldenrod",),
    ("darkgray",),
    ("darkgreen",),
    ("darkgrey",),
    ("darkkhaki",),
    ("darkmagenta",),
    ("darkolivegreen",),
    ("darkorange",),
    ("darkorchid",),
    ("darkred",),
    ("darksalmon",),
    ("darkseagreen",),
    ("darkslateblue",),
    ("darkslategray",),
    ("darkslategrey",),
    ("darkturquoise",),
    ("darkviolet",),
    ("deeppink",),
    ("deepskyblue",),
    ("dimgray",),
    ("dimgrey",),
    ("dodgerblue",),
    ("firebrick",),
    ("floralwhite",),
    ("forestgreen",),
    ("fuchsia",),
    ("gainsboro",),
    ("ghostwhite",),
    ("gold",),
    ("goldenrod",),
    ("gray",),
    ("green",),
    ("greenyellow",),
    ("grey",),
    ("honeydew",),
    ("hotpink",),
    ("hsl()", "hsl(${1:0}, ${2:0}%, ${3:0}%)"),
    ("hsla()", "hsla(${1:0}, ${2:0}%, ${3:0}%, ${4:0.0})"),
    ("indianred",),
    ("indigo",),
    ("ivory",),
    ("khaki",),
    ("lavender",),
    ("lavenderblush",),
    ("lawngreen",),
    ("lemonchiffon",),
    ("lightblue",),
    ("lightcoral",),
    ("lightcyan",),
    ("lightgoldenrodyellow",),
    ("lightgray",),
    ("lightgreen",),
    ("lightgrey",),
    ("lightpink",),
    ("lightsalmon",),
    ("lightseagreen",),
    ("lightskyblue",),
    ("lightslategray",),
    ("lightslategrey",),
    ("lightsteelblue",),
    ("lightyellow",),
    ("lime",),
    ("limegreen",),
    ("linen",),
    ("magenta",),
    ("maroon",),
    ("mediumaquamarine",),
    ("mediumblue",),
    ("mediumorchid",),
    ("mediumpurple",),
    ("mediumseagreen",),
    ("mediumslateblue",),
    ("mediumspringgreen",),
    ("mediumturquoise",),
    ("mediumvioletred",),
    ("midnightblue",),
    ("mintcream",),
    ("mistyrose",),
    ("moccasin",),
    ("navajowhite",),
    ("navy",),
    ("oldlace",),
    ("olive",),
    ("olivedrab",),
    ("orange",),
    ("orangered",),
    ("orchid",),
    ("palegoldenrod",),
    ("palegreen",),
    ("paleturquoise",),
    ("palevioletred",),
    ("papayawhip",),
    ("peachpuff",),
    ("peru",),
    ("pink",),
    ("plum",),
    ("powderblue",),
    ("purple",),
    ("rebeccapurple",),
    ("red",),
    ("rgb()", "rgb(${1:0}, ${2:0}, ${3:0})"),
    ("rgba()", "rgba(${1:0}, ${2:0}, ${3:0}, ${4:0.0})"),
    ("rosybrown",),
    ("royalblue",),
    ("saddlebrown",),
    ("salmon",),
    ("sandybrown",),
    ("seagreen",),
    ("seashell",),
    ("sienna",),
    ("silver",),
    ("skyblue",),
    ("slateblue",),
    ("slategray",),
    ("slategrey",),
    ("snow",),
    ("springgreen",),
    ("steelblue",),
    ("tan",),
    ("teal",),
    ("thistle",),
    ("tomato",),
    ("transparent",),
    ("turquoise",),
    ("violet",),
    ("wheat",),
    ("white",),
    ("whitesmoke",),
    ("yellow",),
    ("yellowgreen",),
]
counter_set = [calc, ident, integer, none]
cue = [decibel, none, url]
line_style = [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), none, ("outset",), ("ridge",), ("solid",),]
line_width = [calc, length, ("medium",), ("thick",), ("thin", )]
background_attachment = [("fixed",), ("local",), ("scroll",)]
background_clip = [("border-box",), ("content-box",), ("padding-box",)]
background_image = sorted([none] + image)
background_repeat = [("no-repeat",), ("repeat",), ("repeat-x",), ("repeat-y",), ("round",), ("space",)]
background_size = [auto, ("contain",), ("cover",), length, percentage]
border = sorted(color + line_style + line_width)
border_clip = [calc, ("<fraction>", "${1:1}/${2:1}"), length, ("normal",), percentage]
border_image_outset = [calc, length, number]
border_image_repeat = [("repeat",), ("round",), ("space",), ("stretch",)]
border_image_slice = [calc, ("fill",), number, percentage]
border_image_source = sorted([none] + image)
border_image_width = [auto, calc, length, number, percentage]
border_image = sorted([auto, calc, length, none, number, percentage] + border_image_repeat + image)
border_radius = [calc, length, percentage]
box_offset = [auto, length, percentage]
box_sizing = [("border-box",), ("content-box",), ("padding-box",)]
break_after = [("always",), ("any",), auto, ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",), ("column",), ("left",), ("page",), ("recto",), ("region",), ("right",), ("verso",)]
break_before = break_after
break_inside = [auto, ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",)]
color_interpolation = [auto, ("linearRGB",), ("sRGB",)]
columns = [auto, calc, integer, length, ("medium",), ("thick",), ("thin",)]
column_count = [auto, calc, integer]
column_fill = [auto, ("balance",)]
column_gap = [calc, length, ("normal",)]
# Sorting is necessary because the list of colors is mixed in.
column_rule = sorted([calc, length, ("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), none, ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",)] + color)
column_rule_style = [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), none, ("outset",), ("ridge",), ("solid",)]
column_rule_width = [calc, length, ("medium",), ("thick",), ("thin",)]
column_span = [("all",), none]
column_width = [auto, calc, length]
corner_shape = [("bevel",), ("notch",), ("round",), ("scoop",)]
flex_basis = [auto, calc, length, ("main-size",), percentage]
flex_property = sorted([calc, none, number] + flex_basis)
flex_direction = [("column",), ("column-reverse",), ("row",), ("row-reverse",)]
flex_wrap = [("nowrap",), ("wrap",), ("wrap-reverse",)]
flex_flow = sorted(flex_direction + flex_wrap)
flex_grow = [calc, number]
flex_shrink = flex_grow
flow_from = [("content",), ("element",), ident, none]
flow_into = [ident, none]
font_feature_settings = [calc, integer, ("off",), ("on",), ("normal",), ("<string>", '"${1:aaaa}"')]
font_kerning = [auto, none, ("normal",)]
font_language_override = [("normal",), ("<string>", '"${1:aaa}"')]
font_variant_ligatures = [("common-ligatures",), ("contextual",), ("discretionary-ligatures",), ("historical-ligatures",), ("no-common-ligatures",), ("no-contextual",), ("no-discretionary-ligatures",), ("no-historical-ligatures",), none, ("normal",)]
grid_column = [auto, calc, ident, integer, ("span",)]
grid_row = grid_column
subgrid = ("subgrid", "subgrid ${1:<line-name-list>}")
grid_template_columns = [auto, calc, flex, ident, length, ("max-content",), ("min-content",), minmax, percentage, subgrid]
grid_template_rows = grid_template_columns
hyphens = [auto, ("manual",), none]
ime_mode = [("active",), auto, ("disabled",), ("inactive",), ("inherit",), ("normal",)]
justify_content = [("center",), ("flex-end",), ("flex-start",), ("space-around",), ("space-between",)]
line_stacking_ruby = [("exclude-ruby",), ("include-ruby",)]
line_stacking_shift = [("consider-shifts",), ("disregard-shifts",)]
line_stacking_strategy = [("block-line-height",), ("grid-height",), ("inline-line-height",), ("max-height",)]
order = [calc, integer]
overflow_style = [auto, ("marquee-block",), ("marquee-line",)]
overflow_x = [auto, ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)]
overflow_y = overflow_x
perspective_property = [calc, length, none]
position = [("bottom",), calc, ("center",), ("left",), length, percentage, ("right",), ("top",)]
perspective_origin = position
region_fragment = [auto, ("break",)]
shadow = sorted([calc, ("inset",), length] + color)
text_align_last = [auto, ("center",), ("end",), ("justify",), ("left",), ("right",), ("start",)]
text_justify = [auto, ("distribute",), ("inter-word",), none]
text_decoration_line = [("line-through blink",), none, ("overline",), ("underline",)]
text_decoration_style = [("dashed",), ("dotted",), ("double",), ("solid",), ("wavy",)]
translate   = ("translate()", "translate(${1:<length>}${2:, ${3:<length>}})")
translate3d = ("translate3d()", "translate3d(${1:<length>}, ${2:<length>}, ${3:<length>})")
translateX  = ("translateX()", "translateX(${1:<length>})")
translateY  = ("translateY()", "translateY(${1:<length>})")
translateZ  = ("translateZ()", "translateX(${1:<length>})")
transform = [matrix, matrix3d, perspective, rotate, rotate3d, rotateX, rotateY, rotateZ, scale, scale3d, scaleX, scaleY, scaleZ, skew, skewX, skewY, translate, translate3d, translateX, translateY, translateZ]
transform_origin = perspective_origin
transform_style = [("flat",), ("preserve-3d",)]
transition_property = [("all",), ident, none]
transition = sorted(animation_delay + single_transition_timing_function + transition_property)
word_wrap = [("break-word",), ("normal",)]
wrap_flow = [auto, ("both",), ("clear",), ("end",), ("maximum",), ("minimum",), ("start",)]
wrap_through = [none, ("wrap",)]
writing_mode = [("horizontal-tb",), ("vertical-lr",), ("vertical-rl",)]


property_values = {
    "-moz-box-sizing": box_sizing,
    "-moz-column-count": column_count,
    "-moz-column-fill": column_fill,
    "-moz-column-gap": column_gap,
    "-moz-column-rule": column_rule,
    "-moz-column-rule-color": color,
    "-moz-column-rule-style": column_rule_style,    # TODO: can this be replaced by column width?
    "-moz-column-rule-width": column_rule_width,    # TODO: can this be replaced by column width?
    "-moz-column-span": column_span,
    "-moz-column-width": column_width,
    "-moz-columns": columns,
    "-moz-font-feature-settings": font_feature_settings,
    "-moz-font-language-override": font_language_override,
    "-moz-hyphens": hyphens,
    "-moz-text-align-last": text_align_last,
    "-moz-text-decoration-color": color,
    "-moz-text-decoration-line": text_decoration_line,
    "-moz-text-decoration-style": text_decoration_style,
    "-ms-flow-from": flow_from,
    "-ms-flow-into": flow_into,
    "-ms-grid-column": grid_column,
    "-ms-grid-row": grid_row,
    "-ms-hyphens": hyphens,
    "-ms-ime-mode": ime_mode,
    "-ms-overflow-style": overflow_style,
    "-ms-overflow-x": overflow_x,
    "-ms-overflow-y": overflow_y,
    "-ms-text-align-last": text_align_last,
    "-ms-text-justify": text_justify,
    "-ms-transform": transform,
    "-ms-transform-origin": transform_origin,
    "-ms-transform-style": transform_style,
    "-ms-word-wrap": word_wrap,
    "-ms-wrap-flow": wrap_flow,
    "-ms-wrap-through": wrap_through,
    "-ms-writing-mode": writing_mode,
    "-webkit-align-content": align_content,
    "-webkit-align-items": align_items,
    "-webkit-align-self": align_self,
    "-webkit-animation": animation,
    "-webkit-animation-delay": animation_delay,
    "-webkit-animation-direction": animation_direction,
    "-webkit-animation-duration": animation_duration,
    "-webkit-animation-fill-mode": animation_fill_mode,
    "-webkit-animation-iteration-count": animation_iteration_count,
    "-webkit-animation-name": animation_name,
    "-webkit-animation-play-state": animation_play_state,
    "-webkit-animation-timing-function": single_transition_timing_function,
    "-webkit-backface-visibility": backface_visibility,
    "-webkit-border-image": border_image,
    "-webkit-break-after": break_after,
    "-webkit-break-before": break_before,
    "-webkit-break-inside": break_inside,
    "-webkit-column-count": column_count,
    "-webkit-column-fill": column_fill,
    "-webkit-column-gap": column_gap,
    "-webkit-column-rule": column_rule,
    "-webkit-column-rule-color": color,
    "-webkit-column-rule-style": column_rule_style, # TODO: can this be replaced by border_width?
    "-webkit-column-rule-width": column_rule_width, # TODO: can this be replaced by column width?
    "-webkit-column-span": column_span,
    "-webkit-column-width": column_width,
    "-webkit-columns": columns,
    "-webkit-flex": flex_property,
    "-webkit-flex-basis": flex_basis,
    "-webkit-flex-direction": flex_direction,
    "-webkit-flex-flow": flex_flow,
    "-webkit-flex-grow": flex_grow,
    "-webkit-flex-shrink": flex_shrink,
    "-webkit-flex-wrap": flex_wrap,
    "-webkit-flow-from": flow_from,
    "-webkit-flow-into": flow_into,
    "-webkit-font-feature-settings": font_feature_settings,
    "-webkit-font-kerning": font_kerning,
    "-webkit-font-variant-ligatures": font_variant_ligatures,
    "-webkit-grid-column": grid_column,
    "-webkit-grid-row": grid_row,
    "-webkit-hyphens": hyphens,
    "-webkit-justify-content": justify_content,
    "-webkit-order": order,
    "-webkit-perspective": perspective_property,
    "-webkit-perspective-origin": perspective_origin,
    "-webkit-region-fragment": region_fragment,
    "-webkit-transform": transform,
    "-webkit-transform-origin": transform_origin,
    "-webkit-transform-style": transform_style,
    "-webkit-transition": transition,
    "-webkit-transition-delay": animation_delay,
    "-webkit-transition-duration": animation_duration,
    "-webkit-transition-property": transition_property,
    "-webkit-transition-timing-function": single_transition_timing_function,
    "additive-symbols": sorted(image + [calc, ident, integer, string]),
    "align-content": align_content,
    "align-items": align_items,
    "align-self": align_self,
    "alignment": [("bottom",), ("center",), ("left",), ("right",), ("top",)],
    "alignment-adjust": [("alphabetic",), auto, ("baseline",), calc, ("central",), ("hanging",), ("ideographic",), length, ("mathematical",), ("middle",), ("over-edge",), percentage, ("text-over-edge",), ("text-under-edge",), ("under-edge",)],
    "alignment-baseline": [("alphabetic",), ("baseline",), ("central",), ("hanging",), ("ideographic",), ("mathematical",), ("middle",), ("over-edge",), ("text-over-edge",), ("text-under-edge",), ("under-edge",), ("use-script",)],
    "all": all_values,
    "animation": animation,
    "animation-delay": animation_delay,
    "animation-direction": animation_direction,
    "animation-duration": animation_duration,
    "animation-fill-mode": animation_fill_mode,
    "animation-iteration-count": animation_iteration_count,
    "animation-name": animation_name,
    "animation-play-state": animation_play_state,
    "animation-timing-function": single_transition_timing_function,
    "backface-visibility": backface_visibility,
    "background": sorted(background_image + position + background_size + background_repeat + background_attachment + background_clip + color),
    "background-attachment": background_attachment,
    "background-clip": background_clip,
    "background-color": color,
    "background-image": background_image,
    "background-origin": background_clip,
    "background-position": position,
    "background-repeat": background_repeat,
    "background-size": background_size,
    "baseline-shift": [("baseline",), length, percentage, ("sub",), ("super",)],
    "bleed": [auto, calc, length],
    "bookmark-label": [calc, integer, none],
    "bookmark-level": [content, counter, counters, ("<string>", "\"${1:<string>}\"")],
    "bookmark-state": [("closed",), ("open",)],
    "border": border,
    "border-bottom": border,
    "border-bottom-color": color,
    "border-bottom-left-radius": border_radius,
    "border-bottom-right-radius": border_radius,
    "border-bottom-style": line_style,
    "border-bottom-width": line_width,
    "border-clip": border_clip,
    "border-clip-bottom": border_clip,
    "border-clip-left": border_clip,
    "border-clip-right": border_clip,
    "border-clip-top": border_clip,
    "border-collapse": [("collapse",), ("separate",)],
    "border-color": color,
    "border-image": border_image,
    "border-image-outset": border_image_outset,
    "border-image-repeat": border_image_repeat,
    "border-image-slice": border_image_slice,
    "border-image-source": border_image_source,
    "border-image-width": border_image_width,
    "border-left": border,
    "border-left-color": color,
    "border-left-style": line_style,
    "border-left-width": line_width,
    "border-limit": [("all",), ("bottom",), calc, ("corners",), ("left",), length, percentage, ("right",), ("sides",), ("top",)],
    "border-radius": border_radius,
    "border-right": border,
    "border-right-color": color,
    "border-right-style": line_style,
    "border-right-width": line_width,
    "border-spacing": [calc, length],
    "border-style": line_style,
    "border-top": border,
    "border-top-color": color,
    "border-top-left-radius": border_radius,
    "border-top-right-radius": border_radius,
    "border-top-style": line_style,
    "border-top-width": line_width,
    "border-width": line_width,
    "bottom": box_offset,
    "box-decoration-break": [("clone",), ("slice",)],
    "box-shadow": shadow,
    "box-sizing": box_sizing,
    "box-snap": [("after",), ("before",), ("center",), ("first-baseline",), ("last-baseline",), none],
    "break-after": break_after,
    "break-before": break_before,
    "break-inside": break_inside,
    "caption-side": [("bottom",), ("top",)],
    "chains": [ident, none],
    "child-align": [auto, ("bottom",), ("left",), ("middle",), ("right",), ("top",)],
    "clear": [("both",), ("left",), none, ("right",)],
    "clear-after": [("both",), ("bottom",), ("descendants",), ("end",), ("inside",), ("left",), none, ("outside",), ("right",), ("start",), ("top",)],
    "clear-side": [auto, ("both",)],
    "clip-path": [("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("padding-box",), ("stroke-box",), url, ("view-box",)],
    "clip-rule": [("evenodd",), ("nonzero",)],
    "color": color,
    "color-correction": [auto, ("sRGB",)],
    "color-interpolation": color_interpolation,
    "color-interpolation-filters": color_interpolation,
    "column-count": column_count,
    "column-fill": column_fill,
    "column-gap": column_gap,
    "column-rule": column_rule,
    "column-rule-color": color,
    "column-rule-style": column_rule_style,     # TODO: can this be replaced by border_width?
    "column-rule-width": column_rule_width,     # TODO: can this be replaced by border_width?
    "column-span": column_span,
    "column-width": column_width,
    "columns": [auto, calc, integer, length],
    "content": [],                              # TODO: write this when spec is finished
    "corner-shape": corner_shape,
    "corners": sorted(border_radius + corner_shape),
    "counter-increment": counter_set,
    "counter-reset": counter_set,
    "counter-set": counter_set,
    "cue": cue,
    "cue-after": cue,
    "cue-before": cue,
    "cursor": [("alias",), ("all-scroll",), ("auto",), ("cell",), ("col-resize",), ("context-menu",), ("copy",), ("crosshair",), ("default",), ("e-resize",), ("ew-resize",), ("help",), ("move",), ("n-resize",), ("ne-resize",), ("nesw-resize",), ("no-drop",), ("none",), ("not-allowed",), ("ns-resize",), number, ("nw-resize",), ("nwse-resize",), ("pointer",), ("progress",), ("row-resize",), ("s-resize",), ("se-resize",), ("sw-resize",), ("text",), url, ("vertical-text",), ("w-resize",), ("wait",), ("zoom-in",), ("zoom-out",)],
    "direction": [],
    "display": [],
    "display-box": [],
    "display-extras": [],
    "display-inside": [],
    "display-outside": [],
    "dominant-baseline": [("alphabetic",), auto, ("central",), ("hanging",), ("ideographic",), ("mathematical",), ("middle",), ("no-change",), ("reset-size",), ("text-over-edge",), ("text-under-edge",), ("use-script",)],
    "empty-cells": [],
    "fallback": [],
    "filter": [],
    "flex": flex_property,
    "flex-basis": flex_basis,
    "flex-direction": flex_direction,
    "flex-flow": flex_flow,
    "flex-grow": [calc, number],
    "flex-shrink": [calc, number],
    "flex-wrap": flex_wrap,
    "float": [],
    "float-defer-column": [],
    "float-defer-page": [],
    "float-displace": [],
    "float-offset": [],
    "float-wrap": [],
    "flood-color": [],
    "flood-opacity": [],
    "flow": [],
    "flow-from": flow_from,
    "flow-into": flow_into,
    "font": [],
    "font-family": [],
    "font-feature-settings": font_feature_settings,
    "font-kerning": [],
    "font-language-override": font_language_override,
    "font-size": [],
    "font-size-adjust": [],
    "font-stretch": [],
    "font-style": [],
    "font-synthesis": [],
    "font-variant": [],
    "font-variant-alternates": [],
    "font-variant-caps": [],
    "font-variant-east-asian": [],
    "font-variant-ligatures": font_variant_ligatures,
    "font-variant-numeric": [],
    "font-variant-position": [],
    "font-weight": [],
    "footnote-display": [],
    "footnote-policy": [],
    "grid": [],
    "grid-area": [],
    "grid-auto-columns": [],
    "grid-auto-flow": [],
    "grid-auto-rows": [],
    "grid-column": grid_column,
    "grid-column-end": [],
    "grid-column-start": [],
    "grid-row": grid_row,
    "grid-row-end": [],
    "grid-row-start": [],
    "grid-template": [],
    "grid-template-areas": [],
    "grid-template-columns": grid_template_columns,
    "grid-template-rows": grid_template_rows,
    "hanging-punctuation": [],
    "height": [],
    "hyphens": hyphens,
    "icon": [],
    "image-orientation": [],
    "image-rendering": [],
    "image-resolution": [],
    "ime-mode": ime_mode,
    "indent-edge-reset": [],
    "initial-letters": [calc, integer],
    "inline-box-align": [calc, integer, ("last",)],
    "justify-content": justify_content,
    "justify-items": [],
    "justify-self": [],
    "left": box_offset,
    "letter-spacing": [],
    "lighting-color": [],
    "line-box-contain": [("block",), ("font",), ("glyphs",), ("inline",), ("inline-box",), none, ("replaced",)],
    "line-break": [],
    "line-grid": [],
    "line-height": [calc, length, none, ("normal",), number, percentage],
    "line-slack": [],
    "line-snap": [],
    "line-stacking": sorted(line_stacking_ruby + line_stacking_shift + line_stacking_strategy),
    "line-stacking-ruby": line_stacking_ruby,
    "line-stacking-shift": line_stacking_shift,
    "line-stacking-strategy": line_stacking_strategy,
    "list-style": [],
    "list-style-image": [],
    "list-style-position": [],
    "list-style-type": [],
    "margin": [],
    "margin-bottom": [],
    "margin-left": [],
    "margin-right": [],
    "margin-top": [],
    "marker-side": [],
    "marks": [],
    "marquee-direction": [],
    "marquee-play-count": [],
    "marquee-speed": [],
    "marquee-style": [],
    "mask": [],
    "mask-border": [],
    "mask-border-outset": [],
    "mask-border-repeat": [],
    "mask-border-slice": [],
    "mask-border-source": [],
    "mask-border-width": [],
    "mask-clip": [],
    "mask-composite": [],
    "mask-image": [],
    "mask-mode": [],
    "mask-origin": [],
    "mask-position": [],
    "mask-repeat": [],
    "mask-size": [],
    "mask-type": [],
    "max-height": [],
    "max-lines": [],
    "max-width": [],
    "max-zoom": [],
    "min-height": [],
    "min-width": [],
    "min-zoom": [],
    "move-to": [],
    "nav-down": [],
    "nav-index": [],
    "nav-left": [],
    "nav-right": [],
    "nav-up": [],
    "negative": [],
    "object-fit": [],
    "object-position": [],
    "offset-after": [],
    "offset-before": [],
    "offset-end": [],
    "offset-start": [],
    "opacity": [],
    "order": order,
    "orientation": [],
    "orphans": [],
    "outline": [],
    "outline-color": [],
    "outline-offset": [],
    "outline-style": [],
    "outline-width": [],
    "overflow": [],
    "overflow-style": overflow_style,
    "overflow-wrap": word_wrap,
    "overflow-x": overflow_x,
    "overflow-y": overflow_y,
    "pad": [],
    "padding": [],
    "padding-bottom": [],
    "padding-left": [],
    "padding-right": [],
    "padding-top": [],
    "page": [],
    "page-break-after": [],
    "page-break-before": [],
    "page-break-inside": [],
    "page-policy": [],
    "pause": [],
    "pause-after": [],
    "pause-before": [],
    "perspective": perspective_property,
    "perspective-origin": perspective_origin,
    "pointer-events": [],
    "position": [],
    "prefix": [],
    "presentation-level": [],
    "quotes": [],
    "range": [],
    "region-fragment": region_fragment,
    "resize": [],
    "resolution": [],
    "rest": [],
    "rest-after": [],
    "rest-before": [],
    "right": box_offset,
    "rotation": [],
    "rotation-point": [],
    "ruby-align": [],
    "ruby-merge": [],
    "ruby-position": [],
    "running": [],
    "shape-image-threshold": [],
    "shape-margin": [],
    "shape-outside": [],
    "size": [],
    "speak": [],
    "speak-as": [],
    "src": [],
    "string-set": [],
    "suffix": [],
    "symbols": [],
    "system": [],
    "tab-size": [],
    "table-layout": [],
    "target": [],
    "target-name": [],
    "target-new": [],
    "target-position": [],
    "text-align": [],
    "text-align-last": text_align_last,
    "text-combine-upright": [],
    "text-decoration": [],
    "text-decoration-color": color,
    "text-decoration-line": text_decoration_line,
    "text-decoration-skip": [],
    "text-decoration-style": text_decoration_style,
    "text-emphasis": [],
    "text-emphasis-color": [],
    "text-emphasis-position": [],
    "text-emphasis-style": [],
    "text-height": [auto, calc, ("font-size",), ("max-size",), number, ("text-size",)],
    "text-indent": [],
    "text-justify": text_justify,
    "text-orientation": [],
    "text-overflow": [],
    "text-shadow": [],
    "text-transform": [],
    "text-underline-position": [],
    "top": box_offset,
    "transform": transform,
    "transform-origin": transform_origin,
    "transform-style": transform_style,
    "transition": transition,
    "transition-delay": animation_delay,
    "transition-duration": animation_duration,
    "transition-property": transition_property,
    "transition-timing-function": single_transition_timing_function,
    "unicode-bidi": [],
    "unicode-range": [],
    "user-zoom": [],
    "vertical-align": [auto, ("baseline",), ("bottom",), ("bottom",), calc, ("central",), length, percentage, ("middle",), ("sub",), ("super",), ("text-bottom",), ("text-top",), ("top",), ("top",)],
    "visibility": [],
    "voice-balance": [],
    "voice-duration": [],
    "voice-family": [],
    "voice-pitch": [],
    "voice-range": [],
    "voice-rate": [],
    "voice-stress": [],
    "voice-volume": [],
    "white-space": [],
    "widows": [],
    "width": [],
    "will-change": [],
    "word-break": [],
    "word-spacing": [],
    "word-wrap": word_wrap,
    "wrap-flow": wrap_flow,
    "wrap-through": wrap_through,
    "writing-mode": writing_mode,
    "z-index": [],
    "zoom": []

}

# TODO
#   break properties and values into different files and import them
#   add completions for the scopes inside of functions
