from CSS3.completions import types as t
import sublime

# PROPERTIES
names = [
    ("align-content", "align-content: ${1};"),
    ("align-items", "align-items: ${1};"),
    ("align-self", "align-self: ${1};"),
    ("alignment-baseline", "alignment-baseline: ${1};"),
    ("all", "all: ${1};"),
    ("animation", "animation: ${1};"),
    ("animation-composition", "animation-composition: ${1};"),
    ("animation-delay", "animation-delay: ${1};"),
    ("animation-direction", "animation-direction: ${1};"),
    ("animation-duration", "animation-duration: ${1};"),
    ("animation-fill-mode", "animation-fill-mode: ${1};"),
    ("animation-iteration-count", "animation-iteration-count: ${1};"),
    ("animation-name", "animation-name: ${1};"),
    ("animation-play-state", "animation-play-state: ${1};"),
    ("animation-timing-function", "animation-timing-function: ${1};"),
    ("appearance", "appearance: ${1};"),
    ("backface-visibility", "backface-visibility: ${1};"),
    ("background", "background: ${1};"),
    ("background-attachment", "background-attachment: ${1};"),
    ("background-blend-mode", "background-blend-mode: ${1};"),
    ("background-clip", "background-clip: ${1};"),
    ("background-color", "background-color: ${1};"),
    ("background-image", "background-image: ${1};"),
    ("background-image-transform", "background-image-transform: ${1};"),
    ("background-origin", "background-origin: ${1};"),
    ("background-position", "background-position: ${1};"),
    ("background-repeat", "background-repeat: ${1};"),
    ("background-size", "background-size: ${1};"),
    ("baseline-shift", "baseline-shift: ${1};"),
    ("bleed", "bleed: ${1};"),
    ("block-size", "block-size: ${1};"),
    ("block-step", "block-step: ${1};"),
    ("block-step-align", "block-step-align: ${1};"),
    ("block-step-insert", "block-step-insert: ${1};"),
    ("block-step-round", "block-step-round: ${1};"),
    ("block-step-size", "block-step-size: ${1};"),
    ("bookmark-label", "bookmark-label: ${1};"),
    ("bookmark-level", "bookmark-level: ${1};"),
    ("bookmark-state", "bookmark-state: ${1};"),
    ("border", "border: ${1};"),
    ("border-block", "border-block: ${1};"),
    ("border-block-color", "border-block-color: ${1};"),
    ("border-block-end", "border-block-end: ${1};"),
    ("border-block-end-color", "border-block-end-color: ${1};"),
    ("border-block-end-style", "border-block-end-style: ${1};"),
    ("border-block-end-width", "border-block-end-width: ${1};"),
    ("border-block-start", "border-block-start: ${1};"),
    ("border-block-start-color", "border-block-start-color: ${1};"),
    ("border-block-start-style", "border-block-start-style: ${1};"),
    ("border-block-start-width", "border-block-start-width: ${1};"),
    ("border-block-style", "border-block-style: ${1};"),
    ("border-block-width", "border-block-width: ${1};"),
    ("border-bottom", "border-bottom: ${1};"),
    ("border-bottom-color", "border-bottom-color: ${1};"),
    ("border-bottom-leftradius", "border-bottom-leftradius: ${1};"),
    ("border-bottom-right-radius", "border-bottom-right-radius: ${1};"),
    ("border-bottom-style", "border-bottom-style: ${1};"),
    ("border-bottom-width", "border-bottom-width: ${1};"),
    ("border-boundary", "border-boundary: ${1};"),
    ("border-collapse", "border-collapse: ${1};"),
    ("border-color", "border-color: ${1};"),
    ("border-image", "border-image: ${1};"),
    ("border-image-outset", "border-image-outset: ${1};"),
    ("border-image-repeat", "border-image-repeat: ${1};"),
    ("border-image-slice", "border-image-slice: ${1};"),
    ("border-image-source", "border-image-source: ${1};"),
    ("border-image-transform", "border-image-transform: ${1};"),
    ("border-image-width", "border-image-width: ${1};"),
    ("border-inline", "border-inline: ${1};"),
    ("border-inline-color", "border-inline-color: ${1};"),
    ("border-inline-end", "border-inline-end: ${1};"),
    ("border-inline-end-color", "border-inline-end-color: ${1};"),
    ("border-inline-end-style", "border-inline-end-style: ${1};"),
    ("border-inline-end-width", "border-inline-end-width: ${1};"),
    ("border-inline-start", "border-inline-start: ${1};"),
    ("border-inline-start-color", "border-inline-start-color: ${1};"),
    ("border-inline-start-style", "border-inline-start-style: ${1};"),
    ("border-inline-start-width", "border-inline-start-width: ${1};"),
    ("border-inline-style", "border-inline-style: ${1};"),
    ("border-inline-width", "border-inline-width: ${1};"),
    ("border-left", "border-left: ${1};"),
    ("border-left-color", "border-left-color: ${1};"),
    ("border-left-style", "border-left-style: ${1};"),
    ("border-left-width", "border-left-width: ${1};"),
    ("border-radius", "border-radius: ${1};"),
    ("border-right", "border-right: ${1};"),
    ("border-right-color", "border-right-color: ${1};"),
    ("border-right-style", "border-right-style: ${1};"),
    ("border-right-width", "border-right-width: ${1};"),
    ("border-spacing", "border-spacing: ${1};"),
    ("border-style", "border-style: ${1};"),
    ("border-top", "border-top: ${1};"),
    ("border-top-color", "border-top-color: ${1};"),
    ("border-top-left-radius", "border-top-left-radius: ${1};"),
    ("border-top-right-radius", "border-top-right-radius: ${1};"),
    ("border-top-style", "border-top-style: ${1};"),
    ("border-top-width", "border-top-width: ${1};"),
    ("border-width", "border-width: ${1};"),
    ("bottom", "bottom: ${1};"),
    ("box-decoration-break", "box-decoration-break: ${1};"),
    ("box-shadow", "box-shadow: ${1};"),
    ("box-sizing", "box-sizing: ${1};"),
    ("box-snap", "box-snap: ${1};"),
    ("break-after", "break-after: ${1};"),
    ("break-before", "break-before: ${1};"),
    ("break-inside", "break-inside: ${1};"),
    ("caption-side", "caption-side: ${1};"),
    ("caret", "caret: ${1};"),
    ("caret-color", "caret-color: ${1};"),
    ("caret-shape", "caret-shape: ${1};"),
    ("chains", "chains: ${1};"),
    ("clear", "clear: ${1};"),
    ("clip-path", "clip-path: ${1};"),
    ("clip-rule", "clip-rule: ${1};"),
    ("color", "color: ${1};"),
    ("color-adjust", "color-adjust: ${1};"),
    ("color-interpolation-filters", "color-interpolation-filters: ${1};"),
    ("color-rendering", "color-rendering: ${1};"),
    ("column-count", "column-count: ${1};"),
    ("column-fill", "column-fill: ${1};"),
    ("column-gap", "column-gap: ${1};"),
    ("column-rule", "column-rule: ${1};"),
    ("column-rule-color", "column-rule-color: ${1};"),
    ("column-rule-style", "column-rule-style: ${1};"),
    ("column-rule-width", "column-rule-width: ${1};"),
    ("column-span", "column-span: ${1};"),
    ("column-width", "column-width: ${1};"),
    ("columns", "columns: ${1};"),
    ("composes", "composes: ${1};"),
    ("contain", "contain: ${1};"),
    ("content", "content: ${1};"),
    ("continue", "continue: ${1};"),
    ("counter-increment", "counter-increment: ${1};"),
    ("counter-reset", "counter-reset: ${1};"),
    ("counter-set", "counter-set: ${1};"),
    ("cue", "cue: ${1};"),
    ("cue-after", "cue-after: ${1};"),
    ("cue-before", "cue-before: ${1};"),
    ("cursor", "cursor: ${1};"),
    ("direction", "direction: ${1};"),
    ("display", "display: ${1};"),
    ("dominant-baseline", "dominant-baseline: ${1};"),
    ("empty-cells", "empty-cells: ${1};"),
    ("fill", "fill: ${1};"),
    ("fill-break", "fill-break: ${1};"),
    ("fill-color", "fill-color: ${1};"),
    ("fill-image", "fill-image: ${1};"),
    ("fill-opacity", "fill-opacity: ${1};"),
    ("fill-origin", "fill-origin: ${1};"),
    ("fill-position", "fill-position: ${1};"),
    ("fill-repeat", "fill-repeat: ${1};"),
    ("fill-rule", "fill-rule: ${1};"),
    ("fill-size", "fill-size: ${1};"),
    ("filter", "filter: ${1};"),
    ("flex", "flex: ${1};"),
    ("flex-basis", "flex-basis: ${1};"),
    ("flex-direction", "flex-direction: ${1};"),
    ("flex-flow", "flex-flow: ${1};"),
    ("flex-grow", "flex-grow: ${1};"),
    ("flex-shrink", "flex-shrink: ${1};"),
    ("flex-wrap", "flex-wrap: ${1};"),
    ("float", "float: ${1};"),
    ("float-defer", "float-defer: ${1};"),
    ("float-offset", "float-offset: ${1};"),
    ("float-reference", "float-reference: ${1};"),
    ("flood-color", "flood-color: ${1};"),
    ("flood-opacity", "flood-opacity: ${1};"),
    ("flow", "flow: ${1};"),
    ("flow-from", "flow-from: ${1};"),
    ("flow-into", "flow-into: ${1};"),
    ("font", "font: ${1};"),
    ("font-family", "font-family: ${1};"),
    ("font-feature-settings", "font-feature-settings: ${1};"),
    ("font-kerning", "font-kerning: ${1};"),
    ("font-language-override", "font-language-override: ${1};"),
    ("font-max-size", "font-max-size: ${1};"),
    ("font-min-size", "font-min-size: ${1};"),
    ("font-optical-sizing", "font-optical-sizing: ${1};"),
    ("font-palette", "font-palette: ${1};"),
    ("font-presentation", "font-presentation: ${1};"),
    ("font-size", "font-size: ${1};"),
    ("font-size-adjust", "font-size-adjust: ${1};"),
    ("font-stretch", "font-stretch: ${1};"),
    ("font-style", "font-style: ${1};"),
    ("font-synthesis", "font-synthesis: ${1};"),
    ("font-variant", "font-variant: ${1};"),
    ("font-variant-alternates", "font-variant-alternates: ${1};"),
    ("font-variant-caps", "font-variant-caps: ${1};"),
    ("font-variant-east-asian", "font-variant-east-asian: ${1};"),
    ("font-variant-emoji", "font-variant-emoji: ${1};"),
    ("font-variant-ligatures", "font-variant-ligatures: ${1};"),
    ("font-variant-numeric", "font-variant-numeric: ${1};"),
    ("font-variant-position", "font-variant-position: ${1};"),
    ("font-variation-settings", "font-variation-settings: ${1};"),
    ("font-weight", "font-weight: ${1};"),
    ("footnote-display", "footnote-display: ${1};"),
    ("footnote-policy", "footnote-policy: ${1};"),
    ("gap", "gap: ${1};"),
    ("grid", "grid: ${1};"),
    ("grid-area", "grid-area: ${1};"),
    ("grid-auto-columns", "grid-auto-columns: ${1};"),
    ("grid-auto-flow", "grid-auto-flow: ${1};"),
    ("grid-auto-rows", "grid-auto-rows: ${1};"),
    ("grid-column", "grid-column: ${1};"),
    ("grid-column-end", "grid-column-end: ${1};"),
    ("grid-column-start", "grid-column-start: ${1};"),
    ("grid-gap", "grid-gap: ${1};"),
    ("grid-row", "grid-row: ${1};"),
    ("grid-row-end", "grid-row-end: ${1};"),
    ("grid-row-start", "grid-row-start: ${1};"),
    ("grid-template", "grid-template: ${1};"),
    ("grid-template-areas", "grid-template-areas: ${1};"),
    ("grid-template-columns", "grid-template-columns: ${1};"),
    ("grid-template-rows", "grid-template-rows: ${1};"),
    ("hanging-punctuation", "hanging-punctuation: ${1};"),
    ("height", "height: ${1};"),
    ("hyphenate-character", "hyphenate-character: ${1};"),
    ("hyphenate-limit-chars", "hyphenate-limit-chars: ${1};"),
    ("hyphenate-limit-last", "hyphenate-limit-last: ${1};"),
    ("hyphenate-limit-lines", "hyphenate-limit-lines: ${1};"),
    ("hyphenate-limit-zone", "hyphenate-limit-zone: ${1};"),
    ("hyphens", "hyphens: ${1};"),
    ("image-orientation", "image-orientation: ${1};"),
    ("image-rendering", "image-rendering: ${1};"),
    ("image-resolution", "image-resolution: ${1};"),
    ("initial-letter", "initial-letter: ${1};"),
    ("initial-letter-align", "initial-letter-align: ${1};"),
    ("initial-letter-wrap", "initial-letter-wrap: ${1};"),
    ("inline-size", "inline-size: ${1};"),
    ("inset", "inset: ${1};"),
    ("inset-block", "inset-block: ${1};"),
    ("inset-block-end", "inset-block-end: ${1};"),
    ("inset-block-start", "inset-block-start: ${1};"),
    ("inset-inline-end", "inset-inline-end: ${1};"),
    ("inset-inline-start", "inset-inline-start: ${1};"),
    ("isolation", "isolation: ${1};"),
    ("justify-content", "justify-content: ${1};"),
    ("justify-items", "justify-items: ${1};"),
    ("justify-self", "justify-self: ${1};"),
    ("left", "left: ${1};"),
    ("letter-spacing", "letter-spacing: ${1};"),
    ("lighting-color", "lighting-color: ${1};"),
    ("line-break", "line-break: ${1};"),
    ("line-grid", "line-grid: ${1};"),
    ("line-height", "line-height: ${1};"),
    ("line-height-step", "line-height-step: ${1};"),
    ("line-snap", "line-snap: ${1};"),
    ("list-style", "list-style: ${1};"),
    ("list-style-image", "list-style-image: ${1};"),
    ("list-style-position", "list-style-position: ${1};"),
    ("list-style-type", "list-style-type: ${1};"),
    ("margin", "margin: ${1};"),
    ("margin-block", "margin-block: ${1};"),
    ("margin-block-end", "margin-block-end: ${1};"),
    ("margin-block-start", "margin-block-start: ${1};"),
    ("margin-bottom", "margin-bottom: ${1};"),
    ("margin-inline", "margin-inline: ${1};"),
    ("margin-inline-end", "margin-inline-end: ${1};"),
    ("margin-inline-start", "margin-inline-start: ${1};"),
    ("margin-left", "margin-left: ${1};"),
    ("margin-right", "margin-right: ${1};"),
    ("margin-top", "margin-top: ${1};"),
    ("marker", "marker: ${1};"),
    ("marker-end", "marker-end: ${1};"),
    ("marker-knockout-left", "marker-knockout-left: ${1};"),
    ("marker-knockout-right", "marker-knockout-right: ${1};"),
    ("marker-mid", "marker-mid: ${1};"),
    ("marker-pattern", "marker-pattern: ${1};"),
    ("marker-segment", "marker-segment: ${1};"),
    ("marker-side", "marker-side: ${1};"),
    ("marker-start", "marker-start: ${1};"),
    ("marks", "marks: ${1};"),
    ("mask", "mask: ${1};"),
    ("mask-border", "mask-border: ${1};"),
    ("mask-border-mode", "mask-border-mode: ${1};"),
    ("mask-border-outset", "mask-border-outset: ${1};"),
    ("mask-border-repeat", "mask-border-repeat: ${1};"),
    ("mask-border-slice", "mask-border-slice: ${1};"),
    ("mask-border-source", "mask-border-source: ${1};"),
    ("mask-border-width", "mask-border-width: ${1};"),
    ("mask-clip", "mask-clip: ${1};"),
    ("mask-composite", "mask-composite: ${1};"),
    ("mask-image", "mask-image: ${1};"),
    ("mask-mode", "mask-mode: ${1};"),
    ("mask-origin", "mask-origin: ${1};"),
    ("mask-position", "mask-position: ${1};"),
    ("mask-repeat", "mask-repeat: ${1};"),
    ("mask-size", "mask-size: ${1};"),
    ("mask-type", "mask-type: ${1};"),
    ("max-block-size", "max-block-size: ${1};"),
    ("max-height", "max-height: ${1};"),
    ("max-inline-size", "max-inline-size: ${1};"),
    ("max-lines", "max-lines: ${1};"),
    ("max-width", "max-width: ${1};"),
    ("min-block-size", "min-block-size: ${1};"),
    ("min-height", "min-height: ${1};"),
    ("min-inline-size", "min-inline-size: ${1};"),
    ("min-width", "min-width: ${1};"),
    ("mix-blend-mode", "mix-blend-mode: ${1};"),
    ("motion", "motion: ${1};"),
    ("motion-offset", "motion-offset: ${1};"),
    ("motion-path", "motion-path: ${1};"),
    ("motion-rotation", "motion-rotation: ${1};"),
    ("nav-down", "nav-down: ${1};"),
    ("nav-left", "nav-left: ${1};"),
    ("nav-right", "nav-right: ${1};"),
    ("nav-up", "nav-up: ${1};"),
    ("object-fit", "object-fit: ${1};"),
    ("object-position", "object-position: ${1};"),
    ("offset", "offset: ${1};"),
    ("offset-after", "offset-after: ${1};"),
    ("offset-anchor", "offset-anchor: ${1};"),
    ("offset-before", "offset-before: ${1};"),
    ("offset-distance", "offset-distance: ${1};"),
    ("offset-end", "offset-end: ${1};"),
    ("offset-path", "offset-path: ${1};"),
    ("offset-position", "offset-position: ${1};"),
    ("offset-rotate", "offset-rotate: ${1};"),
    ("offset-start", "offset-start: ${1};"),
    ("opacity", "opacity: ${1};"),
    ("order", "order: ${1};"),
    ("orphans", "orphans: ${1};"),
    ("outline", "outline: ${1};"),
    ("outline-color", "outline-color: ${1};"),
    ("outline-offset", "outline-offset: ${1};"),
    ("outline-style", "outline-style: ${1};"),
    ("outline-width", "outline-width: ${1};"),
    ("overflow", "overflow: ${1};"),
    ("overflow-anchor", "overflow-anchor: ${1};"),
    ("overflow-wrap", "overflow-wrap: ${1};"),
    ("overflow-x", "overflow-x: ${1};"),
    ("overflow-y", "overflow-y: ${1};"),
    ("overscroll-behavior", "overscroll-behavior: ${1};"),
    ("overscroll-behavior-block", "overscroll-behavior-block: ${1};"),
    ("overscroll-behavior-inline", "overscroll-behavior-inline: ${1};"),
    ("overscroll-behavior-x", "overscroll-behavior-x: ${1};"),
    ("overscroll-behavior-y", "overscroll-behavior-y: ${1};"),
    ("padding", "padding: ${1};"),
    ("padding-block", "padding-block: ${1};"),
    ("padding-block-end", "padding-block-end: ${1};"),
    ("padding-block-start", "padding-block-start: ${1};"),
    ("padding-bottom", "padding-bottom: ${1};"),
    ("padding-inline-end", "padding-inline-end: ${1};"),
    ("padding-inline-start", "padding-inline-start: ${1};"),
    ("padding-left", "padding-left: ${1};"),
    ("padding-right", "padding-right: ${1};"),
    ("padding-top", "padding-top: ${1};"),
    ("page", "page: ${1};"),
    ("page-break-after", "page-break-after: ${1};"),
    ("page-break-before", "page-break-before: ${1};"),
    ("page-break-inside", "page-break-inside: ${1};"),
    ("paint-order", "paint-order: ${1};"),
    ("pause", "pause: ${1};"),
    ("pause-after", "pause-after: ${1};"),
    ("pause-before", "pause-before: ${1};"),
    ("perspective", "perspective: ${1};"),
    ("perspective-origin", "perspective-origin: ${1};"),
    ("place-content", "place-content: ${1};"),
    ("place-items", "place-items: ${1};"),
    ("place-self", "place-self: ${1};"),
    ("pointer-events", "pointer-events: ${1};"),
    ("polar-anchor", "polar-anchor: ${1};"),
    ("polar-angle", "polar-angle: ${1};"),
    ("polar-distance", "polar-distance: ${1};"),
    ("polar-origin", "polar-origin: ${1};"),
    ("position", "position: ${1};"),
    ("presentation-level", "presentation-level: ${1};"),
    ("quotes", "quotes: ${1};"),
    ("region-fragment", "region-fragment: ${1};"),
    ("resize", "resize: ${1};"),
    ("rest", "rest: ${1};"),
    ("rest-after", "rest-after: ${1};"),
    ("rest-before", "rest-before: ${1};"),
    ("right", "right: ${1};"),
    ("rotate", "rotate: ${1};"),
    ("rotation", "rotation: ${1};"),
    ("rotation-point", "rotation-point: ${1};"),
    ("row-gap", "row-gap: ${1};"),
    ("ruby-align", "ruby-align: ${1};"),
    ("ruby-merge", "ruby-merge: ${1};"),
    ("ruby-position", "ruby-position: ${1};"),
    ("running", "running: ${1};"),
    ("scale", "scale: ${1};"),
    ("scroll-behavior", "scroll-behavior: ${1};"),
    ("scroll-margin", "scroll-margin: ${1};"),
    ("scroll-margin-block", "scroll-margin-block: ${1};"),
    ("scroll-margin-block-end", "scroll-margin-block-end: ${1};"),
    ("scroll-margin-block-start", "scroll-margin-block-start: ${1};"),
    ("scroll-margin-bottom", "scroll-margin-bottom: ${1};"),
    ("scroll-margin-inline", "scroll-margin-inline: ${1};"),
    ("scroll-margin-inline-end", "scroll-margin-inline-end: ${1};"),
    ("scroll-margin-inline-start", "scroll-margin-inline-start: ${1};"),
    ("scroll-margin-left", "scroll-margin-left: ${1};"),
    ("scroll-margin-right", "scroll-margin-right: ${1};"),
    ("scroll-margin-top", "scroll-margin-top: ${1};"),
    ("scroll-padding", "scroll-padding: ${1};"),
    ("scroll-padding-block", "scroll-padding-block: ${1};"),
    ("scroll-padding-block-end", "scroll-padding-block-end: ${1};"),
    ("scroll-padding-block-start", "scroll-padding-block-start: ${1};"),
    ("scroll-padding-bottom", "scroll-padding-bottom: ${1};"),
    ("scroll-padding-inline", "scroll-padding-inline: ${1};"),
    ("scroll-padding-inline-end", "scroll-padding-inline-end: ${1};"),
    ("scroll-padding-inline-start", "scroll-padding-inline-start: ${1};"),
    ("scroll-padding-left", "scroll-padding-left: ${1};"),
    ("scroll-padding-right", "scroll-padding-right: ${1};"),
    ("scroll-padding-top", "scroll-padding-top: ${1};"),
    ("scroll-snap-align", "scroll-snap-align: ${1};"),
    ("scroll-snap-stop", "scroll-snap-stop: ${1};"),
    ("scroll-snap-type", "scroll-snap-type: ${1};"),
    ("shape-image-threshold", "shape-image-threshold: ${1};"),
    ("shape-inside", "shape-inside: ${1};"),
    ("shape-margin", "shape-margin: ${1};"),
    ("shape-outside", "shape-outside: ${1};"),
    ("shape-rendering", "shape-rendering: ${1};"),
    ("size", "size: ${1};"),
    ("spatial-navigation-action", "spatial-navigation-action: ${1};"),
    ("spatial-navigation-contain", "spatial-navigation-contain: ${1};"),
    ("spatial-navigation-function", "spatial-navigation-function: ${1};"),
    ("speak", "speak: ${1};"),
    ("speak-as", "speak-as: ${1};"),
    ("stop-color", "stop-color: ${1};"),
    ("stop-opacity", "stop-opacity: ${1};"),
    ("string-set", "string-set: ${1};"),
    ("stroke", "stroke: ${1};"),
    ("stroke-align", "stroke-align: ${1};"),
    ("stroke-alignment", "stroke-alignment: ${1};"),
    ("stroke-break", "stroke-break: ${1};"),
    ("stroke-color", "stroke-color: ${1};"),
    ("stroke-dash-corner", "stroke-dash-corner: ${1};"),
    ("stroke-dash-justify", "stroke-dash-justify: ${1};"),
    ("stroke-dashadjust", "stroke-dashadjust: ${1};"),
    ("stroke-dasharray", "stroke-dasharray: ${1};"),
    ("stroke-dashcorner", "stroke-dashcorner: ${1};"),
    ("stroke-dashoffset", "stroke-dashoffset: ${1};"),
    ("stroke-image", "stroke-image: ${1};"),
    ("stroke-linecap", "stroke-linecap: ${1};"),
    ("stroke-linejoin", "stroke-linejoin: ${1};"),
    ("stroke-miterlimit", "stroke-miterlimit: ${1};"),
    ("stroke-opacity", "stroke-opacity: ${1};"),
    ("stroke-origin", "stroke-origin: ${1};"),
    ("stroke-position", "stroke-position: ${1};"),
    ("stroke-repeat", "stroke-repeat: ${1};"),
    ("stroke-width", "stroke-width: ${1};"),
    ("tab-size", "tab-size: ${1};"),
    ("table-layout", "table-layout: ${1};"),
    ("text-align", "text-align: ${1};"),
    ("text-align-all", "text-align-all: ${1};"),
    ("text-align-last", "text-align-last: ${1};"),
    ("text-anchor", "text-anchor: ${1};"),
    ("text-combine-upright", "text-combine-upright: ${1};"),
    ("text-decoration", "text-decoration: ${1};"),
    ("text-decoration-color", "text-decoration-color: ${1};"),
    ("text-decoration-line", "text-decoration-line: ${1};"),
    ("text-decoration-skip", "text-decoration-skip: ${1};"),
    ("text-decoration-skip-ink", "text-decoration-skip-ink: ${1};"),
    ("text-decoration-style", "text-decoration-style: ${1};"),
    ("text-decoration-width", "text-decoration-width: ${1};"),
    ("text-emphasis", "text-emphasis: ${1};"),
    ("text-emphasis-color", "text-emphasis-color: ${1};"),
    ("text-emphasis-position", "text-emphasis-position: ${1};"),
    ("text-emphasis-skip", "text-emphasis-skip: ${1};"),
    ("text-emphasis-style", "text-emphasis-style: ${1};"),
    ("text-indent", "text-indent: ${1};"),
    ("text-justify", "text-justify: ${1};"),
    ("text-orientation", "text-orientation: ${1};"),
    ("text-overflow", "text-overflow: ${1};"),
    ("text-rendering", "text-rendering: ${1};"),
    ("text-shadow", "text-shadow: ${1};"),
    ("text-size-adjust", "text-size-adjust: ${1};"),
    ("text-space-collapse", "text-space-collapse: ${1};"),
    ("text-space-trim", "text-space-trim: ${1};"),
    ("text-spacing", "text-spacing: ${1};"),
    ("text-transform", "text-transform: ${1};"),
    ("text-underline-offset", "text-underline-offset: ${1};"),
    ("text-underline-position", "text-underline-position: ${1};"),
    ("text-wrap", "text-wrap: ${1};"),
    ("top", "top: ${1};"),
    ("transform", "transform: ${1};"),
    ("transform-box", "transform-box: ${1};"),
    ("transform-origin", "transform-origin: ${1};"),
    ("transform-style", "transform-style: ${1};"),
    ("transition", "transition: ${1};"),
    ("transition-delay", "transition-delay: ${1};"),
    ("transition-duration", "transition-duration: ${1};"),
    ("transition-property", "transition-property: ${1};"),
    ("transition-timing-function", "transition-timing-function: ${1};"),
    ("translate", "translate: ${1};"),
    ("unicode-bidi", "unicode-bidi: ${1};"),
    ("user-select", "user-select: ${1};"),
    ("vector-effect", "vector-effect: ${1};"),
    ("vertical-align", "vertical-align: ${1};"),
    ("visibility", "visibility: ${1};"),
    ("voice-balance", "voice-balance: ${1};"),
    ("voice-duration", "voice-duration: ${1};"),
    ("voice-family", "voice-family: ${1};"),
    ("voice-pitch", "voice-pitch: ${1};"),
    ("voice-range", "voice-range: ${1};"),
    ("voice-rate", "voice-rate: ${1};"),
    ("voice-stress", "voice-stress: ${1};"),
    ("voice-volume", "voice-volume: ${1};"),
    ("white-space", "white-space: ${1};"),
    ("widows", "widows: ${1};"),
    ("width", "width: ${1};"),
    ("will-change", "will-change: ${1};"),
    ("word-break", "word-break: ${1};"),
    ("word-spacing", "word-spacing: ${1};"),
    ("word-wrap", "word-wrap: ${1};"),
    ("wrap-after", "wrap-after: ${1};"),
    ("wrap-before", "wrap-before: ${1};"),
    ("wrap-flow", "wrap-flow: ${1};"),
    ("wrap-inside", "wrap-inside: ${1};"),
    ("wrap-through", "wrap-through: ${1};"),
    ("writing-mode", "writing-mode: ${1};"),
    ("z-index", "z-index: ${1};"),
]

media_features = [
    ("any-hover", "any-hover: ${0}"),
    ("any-pointer", "any-pointer: ${0}"),
    ("aspect-ratio", "aspect-ratio: ${1}/"),
    ("color", "color: ${0}"),
    ("color-gamut", "color-gamut: ${0}"),
    ("color-index", "color-index: ${0}"),
    ("environment-blending", "environment-blending: ${0}"),
    ("forced-colors", "forced-colors: ${0}"),
    ("grid",),
    ("hover", "hover: ${0}"),
    ("inverted-colors", "inverted-colors: ${0}"),
    ("light-level", "light-level: ${0}"),
    ("max-aspect-ratio", "max-aspect-ratio: ${0}"),
    ("max-color", "max-color: ${0}"),
    ("max-color-index", "max-color-index: ${0}"),
    ("max-height", "max-height: ${0}"),
    ("max-monochrome", "max-monochrome: ${0}"),
    ("max-resolution", "max-resolution: ${0}"),
    ("max-width", "max-width: ${0}"),
    ("min-aspect-ratio", "min-aspect-ratio: ${0}"),
    ("min-color", "min-color: ${0}"),
    ("min-color-index", "min-color-index: ${0}"),
    ("min-height", "min-height: ${0}"),
    ("min-monochrome", "min-monochrome: ${0}"),
    ("min-resolution", "min-resolution: ${0}"),
    ("min-width", "min-width: ${0}"),
    ("monochrome", "monochrome: ${0}"),
    ("orientation", "orientation: ${0}"),
    ("overflow-block", "overflow-block: ${0}"),
    ("overflow-inline", "overflow-inline: ${0}"),
    ("pointer", "pointer: ${0}"),
    ("prefers-color-scheme", "prefers-color-scheme: ${0}"),
    ("prefers-contrast", "prefers-contrast: ${0}"),
    ("prefers-reduced-data", "prefers-reduced-data: ${0}"),
    ("prefers-reduced-motion", "prefers-reduced-motion: ${0}"),
    ("prefers-reduced-transparency", "prefers-reduced-transparency: ${0}"),
    ("resolution", "resolution: ${0}"),
    ("scan", "scan: ${0}"),
    ("scripting",),
    ("update", "update: ${0}"),
]

name_to_completions = {
    "align-content": [("normal",),]
    + t.baseline_position
    + t.content_distribution
    + t.content_position
    + t.overflow_position
    + t.aspect_ratio
    + t.number,
    "align-items": [("normal",), ("stretch",),]
    + t.baseline_position
    + t.overflow_position
    + t.self_position,
    "align-self": [("auto",), ("normal",), ("stretch",),]
    + t.baseline_position
    + t.overflow_position
    + t.self_position,
    "alignment-baseline": [
        ("after-edge",),
        ("alphabetic",),
        ("auto",),
        ("baseline",),
        ("before-edge",),
        ("bottom",),
        ("center",),
        ("central",),
        ("hanging",),
        ("ideographic",),
        ("mathematical",),
        ("middle",),
        ("text-after-edge",),
        ("text-before-edge",),
        ("text-bottom",),
        ("text-top",),
        ("top",),
    ],
    # "all": [],  # TODO: write this when the context for any-value is completed
    "animation": (
        t.single_animation_direction
        + t.single_animation_fill_mode
        + t.single_animation_iteration_count
        + t.single_animation_name
        + t.single_animation_play_state
        + t.single_timing_function
        + t.time
    ),
    "animation-composition": t.single_animation_composition,
    "animation-delay": t.time,
    "animation-direction": t.single_animation_direction,
    "animation-duration": t.time,
    "animation-fill-mode": t.single_animation_fill_mode,
    "animation-iteration-count": t.single_animation_iteration_count,
    "animation-name": t.single_animation_name,
    "animation-play-state": t.single_animation_play_state,
    "animation-timing-function": t.single_timing_function,
    "appearance": [
        ("auto",),
        ("button",),
        ("checkbox",),
        ("listbox",),
        ("menulist",),
        ("menulist-button",),
        ("meter",),
        ("none",),
        ("progress-bar",),
        ("push-button",),
        ("radio",),
        ("searchfield",),
        ("slider-horizontal",),
        ("square-button",),
        ("textarea",),
        ("textfield",),
    ],
    "backface-visibility": [("hidden",), ("visible",)],
    "background-attachment": t.attachment,
    "background-blend-mode": t.blend_mode,
    "background-clip": t.box,
    "background-color": t.color,
    "background-image": t.bg_image,
    "background-image-transform": [("logical",), ("physical",), ("rotate",)],
    "background-origin": t.box,
    "background-position": t.position,
    "background-repeat": t.repeat_style,
    "background-size": t.bg_size,
    "background": (
        t.attachment
        + t.bg_image
        + t.bg_size
        + t.box
        + t.color
        + t.position
        + t.repeat_style
    ),
    "baseline-shift": t.baseline_shift,
    "bleed": [("auto",)] + t.length,
    "block-inline-size": [("auto",)] + t.length + t.percentage,
    "block-step": [
        ("auto",),
        ("center",),
        ("down",),
        ("end",),
        ("margin",),
        ("nearest",),
        ("none",),
        ("padding",),
        ("start",),
        ("up",),
    ]
    + t.length,
    "block-step-align": [("auto",), ("center",), ("end",), ("start",)],
    "block-step-insert": [("margin",), ("padding",)],
    "block-step-round": [("down",), ("nearest",), ("up",)],
    "block-step-size": [("none",)] + t.length,
    "bookmark-label": t.content_list,
    "bookmark-level": [("none",)] + t.integer,
    "bookmark-state": [("closed",), ("open",)],
    "border": t.border_style + t.border_width + t.color,
    "border-block-inline": t.color + t.line_style + t.line_width,
    "border-block-inline-color": t.color,
    "border-block-inline-style": t.line_style,
    "border-block-inline-width": t.line_width,
    "border-boundary": [("display",), ("none",), ("parent",)],
    "border-collapse": [("collapse",), ("separate",)],
    "border-color": t.color,
    "border-image": [
        ("auto",),
        ("fill",),
        ("none",),
        ("repeat",),
        ("round",),
        ("space",),
        ("stretch",),
    ]
    + t.image
    + t.integer
    + t.length
    + t.number,
    "border-image-outset": t.length + t.number,
    "border-image-repeat": [("repeat",), ("round",), ("space",), ("stretch",)],
    "border-image-slice": [("fill",)] + t.integer + t.percentage,
    "border-image-source": [("none",)] + t.image,
    "border-image-transform": [("logical",), ("physical",), ("rotate",)],
    "border-image-width": [("auto",)] + t.length + t.number + t.percentage,
    "border-radius": t.length + t.percentage,
    "border-spacing": t.length,
    "border-style": t.border_style,
    "border-top-right-left-bottom": t.border_style + t.border_width + t.color,
    "border-width": t.border_width,
    "box-decoration-break": [("clone",), ("slice",)],
    "box-shadow": [("inset",), ("none",)] + t.color + t.length,
    "box-sizing": [("border-box",), ("content-box",)],
    "box-snap": [
        ("baseline",),
        ("block-end",),
        ("block-start",),
        ("center",),
        ("last-baseline",),
        ("none",),
    ],
    "break-before-after": [
        ("always",),
        ("auto",),
        ("avoid",),
        ("avoid-column",),
        ("avoid-page",),
        ("avoid-region",),
        ("column",),
        ("left",),
        ("page",),
        ("recto",),
        ("region",),
        ("right",),
        ("verso",),
    ],
    "break-inside": [
        ("auto",),
        ("avoid",),
        ("avoid-column",),
        ("avoid-page",),
        ("avoid-region",),
    ],
    "caption-side": [("bottom",), ("inline-end",), ("inline-start",), ("top",)],
    "caret-color": [("auto",)] + t.color,
    "caret-shape": t.caret_shape,
    "caret": [("auto",)] + t.caret_shape + t.color,
    "chains": [("none",), t.identifier],
    "clear": [
        ("block-end",),
        ("block-start",),
        ("both",),
        ("both-block",),
        ("both-inline",),
        ("bottom",),
        ("inline-end",),
        ("inline-start",),
        ("left",),
        ("none",),
        ("right",),
        ("top",),
    ],
    "clip-path": [("none",), t.url] + t.basic_shape + t.geometry_box,
    "clip-rule": [("evenodd",), ("nonzero",)],
    "color": t.color,
    "color-adjust": [("economy",), ("exact",)],
    "color-gamut": [("p3",), ("rec2020",), ("srgb",)],
    "color-interpolation-filters": [("auto",), ("linearRGB",), ("sRGB",)],
    "color-rendering": [("auto",), ("optimizeQuality",), ("optimizeSpeed",)],
    "columns": [("auto",)] + t.integer + t.length,
    "column-count": [("auto",)] + t.integer,
    "column-fill": [("auto",), ("balance",), ("balance-all",)],
    "column-rule": t.color + t.line_style + t.line_width,
    "column-rule-color": t.color,
    "column-rule-style": t.line_style,
    "column-rule-width": t.line_width,
    "column-span": [("all",), ("none",)],
    "column-width": [("auto",)] + t.length,
    "composes": [("from",), t.string],
    "contain": [
        ("content",),
        ("layout",),
        ("none",),
        ("paint",),
        ("size",),
        ("strict",),
    ],
    "content": [("none",), ("normal",), t.attr, t.counter, t.counters, t.string,]
    + t.content_list
    + t.image,
    "continue": [
        ("auto",),
        ("discard",),
        ("fragments",),
        ("overflow",),
        ("paginate",),
    ],
    "counter-set-reset-increment": [("none",), t.attr, t.identifier] + t.integer,
    "cue-before-after": [("none",), t.url] + t.decibel,
    "cursor": [
        ("alias",),
        ("all-scroll",),
        ("auto",),
        ("cell",),
        ("col-resize",),
        ("context-menu",),
        ("copy",),
        ("crosshair",),
        ("default",),
        ("e-resize",),
        ("ew-resize",),
        ("grab",),
        ("grabbing",),
        ("help",),
        ("move",),
        ("n-resize",),
        ("ne-resize",),
        ("nesw-resize",),
        ("no-drop",),
        ("none",),
        ("not-allowed",),
        ("ns-resize",),
        ("nw-resize",),
        ("nwse-resize",),
        ("pointer",),
        ("progress",),
        ("row-resize",),
        ("s-resize",),
        ("se-resize",),
        ("sw-resize",),
        ("text",),
        ("vertical-text",),
        ("w-resize",),
        ("wait",),
        ("zoom-in",),
        ("zoom-out",),
        t.url,
    ]
    + t.number,
    "direction": [("ltr",), ("rtl",)],
    "display": (
        t.display_box
        + t.display_inside
        + t.display_internal
        + t.display_legacy
        + t.display_listitem
        + t.display_outside
    ),
    "dominant-baseline": [
        ("alphabetic",),
        ("auto",),
        ("central",),
        ("hanging",),
        ("ideographic",),
        ("mathematical",),
        ("middle",),
        ("text-bottom",),
        ("text-top",),
    ],
    "empty-cells": [("hide",), ("show",)],
    "environment-blending": [("additive",), ("opaque",), ("subtractive",)],
    "fill": t.background,
    "fill-break": [("bounding-box",), ("clone",), ("slice",)],
    "fill-color": t.color,
    "fill-image": t.paint,
    "fill-opacity": t.number,
    "fill-origin": [
        ("border-box",),
        ("content-box",),
        ("fill-box",),
        ("match-parent",),
        ("padding-box",),
        ("stroke-box",),
    ],
    "fill-position": t.position,
    "fill-repeat": t.repeat_style,
    "fill-rule": [("evenodd",), ("nonzero",)],
    "fill-size": t.bg_size,
    "filter": [("none",), t.blur, t.drop_shadow, t.filter_func, t.hue_rotate, t.url],
    "flex": [("auto",), ("content",), ("initial",), ("none",)]
    + t.length
    + t.number
    + t.percentage,
    "flex-basis": [("auto",), ("content",)] + t.length + t.percentage + t.width,
    "flex-direction": t.flex_direction,
    "flex-flow": t.flex_direction + t.flex_wrap,
    "flex-shrink-grow": t.number,
    "flex-wrap": t.flex_wrap,
    "float": [
        ("block-end",),
        ("block-start",),
        ("bottom",),
        ("inline-end",),
        ("inline-start",),
        ("left",),
        ("none",),
        ("right",),
        ("snap-block",),
        ("snap-inline",),
        ("top",),
        t.snap_block,
        t.snap_inline,
    ],
    "float-defer": [("last",), ("none",)] + t.integer,
    "float-offset": t.length + t.percentage,
    "float-reference": [("column",), ("inline",), ("page",), ("region",)],
    "flood-color": t.color,
    "flood-opacity": t.number + t.percentage,
    "flow": [("auto",), ("same",), t.identifier, t.string],
    "flow-from": [("none",), t.identifier],
    "flow-into": [("content",), ("element",), ("none",), t.identifier],
    "font": [
        ("100",),
        ("200",),
        ("300",),
        ("400",),
        ("500",),
        ("600",),
        ("700",),
        ("800",),
        ("900",),
        ("bold",),
        ("bolder",),
        ("caption",),
        ("condensed",),
        ("expanded",),
        ("extra-condensed",),
        ("extra-expanded",),
        ("icon",),
        ("italic",),
        ("large",),
        ("larger",),
        ("lighter",),
        ("medium",),
        ("menu",),
        ("message-box",),
        ("normal",),
        ("oblique",),
        ("semi-condensed",),
        ("semi-expanded",),
        ("small",),
        ("small-caps",),
        ("small-caption",),
        ("smaller",),
        ("status-bar",),
        ("ultra-condensed",),
        ("ultra-expanded",),
        ("x-large",),
        ("x-small",),
        ("xx-large",),
        ("xx-small",),
    ]
    + (t.font_family_generic + t.font_family_name + t.length + t.number + t.percentage),
    "font-family": t.font_family_generic + t.font_family_name,
    "font-feature-settings": [("normal",)] + t.feature_tag_value,
    "font-kerning": [("auto",), ("none",), ("normal",)],
    "font-language-override": [("normal",), t.string],
    "font-optical-sizing": [("auto",), ("none",)],
    "font-palette": [("dark",), ("light",), ("normal",), t.identifier,],
    "font-presentation": [("auto",), ("emoji",), ("text",)],
    "font-size": [
        ("infinity",),
        ("large",),
        ("larger",),
        ("medium",),
        ("small",),
        ("smaller",),
        ("x-large",),
        ("x-small",),
        ("xx-large",),
        ("xx-small",),
    ]
    + t.length
    + t.percentage,
    "font-size-adjust": [("none",)] + t.number,
    "font-stretch": [
        ("condensed",),
        ("expanded",),
        ("extra-condensed",),
        ("extra-expanded",),
        ("normal",),
        ("semi-condensed",),
        ("semi-expanded",),
        ("ultra-condensed",),
        ("ultra-expanded",),
    ]
    + t.percentage,
    "font-style": [("italic",), ("normal",), ("oblique",)] + t.angle,
    "font-synthesis": [("none",), ("small-caps",), ("style",), ("weight",)],
    "font-variant": [
        ("all-petite-caps",),
        ("all-small-caps",),
        ("none",),
        ("normal",),
        ("ordinal",),
        ("petite-caps",),
        ("ruby",),
        ("slashed-zero",),
        ("small-caps",),
        ("sub",),
        ("super",),
        ("titling-caps",),
        ("unicase",),
        t.annotation,
        t.character_variant,
        t.ornaments,
        t.stylistic,
        t.styleset,
        t.swash,
    ]
    + t.font_variant,
    "font-variant-alternates": [
        ("historical-forms",),
        ("normal",),
        t.annotation,
        t.character_variant,
        t.ornaments,
        t.stylistic,
        t.styleset,
        t.swash,
    ],
    "font-variant-caps": [
        ("all-petite-caps",),
        ("all-small-caps",),
        ("normal",),
        ("petite-caps",),
        ("small-caps",),
        ("titling-caps",),
        ("unicase",),
    ],
    "font-variant-east-asian": [("normal",), ("ruby",),]
    + t.east_asian_width_values
    + t.east_asian_variant_values,
    "font-variant-emoji": [("auto",), ("emoji",), ("text",),],
    "font-variant-ligatures": [("none",), ("normal",),]
    + (
        t.common_lig_values
        + t.contextual_alt_values
        + t.discretionary_lig_values
        + t.historical_lig_values
    ),
    "font-variant-numeric": [("normal",), ("ordinal",), ("slashed-zero",),]
    + t.numeric_figure_values
    + t.numeric_fraction_values
    + t.numeric_spacing_values,
    "font-variant-position": [("normal",), ("sub",), ("super",)],
    "font-variation-settings": [("normal",), t.string] + t.number,
    "font-weight": [
        ("100",),
        ("200",),
        ("300",),
        ("400",),
        ("500",),
        ("600",),
        ("700",),
        ("800",),
        ("900",),
        ("bold",),
        ("bolder",),
        ("lighter",),
        ("normal",),
    ],
    "footnote-display": [("block",), ("compact",), ("inline",)],
    "footnote-policy": [("auto",), ("block",), ("line",)],
    "forced-colors": [("active",), ("none",)],
    "grid": [("auto-flow",), ("dense",), ("none",), ("subgrid",), t.string,]
    + t.auto_track_list
    + t.track_list,
    "grid-row-column-area": t.grid_line,
    "grid-row-column-gap": t.length + t.percentage,
    "grid-auto-flow": [("column",), ("dense",), ("row",)],
    "grid-auto-rows-columns": t.track_size,
    "grid-template-areas": [("none",), t.string],
    "grid-template-rows-columns": [("none",), ("subgrid",),]
    + t.auto_track_list
    + t.track_list,
    "grid-template": [("none",), ("subgrid",), t.line_names, t.string,]
    + t.fixed_size
    + t.track_size,
    "hanging-punctuation": [
        ("allow-end",),
        ("first",),
        ("force-end",),
        ("last",),
        ("none",),
    ],
    "height": [
        ("auto",),
        ("fill",),
        ("fit-content",),
        ("max-content",),
        ("min-content",),
        ("none",),
        t.fit_content,
    ]
    + t.length
    + t.percentage,
    "hover": [("hover",), ("none",)],
    "hyphenate-character": [("auto",), t.string,],
    "hyphenate-limit-chars": [("auto",)] + t.integer,
    "hyphenate-limit-last": [
        ("always",),
        ("column",),
        ("none",),
        ("page",),
        ("spread",),
    ],
    "hyphenate-limit-lines": [("no-limit",)] + t.integer,
    "hyphenate-limit-zone": t.length + t.percentage,
    "hyphens": [("auto",), ("manual",), ("none",)],
    "image-orientation": [("flip",), ("from-image",)] + t.angle,
    "image-rendering": [("auto",), ("crisp-edges",), ("pixelated",)],
    "image-resolution": [("from-image",), ("snap",)] + t.resolution,
    "initial-letter": [("normal",)] + t.integer + t.number,
    "initial-letter-align": [
        ("alphabetic",),
        ("border-box",),
        ("hanging",),
        ("hebrew",),
        ("ideographic",),
    ],
    "initial-letter-wrap": [("all",), ("first",), ("grid",), ("none",),]
    + t.length
    + t.percentage,
    "inset-block-inline": [("auto",)] + t.length + t.percentage,
    "inverted-colors": [("inverted",), ("none",)],
    "isolation": t.isolation_mode,
    "justify-content": [
        ("center",),
        ("flex-end",),
        ("flex-start",),
        ("left",),
        ("normal",),
        ("right",),
        ("space-around",),
        ("space-between",),
    ]
    + (
        t.content_distribution
        + t.overflow_position
        + t.content_position
        + t.aspect_ratio
        + t.number
    ),
    "justify-items": [
        ("center",),
        ("left",),
        ("legacy",),
        ("normal",),
        ("right",),
        ("stretch",),
    ]
    + (t.baseline_position + t.overflow_position + t.self_position),
    "justify-self": [("auto",), ("left",), ("normal",), ("right",), ("stretch",),]
    + t.baseline_position
    + t.overflow_position
    + t.self_position,
    "letter-spacing": [("normal",)] + t.length,
    "light-level": [("dim",), ("normal",), ("washed",)],
    "lighting-color": t.color,
    "line-break": [("auto",), ("loose",), ("normal",), ("strict",)],
    "line-grid": [("create",), ("match-parent",)],
    "line-height": [("normal",)] + t.length + t.number + t.percentage,
    "line-height-step": [("none",)] + t.length,
    "line-snap": [("baseline",), ("contain",), ("none",)],
    "list-style": [("inside",), ("none",), ("outside",), t.identifier, t.string,]
    + t.image,
    "list-style-image": [("none",)] + t.image,
    "list-style-position": [("inside",), ("outside",)],
    "list-style-type": [("none",), t.identifier, t.string, t.symbols],
    "margin": [("auto",), ("logical",)] + t.length + t.percentage,
    "margin-block-inline": [("auto",)] + t.length + t.percentage,
    "marker": [("none",)] + t.length + t.percentage,
    "marker-knockout": t.knockout_offset + t.knockout_shape,
    "marker-pattern": t.marker_gap + t.marker_ref,
    "marker-start-segment-mid-end": [("none",)] + t.marker_ref,
    "marker-side": [("list-container",), ("list-item",)],
    "marks": [("crop",), ("cross",), ("none",)],
    "mask": t.mask_layer,
    "mask-border": [
        ("alpha",),
        ("auto",),
        ("fill",),
        ("luminance",),
        ("repeat",),
        ("round",),
        ("space",),
        ("stretch",),
    ]
    + t.image
    + t.length
    + t.number
    + t.percentage,
    "mask-border-mode": [("alpha",), ("luminance",),],
    "mask-border-outset": t.length + t.percentage,
    "mask-border-repeat": [("repeat",), ("round",), ("space",), ("stretch",),],
    "mask-border-slice": [("fill",)] + t.number + t.percentage,
    "mask-border-source": t.image,
    "mask-border-width": [("auto",)] + t.length + t.number + t.percentage,
    "mask-clip": [("no-clip",)] + t.geometry_box,
    "mask-composite": t.compositing_operator,
    "mask-image": t.mask_reference,
    "mask-mode": t.masking_mode,
    "mask-origin": t.geometry_box,
    "mask-position": t.position,
    "mask-repeat": t.repeat_style,
    "mask-size": t.bg_size,
    "mask-type": [("alpha",), ("luminance",),],
    "max-lines": [("none",)] + t.integer,
    "media-feature-grid": [("0",), ("1",)],
    "mix-blend-mode": t.blend_mode,
    "monochrome-color-index": t.integer,
    "motion": [("auto",), ("none",), ("reverse",), t.path, t.url,]
    + (t.angle + t.basic_shape + t.geometry_box + t.length + t.percentage),
    "motion-offset": t.length + t.percentage,
    "motion-path": [("none",), t.path, t.url,] + t.basic_shape + t.geometry_box,
    "motion-rotation": [("auto",), ("reverse",)] + t.angle,
    "nav-up-right-left-down": [("auto",), ("current",), ("root",), t.string],
    "object-fit": [("contain",), ("cover",), ("fill",), ("none",), ("scale-down",),],
    "object-position": t.position,
    "offset": [("auto",), ("none",), ("reverse",), t.path, t.ray, t.url,]
    + t.angle
    + t.basic_shape
    + t.extent_keyword
    + t.geometry_box
    + t.length
    + t.percentage
    + t.position,
    "offset-anchor": [("auto",)] + t.position,
    "offset-distance": t.extent_keyword + t.length + t.percentage,
    "offset-path": [("none",), t.path, t.ray, t.url,] + t.basic_shape + t.geometry_box,
    "offset-position": [("auto",)] + t.position,
    "offset-rotate": [("auto",), ("reverse",)] + t.angle,
    "offset-start-end-before-after": [("auto",)] + t.length + t.percentage,
    "opacity": t.number,
    "order": t.integer,
    "orientation": [("landscape",), ("portrait",)],
    "outline": [("auto",), ("invert",)] + (t.border_style + t.border_width + t.color),
    "outline-color": [("invert",)] + t.color,
    "outline-offset": t.length,
    "outline-style": [("auto",)] + t.border_style,
    "outline-width": t.border_width,
    "overflow": [("auto",), ("clip",), ("hidden",), ("scroll",), ("visible",)],
    "overflow-block": [("none",), ("optional-paged",), ("paged",), ("scroll",)],
    "overflow-inline": [("none",), ("scroll",)],
    "overflow-anchor": [("auto",), ("none",)],
    "overflow-wrap": [("break-word",), ("normal",)],
    "overflow-x-y": [("auto",), ("clip",), ("hidden",), ("scroll",), ("visible",),],
    "overscroll-behavior": [("auto",), ("contain",), ("none",)],
    "padding": [("logical",)] + t.length + t.percentage,
    "padding-block-inline": t.length + t.percentage,
    "page": [("auto",), t.identifier],
    "page-break-before-after": [
        ("always",),
        ("auto",),
        ("avoid",),
        ("left",),
        ("recto",),
        ("right",),
        ("verso",),
    ],
    "page-break-inside": [("avoid",), ("auto",)],
    "paint-order": [("fill",), ("markers",), ("normal",), ("stroke",)],
    "pause": [
        ("medium",),
        ("none",),
        ("strong",),
        ("weak",),
        ("x-strong",),
        ("x-weak",),
    ]
    + t.time,
    "perspective": [("none",)] + t.length,
    "perspective-origin": t.position,
    "place-content": [("left",), ("normal",), ("right",),]
    + (
        t.baseline_position
        + t.content_distribution
        + t.overflow_position
        + t.content_position
    ),
    "place-items": [
        ("auto",),
        ("center",),
        ("left",),
        ("legacy",),
        ("normal",),
        ("right",),
        ("stretch",),
    ]
    + (t.baseline_position + t.overflow_position + t.self_position),
    "place-self": [("auto",), ("left",), ("normal",), ("right",), ("stretch",),]
    + (t.baseline_position + t.overflow_position + t.self_position),
    "pointer": [("coarse",), ("fine",), ("none",)],
    "pointer-events": [
        ("all",),
        ("bounding-box",),
        ("fill",),
        ("none",),
        ("painted",),
        ("stroke",),
        ("visible",),
        ("visibleFill",),
        ("visiblePainted",),
        ("visibleStroke",),
    ],
    "polar-anchor": t.position,
    "polar-angle": t.angle,
    "polar-distance": [("contain",)] + (t.extent_keyword + t.length + t.percentage),
    "polar-origin": [("auto",)] + t.position,
    "position": [("absolute",), ("fixed",), ("relative",), ("static",), ("sticky",),],
    "prefers-color-scheme": [("dark",), ("light",), ("no-preference",)],
    "prefers-contrast": [("high",), ("low",), ("no-preference",)],
    "prefers-reduced-data": [("no-preference",), ("reduced",)],
    "prefers-reduced-motion": [("no-preference",), ("reduced",)],
    "prefers-reduced-transparency": [("no-preference",), ("reduced",)],
    "presentation-level": [("increment",), ("same",)] + t.integer,
    "quotes": [("none",), t.string],
    "region-fragment": [("auto",), ("break",)],
    "resize": [
        ("block",),
        ("both",),
        ("horizontal",),
        ("inline",),
        ("none",),
        ("vertical",),
    ],
    "resolution": [("infinite",)] + t.resolution,
    "rest": [
        ("medium",),
        ("none",),
        ("strong",),
        ("weak",),
        ("x-strong",),
        ("x-weak",),
    ]
    + t.time,
    "rotate": [("none",), ("x",), ("y",), ("z",)] + t.angle + t.number,
    "rotation": t.angle,
    "rotation-point": t.position,
    "row-column-gap": [("normal",)] + t.length + t.percentage,
    "ruby-align": [("center",), ("space-around",), ("space-between",), ("start",),],
    "ruby-merge": [("auto",), ("collapse",), ("separate",)],
    "ruby-position": [("inter-character",), ("over",), ("under",)],
    "running": [t.identifier],
    "scale": [("none",)] + t.number,
    "scan": [("interlace",), ("progressive",)],
    "scripting": [("enabled",), ("initial-only",), ("none",)],
    "scroll-behavior": [("auto",), ("smooth",)],
    "scroll-padding": t.length + t.percentage,
    "scroll-snap-align": [("center",), ("end",), ("none",), ("start",)],
    "scroll-margin": t.length,
    "scroll-snap-stop": [("always",), ("normal",)],
    "scroll-snap-type": [
        ("block",),
        ("both",),
        ("inline",),
        ("mandatory",),
        ("none",),
        ("proximity",),
        ("x",),
        ("y",),
    ],
    "shape-image-threshold": t.number,
    "shape-inside": [("auto",), ("display",), ("outside-shape",), ("shape-box",),]
    + t.basic_shape
    + t.image,
    "shape-margin": t.length + t.percentage,
    "shape-outside": [("none",)] + t.basic_shape + t.image + t.shape_box,
    "shape-rendering": [
        ("auto",),
        ("crispEdges",),
        ("geometricPrecision",),
        ("optimizeSpeed",),
    ],
    "size": [("auto",), ("landscape",), ("portrait",)] + t.page_size + t.length,
    "spatial-navigation-action": [("auto",), ("focus",), ("scroll",)],
    "spatial-navigation-contain": [("auto",), ("contain",)],
    "spatial-navigation-function": [("normal",), ("grid",)],
    "speak": [("always",), ("auto",), ("never",)],
    "speak-as": [
        ("digits",),
        ("literal-punctuation",),
        ("no-punctuation",),
        ("normal",),
        ("spell-out",),
    ],
    "stop-color": t.color,
    "stop-opacity": t.number,
    "string-set": [("none",), t.attr, t.content, t.identifier, t.url,] + t.content_list,
    "stroke": t.background,
    "stroke-align": [("center",), ("inner",), ("outer",)],
    "stroke-alignment": [("center",), ("inner",), ("outer",)],
    "stroke-break": [("bounding-box",), ("clone",), ("slice",)],
    "stroke-color": t.color,
    "stroke-dashadjust": [
        ("compress",),
        ("dashes",),
        ("gaps",),
        ("none",),
        ("stretch",),
    ],
    "stroke-dasharray": [("none",)] + t.dasharray,
    "stroke-dash-corner": [("none",)] + t.length,
    "stroke-dashcorner": [("none",)] + t.length,
    "stroke-dash-justify": [
        ("compress",),
        ("dashes",),
        ("gaps",),
        ("none",),
        ("stretch",),
    ],
    "stroke-dashoffset": t.length + t.percentage,
    "stroke-image": t.paint,
    "stroke-linecap": [("butt",), ("round",), ("square",)],
    "stroke-linejoin": [
        ("arcs",),
        ("bevel",),
        ("crop",),
        ("fallback",),
        ("miter",),
        ("miter-clip",),
        ("round",),
        ("stupid",),
    ],
    "stroke-miterlimit": t.number,
    "stroke-opacity": t.number,
    "stroke-origin": [
        ("border-box",),
        ("content-box",),
        ("fill-box",),
        ("match-parent",),
        ("padding-box",),
        ("stroke-box",),
    ],
    "stroke-position": t.position,
    "stroke-repeat": t.repeat_style,
    "stroke-width": t.length + t.percentage,
    "tab-size": t.length + t.number,
    "table-layout": [("auto",), ("fixed",)],
    "text-align": [
        ("center",),
        ("end",),
        ("justify",),
        ("justify-all",),
        ("left",),
        ("match-parent",),
        ("right",),
        ("start",),
    ],
    "text-align-all": [
        ("center",),
        ("end",),
        ("justify",),
        ("left",),
        ("match-parent",),
        ("right",),
        ("start",),
    ],
    "text-align-last": [
        ("auto",),
        ("center",),
        ("end",),
        ("justify",),
        ("left",),
        ("right",),
        ("start",),
    ],
    "text-anchor": [("end",), ("middle",), ("start",)],
    "text-combine-upright": [("all",), ("none",)] + t.integer,
    "text-decoration": [
        ("blink",),
        ("dashed",),
        ("dotted",),
        ("double",),
        ("line-through",),
        ("none",),
        ("overline",),
        ("solid",),
        ("underline",),
        ("wavy",),
    ]
    + t.color,
    "text-decoration-color": t.color,
    "text-decoration-line": [
        ("blink",),
        ("line-through",),
        ("none",),
        ("overline",),
        ("underline",),
    ],
    "text-decoration-skip": [
        ("box-decoration",),
        ("edges",),
        ("leading-spaces",),
        ("none",),
        ("objects",),
        ("spaces",),
        ("trailing-spaces",),
    ],
    "text-decoration-skip-ink": [("auto",), ("none",),],
    "text-decoration-style": [
        ("dashed",),
        ("dotted",),
        ("double",),
        ("solid",),
        ("wavy",),
    ],
    "text-decoration-width": [("auto",),] + t.length,
    "text-emphasis": [
        ("circle",),
        ("dot",),
        ("double-circle",),
        ("filled",),
        ("none",),
        ("open",),
        ("sesame",),
        ("triangle",),
        t.string,
    ]
    + t.color,
    "text-emphasis-color": t.color,
    "text-emphasis-position": [("left",), ("over",), ("right",), ("under",)],
    "text-emphasis-skip": [("narrow",), ("punctuation",), ("spaces",), ("symbols",),],
    "text-emphasis-style": [
        ("circle",),
        ("dot",),
        ("double-circle",),
        ("filled",),
        ("none",),
        ("open",),
        ("sesame",),
        ("triangle",),
        t.string,
    ],
    "text-indent": [("each-line",), ("hanging",)] + t.length + t.percentage,
    "text-justify": [("auto",), ("inter-character",), ("inter-word",), ("none",),],
    "text-orientation": [("mixed",), ("sideways",), ("upright",)],
    "text-overflow": [("clip",), ("ellipsis",), ("fade",), t.fade, t.string],
    "text-rendering": [
        ("auto",),
        ("geometricPrecision",),
        ("optimizeLegibility",),
        ("optimizeSpeed",),
    ],
    "text-shadow": [("none",)] + t.color + t.length,
    "text-size-adjust": [("auto",), ("none",)] + t.percentage,
    "text-space-collapse": [
        ("collapse",),
        ("discard",),
        ("preserve",),
        ("preserve-auto",),
        ("preserve-breaks",),
        ("preserve-spaces",),
        ("preserve-trim",),
    ],
    "text-space-trim": [
        ("discard-after",),
        ("discard-before",),
        ("none",),
        ("trim-inner",),
    ],
    "text-spacing": [
        ("allow-end",),
        ("ideograph-alpha",),
        ("ideograph-numeric",),
        ("no-compress",),
        ("none",),
        ("normal",),
        ("punctuation",),
        ("space-adjacent",),
        ("space-end",),
        ("space-start",),
        ("trim-adjacent",),
        ("trim-end",),
        ("trim-start",),
    ],
    "text-transform": [
        ("capitalize",),
        ("full-width",),
        ("lowercase",),
        ("none",),
        ("uppercase",),
    ],
    "text-underline-offset": [("auto",)] + t.length,
    "text-underline-position": [("auto",), ("left",), ("right",), ("under",)],
    "text-wrap": [("balance",), ("normal",), ("nowrap",)],
    "top-right-left-bottom": [
        ("auto",),
        ("block-end",),
        ("block-start",),
        ("inline-end",),
        ("inline-start",),
    ]
    + t.length
    + t.percentage,
    "transform": [("none",)] + t.transform_list,
    "transform-box": [("border-box",), ("fill-box",), ("view-box",)],
    "transform-origin": t.position,
    "transform-style": [("flat",), ("preserve-3d",)],
    "transition": t.single_transition,
    "transition-delay": t.time,
    "transition-duration": t.time,
    "transition-property": [("all",), ("none",), t.identifier],
    "transition-timing-function": t.single_timing_function,
    "translate": t.length + t.percentage,
    "unicode-bidi": [
        ("bidi-override",),
        ("embed",),
        ("isolate",),
        ("isolate-override",),
        ("normal",),
        ("plaintext",),
    ],
    "update": [("fast",), ("none",), ("slow",)],
    "user-select": [("all",), ("auto",), ("contain",), ("none",), ("text",)],
    "vector-effect": [("non-scaling-stroke",), ("none",)],
    "vertical-align": [
        ("alphabetic",),
        ("baseline",),
        ("bottom",),
        ("center",),
        ("central",),
        ("ideographic",),
        ("mathematical",),
        ("middle",),
        ("text-bottom",),
        ("text-top",),
        ("top",),
    ]
    + t.baseline_shift,
    "visibility": [("collapse",), ("hidden",), ("visible",)],
    "voice-balance": [
        ("center",),
        ("left",),
        ("leftwards",),
        ("right",),
        ("rightwards",),
    ]
    + t.number,
    "voice-duration": [("auto",)] + t.time,
    "voice-family": [("preserve",)] + t.generic_voice + t.voice_name,
    "voice-range-pitch": [
        ("absolute",),
        ("high",),
        ("low",),
        ("medium",),
        ("x-high",),
        ("x-low",),
    ]
    + t.frequency
    + t.percentage
    + t.semitones,
    "voice-rate": [
        ("fast",),
        ("medium",),
        ("normal",),
        ("slow",),
        ("x-fast",),
        ("x-slow",),
    ]
    + t.percentage,
    "voice-stress": [("moderate",), ("none",), ("normal",), ("reduced",), ("strong",),],
    "voice-volume": [
        ("loud",),
        ("medium",),
        ("silent",),
        ("soft",),
        ("x-loud",),
        ("x-soft",),
    ]
    + t.decibel,
    "white-space": [
        ("normal",),
        ("nowrap",),
        ("pre",),
        ("pre-line",),
        ("pre-wrap",),
        ("pre-wrap-auto",),
    ],
    "widows-orphans": t.integer,
    "width": [
        ("auto",),
        ("fill",),
        ("fit-content",),
        ("max-content",),
        ("min-content",),
        ("none",),
    ]
    + t.length
    + t.percentage,
    # width-height is a media-feature. Do not confuse it with the width and
    # height properties.
    "width-height": t.length,
    "will-change": [("auto",)] + t.animateable_feature,
    "word-break": [("break-all",), ("keep-all",), ("normal",)],
    "word-spacing": [("normal",)] + t.length + t.percentage,
    "word-wrap": [("break-word",), ("normal",)],
    "wrap-before-after": [
        ("auto",),
        ("avoid",),
        ("avoid-flex",),
        ("avoid-line",),
        ("flex",),
        ("line",),
    ],
    "wrap-flow": [
        ("auto",),
        ("both",),
        ("clear",),
        ("end",),
        ("maximum",),
        ("minimum",),
        ("start",),
    ],
    "wrap-inside": [("auto",), ("avoid",)],
    "wrap-through": [("none",), ("wrap",)],
    "writing-mode": [
        ("horizontal-tb",),
        ("vertical-lr",),
        ("vertical-rl",),
    ],
    "z-index": [("auto",)] + t.integer,
}


allow_word_completions = frozenset(
    (
        "animation",
        "animation-name",
        "chains",
        "composes",
        "counter-set-reset-increment",
        "custom",
        "flow",
        "flow-from",
        "flow-into",
        "font",
        "font-palette",
        "grid-row-column-area",
        "list-style",
        "list-style-type",
        "nav-up-right-left-down",
        "page",
        "running",
        "string-set",
        "transition",
        "transition-property",
        "voice-family",
        "will-change",
    )
)


def get_values(property_name):
    completions = name_to_completions.get(property_name, []) + [t.var]

    if property_name in allow_word_completions:
        return completions

    return completions, sublime.INHIBIT_WORD_COMPLETIONS


def sort_and_uniq_completions():
    for name in name_to_completions:
        name_to_completions[name] = list(set(name_to_completions[name]))
        name_to_completions[name].sort()


sort_and_uniq_completions()

# This is identical to the property names list, except that it does not insert
# the trailing semicolon.
supports_conditions = []


def populate_supports_conditions_list():
    """Populate the completions list for @supports conditions.

    An @supports condition is looks like this: (display: flex). All the property
    names should be offered as completions, but the inserted text should not
    have a trailing semicolon.
    """
    global supports_conditions
    old_suffix = r"${1};"
    new_suffix = r"${0}"

    for label, completion in names:
        # strip trailing semicolon and replace ${1} with ${0}
        if completion.endswith(old_suffix):
            completion = completion[: -len(old_suffix)] + new_suffix
        supports_conditions.append((label, completion))


populate_supports_conditions_list()
