from CSS3.completions import values as v


names = [
    ("-moz-box-sizing", "-moz-box-sizing: ${0};"),
    ("-moz-column-count", "-moz-column-count: ${0};"),
    ("-moz-column-fill", "-moz-column-fill: ${0};"),
    ("-moz-column-gap", "-moz-column-gap: ${0};"),
    ("-moz-column-rule", "-moz-column-rule: ${0};"),
    ("-moz-column-rule-color", "-moz-column-rule-color: ${0};"),
    ("-moz-column-rule-style", "-moz-column-rule-style: ${0};"),
    ("-moz-column-rule-width", "-moz-column-rule-width: ${0};"),
    ("-moz-column-span", "-moz-column-span: ${0};"),
    ("-moz-column-width", "-moz-column-width: ${0};"),
    ("-moz-columns", "-moz-columns: ${0};"),
    ("-moz-font-feature-settings", "-moz-font-feature-settings: ${0};"),
    ("-moz-font-language-override", "-moz-font-language-override: ${0};"),
    ("-moz-hyphens", "-moz-hyphens: ${0};"),
    ("-moz-tab-size", "-moz-tab-size: ${0};"),
    ("-moz-text-align-last", "-moz-text-align-last: ${0};"),
    ("-moz-text-decoration-color", "-moz-text-decoration-color: ${0};"),
    ("-moz-text-decoration-line", "-moz-text-decoration-line: ${0};"),
    ("-moz-text-decoration-skip", "-moz-text-decoration-skip: ${0};"),
    ("-moz-text-decoration-style", "-moz-text-decoration-style: ${0};"),
    ("-moz-user-select", "-moz-user-select: ${0};"),
    ("-ms-backface-visibility", "-ms-backface-visibility: ${0};"),
    ("-ms-flex", "-ms-flex: ${0};"),
    ("-ms-flex-direction", "-ms-flex-direction: ${0};"),
    ("-ms-flex-flow", "-ms-flex-flow: ${0};"),
    ("-ms-flex-wrap", "-ms-flex-wrap: ${0};"),
    ("-ms-flow-from", "-ms-flow-from: ${0};"),
    ("-ms-flow-into", "-ms-flow-into: ${0};"),
    ("-ms-grid-column", "-ms-grid-column: ${0};"),
    ("-ms-grid-row", "-ms-grid-row: ${0};"),
    ("-ms-hyphens", "-ms-hyphens: ${0};"),
    ("-ms-overflow-x", "-ms-overflow-x: ${0};"),
    ("-ms-overflow-y", "-ms-overflow-y: ${0};"),
    ("-ms-perspective", "-ms-perspective: ${0};"),
    ("-ms-perspective-origin", "-ms-perspective-origin: ${0};"),
    ("-ms-scroll-snap-type", "-ms-scroll-snap-type: ${0};"),
    ("-ms-text-align-last", "-ms-text-align-last: ${0};"),
    ("-ms-text-justify", "-ms-text-justify: ${0};"),
    ("-ms-transform", "-ms-transform: ${0};"),
    ("-ms-transform-origin", "-ms-transform-origin: ${0};"),
    ("-ms-transform-style", "-ms-transform-style: ${0};"),
    ("-ms-user-select", "-ms-user-select: ${0};"),
    ("-ms-word-wrap", "-ms-word-wrap: ${0};"),
    ("-ms-wrap-flow", "-ms-wrap-flow: ${0};"),
    ("-ms-wrap-through", "-ms-wrap-through: ${0};"),
    ("-ms-writing-mode", "-ms-writing-mode: ${0};"),
    ("-webkit-align-content", "-webkit-align-content: ${0};"),
    ("-webkit-align-items", "-webkit-align-items: ${0};"),
    ("-webkit-align-self", "-webkit-align-self: ${0};"),
    ("-webkit-animation", "-webkit-animation: ${0};"),
    ("-webkit-animation-delay", "-webkit-animation-delay: ${0};"),
    ("-webkit-animation-direction", "-webkit-animation-direction: ${0};"),
    ("-webkit-animation-duration", "-webkit-animation-duration: ${0};"),
    ("-webkit-animation-fill-mode", "-webkit-animation-fill-mode: ${0};"),
    ("-webkit-animation-iteration-count", "-webkit-animation-iteration-count: ${0};"),
    ("-webkit-animation-name", "-webkit-animation-name: ${0};"),
    ("-webkit-animation-play-state", "-webkit-animation-play-state: ${0};"),
    ("-webkit-animation-timing-function", "-webkit-animation-timing-function: ${0};"),
    ("-webkit-backface-visibility", "-webkit-backface-visibility: ${0};"),
    ("-webkit-border-image", "-webkit-border-image: ${0};"),
    ("-webkit-box-decoration-break", "-webkit-box-decoration-break: ${0};"),
    ("-webkit-break-after", "-webkit-break-after: ${0};"),
    ("-webkit-break-before", "-webkit-break-before: ${0};"),
    ("-webkit-break-inside", "-webkit-break-inside: ${0};"),
    ("-webkit-clip-path", "-webkit-clip-path: ${0};"),
    ("-webkit-column-count", "-webkit-column-count: ${0};"),
    ("-webkit-column-fill", "-webkit-column-fill: ${0};"),
    ("-webkit-column-gap", "-webkit-column-gap: ${0};"),
    ("-webkit-column-rule", "-webkit-column-rule: ${0};"),
    ("-webkit-column-rule-color", "-webkit-column-rule-color: ${0};"),
    ("-webkit-column-rule-style", "-webkit-column-rule-style: ${0};"),
    ("-webkit-column-rule-width", "-webkit-column-rule-width: ${0};"),
    ("-webkit-column-span", "-webkit-column-span: ${0};"),
    ("-webkit-column-width", "-webkit-column-width: ${0};"),
    ("-webkit-columns", "-webkit-columns: ${0};"),
    ("-webkit-filter", "-webkit-filter: ${0};"),
    ("-webkit-flex", "-webkit-flex: ${0};"),
    ("-webkit-flex-basis", "-webkit-flex-basis: ${0};"),
    ("-webkit-flex-direction", "-webkit-flex-direction: ${0};"),
    ("-webkit-flex-flow", "-webkit-flex-flow: ${0};"),
    ("-webkit-flex-grow", "-webkit-flex-grow: ${0};"),
    ("-webkit-flex-shrink", "-webkit-flex-shrink: ${0};"),
    ("-webkit-flex-wrap", "-webkit-flex-wrap: ${0};"),
    ("-webkit-flow-from", "-webkit-flow-from: ${0};"),
    ("-webkit-flow-into", "-webkit-flow-into: ${0};"),
    ("-webkit-font-feature-settings", "-webkit-font-feature-settings: ${0};"),
    ("-webkit-font-kerning", "-webkit-font-kerning: ${0};"),
    ("-webkit-font-variant-ligatures", "-webkit-font-variant-ligatures: ${0};"),
    ("-webkit-grid", "-webkit-grid: ${0};"),
    ("-webkit-grid-area", "-webkit-grid-area: ${0};"),
    ("-webkit-grid-auto-columns", "-webkit-grid-auto-columns: ${0};"),
    ("-webkit-grid-auto-flow", "-webkit-grid-auto-flow: ${0};"),
    ("-webkit-grid-auto-rows", "-webkit-grid-auto-rows: ${0};"),
    ("-webkit-grid-column", "-webkit-grid-column: ${0};"),
    ("-webkit-grid-column-end", "-webkit-grid-column-end: ${0};"),
    ("-webkit-grid-column-start", "-webkit-grid-column-start: ${0};"),
    ("-webkit-grid-row", "-webkit-grid-row: ${0};"),
    ("-webkit-grid-row-end", "-webkit-grid-row-end: ${0};"),
    ("-webkit-grid-row-start", "-webkit-grid-row-start: ${0};"),
    ("-webkit-grid-template", "-webkit-grid-template: ${0};"),
    ("-webkit-grid-template-areas", "-webkit-grid-template-areas: ${0};"),
    ("-webkit-grid-template-columns", "-webkit-grid-template-columns: ${0};"),
    ("-webkit-grid-template-rows", "-webkit-grid-template-rows: ${0};"),
    ("-webkit-hyphens", "-webkit-hyphens: ${0};"),
    ("-webkit-justify-content", "-webkit-justify-content: ${0};"),
    ("-webkit-justify-self", "-webkit-justify-self: ${0};"),
    ("-webkit-order", "-webkit-order: ${0};"),
    ("-webkit-perspective", "-webkit-perspective: ${0};"),
    ("-webkit-perspective-origin", "-webkit-perspective-origin: ${0};"),
    ("-webkit-region-fragment", "-webkit-region-fragment: ${0};"),
    ("-webkit-ruby-position", "-webkit-ruby-position: ${0};"),
    ("-webkit-shape-image-threshold", "-webkit-shape-image-threshold: ${0};"),
    ("-webkit-shape-margin", "-webkit-shape-margin: ${0};"),
    ("-webkit-shape-outside", "-webkit-shape-outside: ${0};"),
    ("-webkit-text-decoration-color", "-webkit-text-decoration-color: ${0};"),
    ("-webkit-text-decoration-line", "-webkit-text-decoration-line: ${0};"),
    ("-webkit-text-decoration-skip", "-webkit-text-decoration-skip: ${0};"),
    ("-webkit-text-decoration-style", "-webkit-text-decoration-style: ${0};"),
    ("-webkit-text-emphasis", "-webkit-text-emphasis: ${0};"),
    ("-webkit-text-emphasis-color", "-webkit-text-emphasis-color: ${0};"),
    ("-webkit-text-emphasis-position", "-webkit-text-emphasis-position: ${0};"),
    ("-webkit-text-emphasis-style", "-webkit-text-emphasis-style: ${0};"),
    ("-webkit-text-orientation", "-webkit-text-orientation: ${0};"),
    ("-webkit-transform", "-webkit-transform: ${0};"),
    ("-webkit-transform-origin", "-webkit-transform-origin: ${0};"),
    ("-webkit-transform-style", "-webkit-transform-style: ${0};"),
    ("-webkit-transition", "-webkit-transition: ${0};"),
    ("-webkit-transition-delay", "-webkit-transition-delay: ${0};"),
    ("-webkit-transition-duration", "-webkit-transition-duration: ${0};"),
    ("-webkit-transition-property", "-webkit-transition-property: ${0};"),
    ("-webkit-transition-timing-function", "-webkit-transition-timing-function: ${0};"),
    ("-webkit-user-select", "-webkit-user-select: ${0};"),
    ("-webkit-writing-mode", "-webkit-writing-mode: ${0};"),
    ("additive-symbols", "additive-symbols: ${0};"),
    ("align-content", "align-content: ${0};"),
    ("align-items", "align-items: ${0};"),
    ("align-self", "align-self: ${0};"),
    ("alignment", "alignment: ${0};"),
    ("alignment-adjust", "alignment-adjust: ${0};"),
    ("alignment-baseline", "alignment-baseline: ${0};"),
    ("all", "all: ${0};"),
    ("animation", "animation: ${0};"),
    ("animation-delay", "animation-delay: ${0};"),
    ("animation-direction", "animation-direction: ${0};"),
    ("animation-duration", "animation-duration: ${0};"),
    ("animation-fill-mode", "animation-fill-mode: ${0};"),
    ("animation-iteration-count", "animation-iteration-count: ${0};"),
    ("animation-name", "animation-name: ${0};"),
    ("animation-play-state", "animation-play-state: ${0};"),
    ("animation-timing-function", "animation-timing-function: ${0};"),
    ("backface-visibility", "backface-visibility: ${0};"),
    ("background", "background: ${0};"),
    ("background-attachment", "background-attachment: ${0};"),
    ("background-blend-mode", "background-blend-mode: ${0};"),
    ("background-clip", "background-clip: ${0};"),
    ("background-color", "background-color: ${0};"),
    ("background-image", "background-image: ${0};"),
    ("background-origin", "background-origin: ${0};"),
    ("background-position", "background-position: ${0};"),
    ("background-repeat", "background-repeat: ${0};"),
    ("background-size", "background-size: ${0};"),
    ("baseline-shift", "baseline-shift: ${0};"),
    ("bleed", "bleed: ${0};"),
    ("bookmark-label", "bookmark-label: ${0};"),
    ("bookmark-level", "bookmark-level: ${0};"),
    ("bookmark-state", "bookmark-state: ${0};"),
    ("border", "border: ${0};"),
    ("border-bottom", "border-bottom: ${0};"),
    ("border-bottom-color", "border-bottom-color: ${0};"),
    ("border-bottom-left-radius", "border-bottom-left-radius: ${0};"),
    ("border-bottom-right-radius", "border-bottom-right-radius: ${0};"),
    ("border-bottom-style", "border-bottom-style: ${0};"),
    ("border-bottom-width", "border-bottom-width: ${0};"),
    ("border-boundary", "border-boundary: ${0};"),
    ("border-clip", "border-clip: ${0};"),
    ("border-clip-bottom", "border-clip-bottom: ${0};"),
    ("border-clip-left", "border-clip-left: ${0};"),
    ("border-clip-right", "border-clip-right: ${0};"),
    ("border-clip-top", "border-clip-top: ${0};"),
    ("border-collapse", "border-collapse: ${0};"),
    ("border-color", "border-color: ${0};"),
    ("border-image", "border-image: ${0};"),
    ("border-image-outset", "border-image-outset: ${0};"),
    ("border-image-repeat", "border-image-repeat: ${0};"),
    ("border-image-slice", "border-image-slice: ${0};"),
    ("border-image-source", "border-image-source: ${0};"),
    ("border-image-width", "border-image-width: ${0};"),
    ("border-left", "border-left: ${0};"),
    ("border-left-color", "border-left-color: ${0};"),
    ("border-left-style", "border-left-style: ${0};"),
    ("border-left-width", "border-left-width: ${0};"),
    ("border-limit", "border-limit: ${0};"),
    ("border-radius", "border-radius: ${0};"),
    ("border-right", "border-right: ${0};"),
    ("border-right-color", "border-right-color: ${0};"),
    ("border-right-style", "border-right-style: ${0};"),
    ("border-right-width", "border-right-width: ${0};"),
    ("border-spacing", "border-spacing: ${0};"),
    ("border-style", "border-style: ${0};"),
    ("border-top", "border-top: ${0};"),
    ("border-top-color", "border-top-color: ${0};"),
    ("border-top-left-radius", "border-top-left-radius: ${0};"),
    ("border-top-right-radius", "border-top-right-radius: ${0};"),
    ("border-top-style", "border-top-style: ${0};"),
    ("border-top-width", "border-top-width: ${0};"),
    ("border-width", "border-width: ${0};"),
    ("bottom", "bottom: ${0};"),
    ("box-decoration-break", "box-decoration-break: ${0};"),
    ("box-shadow", "box-shadow: ${0};"),
    ("box-sizing", "box-sizing: ${0};"),
    ("box-snap", "box-snap: ${0};"),
    ("box-suppress", "box-suppress: ${0};"),
    ("break-after", "break-after: ${0};"),
    ("break-before", "break-before: ${0};"),
    ("break-inside", "break-inside: ${0};"),
    ("caption-side", "caption-side: ${0};"),
    ("caret", "caret: ${0};"),
    ("caret-color", "caret-color: ${0};"),
    ("caret-shape", "caret-shape: ${0};"),
    ("chains", "chains: ${0};"),
    ("child-align", "child-align: ${0};"),
    ("clear", "clear: ${0};"),
    ("clear-after", "clear-after: ${0};"),
    ("clear-side", "clear-side: ${0};"),
    ("clip-path", "clip-path: ${0};"),
    ("clip-rule", "clip-rule: ${0};"),
    ("color", "color: ${0};"),
    ("color-adjust", "color-adjust: ${0};"),
    ("color-correction", "color-correction: ${0};"),
    ("color-interpolation", "color-interpolation: ${0};"),
    ("color-interpolation-filters", "color-interpolation-filters: ${0};"),
    ("color-rendering", "color-rendering: ${0};"),
    ("column-count", "column-count: ${0};"),
    ("column-fill", "column-fill: ${0};"),
    ("column-gap", "column-gap: ${0};"),
    ("column-rule", "column-rule: ${0};"),
    ("column-rule-color", "column-rule-color: ${0};"),
    ("column-rule-style", "column-rule-style: ${0};"),
    ("column-rule-width", "column-rule-width: ${0};"),
    ("column-span", "column-span: ${0};"),
    ("column-width", "column-width: ${0};"),
    ("columns", "columns: ${0};"),
    ("contain", "contain: ${0};"),
    ("content", "content: ${0};"),
    ("corner-shape", "corner-shape: ${0};"),
    ("corners", "corners: ${0};"),
    ("counter-increment", "counter-increment: ${0};"),
    ("counter-reset", "counter-reset: ${0};"),
    ("counter-set", "counter-set: ${0};"),
    ("cue", "cue: ${0};"),
    ("cue-after", "cue-after: ${0};"),
    ("cue-before", "cue-before: ${0};"),
    ("cursor", "cursor: ${0};"),
    ("cx", "cx: ${0};"),
    ("cy", "cy: ${0};"),
    ("d", "d: ${0};"),
    ("direction", "direction: ${0};"),
    ("display", "display: ${0};"),
    ("display-inside", "display-inside: ${0};"),
    ("display-list", "display-list: ${0};"),
    ("display-outside", "display-outside: ${0};"),
    ("dominant-baseline", "dominant-baseline: ${0};"),
    ("empty-cells", "empty-cells: ${0};"),
    ("fallback", "fallback: ${0};"),
    ("fill", "fill: ${0};"),
    ("fill-opacity", "fill-opacity: ${0};"),
    ("fill-rule", "fill-rule: ${0};"),
    ("filter", "filter: ${0};"),
    ("flex", "flex: ${0};"),
    ("flex-basis", "flex-basis: ${0};"),
    ("flex-direction", "flex-direction: ${0};"),
    ("flex-flow", "flex-flow: ${0};"),
    ("flex-grow", "flex-grow: ${0};"),
    ("flex-shrink", "flex-shrink: ${0};"),
    ("flex-wrap", "flex-wrap: ${0};"),
    ("float", "float: ${0};"),
    ("float-defer", "float-defer: ${0};"),
    ("float-displace", "float-displace: ${0};"),
    ("float-offset", "float-offset: ${0};"),
    ("float-reference", "float-reference: ${0};"),
    ("float-wrap", "float-wrap: ${0};"),
    ("flood-color", "flood-color: ${0};"),
    ("flood-opacity", "flood-opacity: ${0};"),
    ("flow", "flow: ${0};"),
    ("flow-from", "flow-from: ${0};"),
    ("flow-into", "flow-into: ${0};"),
    ("font", "font: ${0};"),
    ("font-family", "font-family: ${0};"),
    ("font-feature-settings", "font-feature-settings: ${0};"),
    ("font-kerning", "font-kerning: ${0};"),
    ("font-language-override", "font-language-override: ${0};"),
    ("font-size", "font-size: ${0};"),
    ("font-size-adjust", "font-size-adjust: ${0};"),
    ("font-stretch", "font-stretch: ${0};"),
    ("font-style", "font-style: ${0};"),
    ("font-synthesis", "font-synthesis: ${0};"),
    ("font-variant", "font-variant: ${0};"),
    ("font-variant-alternates", "font-variant-alternates: ${0};"),
    ("font-variant-caps", "font-variant-caps: ${0};"),
    ("font-variant-east-asian", "font-variant-east-asian: ${0};"),
    ("font-variant-ligatures", "font-variant-ligatures: ${0};"),
    ("font-variant-numeric", "font-variant-numeric: ${0};"),
    ("font-variant-position", "font-variant-position: ${0};"),
    ("font-weight", "font-weight: ${0};"),
    ("footnote-display", "footnote-display: ${0};"),
    ("footnote-policy", "footnote-policy: ${0};"),
    ("grid", "grid: ${0};"),
    ("grid-area", "grid-area: ${0};"),
    ("grid-auto-columns", "grid-auto-columns: ${0};"),
    ("grid-auto-flow", "grid-auto-flow: ${0};"),
    ("grid-auto-rows", "grid-auto-rows: ${0};"),
    ("grid-column", "grid-column: ${0};"),
    ("grid-column-end", "grid-column-end: ${0};"),
    ("grid-column-gap", "grid-column-gap: ${0};"),
    ("grid-column-start", "grid-column-start: ${0};"),
    ("grid-gap", "grid-gap: ${0};"),
    ("grid-row", "grid-row: ${0};"),
    ("grid-row-end", "grid-row-end: ${0};"),
    ("grid-row-gap", "grid-row-gap: ${0};"),
    ("grid-row-start", "grid-row-start: ${0};"),
    ("grid-template", "grid-template: ${0};"),
    ("grid-template-areas", "grid-template-areas: ${0};"),
    ("grid-template-columns", "grid-template-columns: ${0};"),
    ("grid-template-rows", "grid-template-rows: ${0};"),
    ("hanging-punctuation", "hanging-punctuation: ${0};"),
    ("height", "height: ${0};"),
    ("hyphenate-character", "hyphenate-character: ${0};"),
    ("hyphenate-limit-chars", "hyphenate-limit-chars: ${0};"),
    ("hyphenate-limit-last", "hyphenate-limit-last: ${0};"),
    ("hyphenate-limit-lines", "hyphenate-limit-lines: ${0};"),
    ("hyphenate-limit-zone", "hyphenate-limit-zone: ${0};"),
    ("hyphens", "hyphens: ${0};"),
    ("image-orientation", "image-orientation: ${0};"),
    ("image-rendering", "image-rendering: ${0};"),
    ("image-resolution", "image-resolution: ${0};"),
    ("indent-edge-reset", "indent-edge-reset: ${0};"),
    ("initial-letter", "initial-letter: ${0};"),
    ("initial-letter-align", "initial-letter-align: ${0};"),
    ("initial-letter-wrap", "initial-letter-wrap: ${0};"),
    ("inline-box-align", "inline-box-align: ${0};"),
    ("inline-size", "inline-size: ${0};"),
    ("isolation", "isolation: ${0};"),
    ("justify-content", "justify-content: ${0};"),
    ("justify-items", "justify-items: ${0};"),
    ("justify-self", "justify-self: ${0};"),
    ("left", "left: ${0};"),
    ("letter-spacing", "letter-spacing: ${0};"),
    ("lighting-color", "lighting-color: ${0};"),
    ("line-break", "line-break: ${0};"),
    ("line-grid", "line-grid: ${0};"),
    ("line-height", "line-height: ${0};"),
    ("line-snap", "line-snap: ${0};"),
    ("line-stacking", "line-stacking: ${0};"),
    ("line-stacking-ruby", "line-stacking-ruby: ${0};"),
    ("line-stacking-shift", "line-stacking-shift: ${0};"),
    ("line-stacking-strategy", "line-stacking-strategy: ${0};"),
    ("list-style", "list-style: ${0};"),
    ("list-style-image", "list-style-image: ${0};"),
    ("list-style-position", "list-style-position: ${0};"),
    ("list-style-type", "list-style-type: ${0};"),
    ("margin", "margin: ${0};"),
    ("margin-bottom", "margin-bottom: ${0};"),
    ("margin-left", "margin-left: ${0};"),
    ("margin-right", "margin-right: ${0};"),
    ("margin-top", "margin-top: ${0};"),
    ("marker", "marker: ${0};"),
    ("marker-end", "marker-end: ${0};"),
    ("marker-mid", "marker-mid: ${0};"),
    ("marker-side", "marker-side: ${0};"),
    ("marker-start", "marker-start: ${0};"),
    ("marks", "marks: ${0};"),
    ("mask", "mask: ${0};"),
    ("mask-border", "mask-border: ${0};"),
    ("mask-border-mode", "mask-border-mode: ${0};"),
    ("mask-border-outset", "mask-border-outset: ${0};"),
    ("mask-border-repeat", "mask-border-repeat: ${0};"),
    ("mask-border-slice", "mask-border-slice: ${0};"),
    ("mask-border-source", "mask-border-source: ${0};"),
    ("mask-border-width", "mask-border-width: ${0};"),
    ("mask-clip", "mask-clip: ${0};"),
    ("mask-composite", "mask-composite: ${0};"),
    ("mask-image", "mask-image: ${0};"),
    ("mask-mode", "mask-mode: ${0};"),
    ("mask-origin", "mask-origin: ${0};"),
    ("mask-position", "mask-position: ${0};"),
    ("mask-repeat", "mask-repeat: ${0};"),
    ("mask-size", "mask-size: ${0};"),
    ("mask-type", "mask-type: ${0};"),
    ("max-height", "max-height: ${0};"),
    ("max-lines", "max-lines: ${0};"),
    ("max-width", "max-width: ${0};"),
    ("max-zoom", "max-zoom: ${0};"),
    ("min-height", "min-height: ${0};"),
    ("min-width", "min-width: ${0};"),
    ("min-zoom", "min-zoom: ${0};"),
    ("mix-blend-mode", "mix-blend-mode: ${0};"),
    ("motion", "motion: ${0};"),
    ("motion-offset", "motion-offset: ${0};"),
    ("motion-path", "motion-path: ${0};"),
    ("motion-rotation", "motion-rotation: ${0};"),
    ("nav-down", "nav-down: ${0};"),
    ("nav-left", "nav-left: ${0};"),
    ("nav-right", "nav-right: ${0};"),
    ("nav-up", "nav-up: ${0};"),
    ("negative", "negative: ${0};"),
    ("object-fit", "object-fit: ${0};"),
    ("object-position", "object-position: ${0};"),
    ("offset-after", "offset-after: ${0};"),
    ("offset-before", "offset-before: ${0};"),
    ("offset-end", "offset-end: ${0};"),
    ("offset-start", "offset-start: ${0};"),
    ("opacity", "opacity: ${0};"),
    ("order", "order: ${0};"),
    ("orientation", "orientation: ${0};"),
    ("orphans", "orphans: ${0};"),
    ("outline", "outline: ${0};"),
    ("outline-color", "outline-color: ${0};"),
    ("outline-offset", "outline-offset: ${0};"),
    ("outline-style", "outline-style: ${0};"),
    ("outline-width", "outline-width: ${0};"),
    ("overflow", "overflow: ${0};"),
    ("overflow-style", "overflow-style: ${0};"),
    ("overflow-wrap", "overflow-wrap: ${0};"),
    ("overflow-x", "overflow-x: ${0};"),
    ("overflow-y", "overflow-y: ${0};"),
    ("pad", "pad: ${0};"),
    ("padding", "padding: ${0};"),
    ("padding-bottom", "padding-bottom: ${0};"),
    ("padding-left", "padding-left: ${0};"),
    ("padding-right", "padding-right: ${0};"),
    ("padding-top", "padding-top: ${0};"),
    ("page", "page: ${0};"),
    ("page-policy", "page-policy: ${0};"),
    ("paint-order", "paint-order: ${0};"),
    ("pause", "pause: ${0};"),
    ("pause-after", "pause-after: ${0};"),
    ("pause-before", "pause-before: ${0};"),
    ("perspective", "perspective: ${0};"),
    ("perspective-origin", "perspective-origin: ${0};"),
    ("pointer-events", "pointer-events: ${0};"),
    ("polar-anchor", "polar-anchor: ${0};"),
    ("polar-angle", "polar-angle: ${0};"),
    ("polar-distance", "polar-distance: ${0};"),
    ("polar-origin", "polar-origin: ${0};"),
    ("position", "position: ${0};"),
    ("prefix", "prefix: ${0};"),
    ("quotes", "quotes: ${0};"),
    ("r", "r: ${0};"),
    ("range", "range: ${0};"),
    ("region-fragment", "region-fragment: ${0};"),
    ("resize", "resize: ${0};"),
    ("resolution", "resolution: ${0};"),
    ("rest", "rest: ${0};"),
    ("rest-after", "rest-after: ${0};"),
    ("rest-before", "rest-before: ${0};"),
    ("right", "right: ${0};"),
    ("rotation", "rotation: ${0};"),
    ("rotation-point", "rotation-point: ${0};"),
    ("ruby-align", "ruby-align: ${0};"),
    ("ruby-merge", "ruby-merge: ${0};"),
    ("ruby-position", "ruby-position: ${0};"),
    ("running", "running: ${0};"),
    ("rx", "rx: ${0};"),
    ("ry", "ry: ${0};"),
    ("scroll-behavior", "scroll-behavior: ${0};"),
    ("scroll-snap-align", "scroll-snap-align: ${0};"),
    ("scroll-snap-margin", "scroll-snap-margin: ${0};"),
    ("scroll-snap-padding", "scroll-snap-padding: ${0};"),
    ("scroll-snap-type", "scroll-snap-type: ${0};"),
    ("shape-image-threshold", "shape-image-threshold: ${0};"),
    ("shape-inside", "shape-inside: ${0};"),
    ("shape-margin", "shape-margin: ${0};"),
    ("shape-outside", "shape-outside: ${0};"),
    ("shape-padding", "shape-padding: ${0};"),
    ("shape-rendering", "shape-rendering: ${0};"),
    ("shape-subtract", "shape-subtract: ${0};"),
    ("size", "size: ${0};"),
    ("speak", "speak: ${0};"),
    ("speak-as", "speak-as: ${0};"),
    ("src", "src: ${0};"),
    ("stop-color", "stop-color: ${0};"),
    ("stop-opacity", "stop-opacity: ${0};"),
    ("string-set", "string-set: ${0};"),
    ("stroke", "stroke: ${0};"),
    ("stroke-dasharray", "stroke-dasharray: ${0};"),
    ("stroke-dashoffset", "stroke-dashoffset: ${0};"),
    ("stroke-linecap", "stroke-linecap: ${0};"),
    ("stroke-linejoin", "stroke-linejoin: ${0};"),
    ("stroke-miterlimit", "stroke-miterlimit: ${0};"),
    ("stroke-opacity", "stroke-opacity: ${0};"),
    ("stroke-width", "stroke-width: ${0};"),
    ("suffix", "suffix: ${0};"),
    ("symbols", "symbols: ${0};"),
    ("system", "system: ${0};"),
    ("tab-size", "tab-size: ${0};"),
    ("table-layout", "table-layout: ${0};"),
    ("text-align", "text-align: ${0};"),
    ("text-align-last", "text-align-last: ${0};"),
    ("text-anchor", "text-anchor: ${0};"),
    ("text-combine-upright", "text-combine-upright: ${0};"),
    ("text-decoration", "text-decoration: ${0};"),
    ("text-decoration-color", "text-decoration-color: ${0};"),
    ("text-decoration-fill", "text-decoration-fill: ${0};"),
    ("text-decoration-line", "text-decoration-line: ${0};"),
    ("text-decoration-skip", "text-decoration-skip: ${0};"),
    ("text-decoration-stroke", "text-decoration-stroke: ${0};"),
    ("text-decoration-style", "text-decoration-style: ${0};"),
    ("text-emphasis", "text-emphasis: ${0};"),
    ("text-emphasis-color", "text-emphasis-color: ${0};"),
    ("text-emphasis-position", "text-emphasis-position: ${0};"),
    ("text-emphasis-style", "text-emphasis-style: ${0};"),
    ("text-height", "text-height: ${0};"),
    ("text-indent", "text-indent: ${0};"),
    ("text-justify", "text-justify: ${0};"),
    ("text-orientation", "text-orientation: ${0};"),
    ("text-overflow", "text-overflow: ${0};"),
    ("text-rendering", "text-rendering: ${0};"),
    ("text-shadow", "text-shadow: ${0};"),
    ("text-space-collapse", "text-space-collapse: ${0};"),
    ("text-space-trim", "text-space-trim: ${0};"),
    ("text-spacing", "text-spacing: ${0};"),
    ("text-transform", "text-transform: ${0};"),
    ("text-underline-position", "text-underline-position: ${0};"),
    ("text-wrap", "text-wrap: ${0};"),
    ("top", "top: ${0};"),
    ("transform", "transform: ${0};"),
    ("transform-box", "transform-box: ${0};"),
    ("transform-origin", "transform-origin: ${0};"),
    ("transform-style", "transform-style: ${0};"),
    ("transition", "transition: ${0};"),
    ("transition-delay", "transition-delay: ${0};"),
    ("transition-duration", "transition-duration: ${0};"),
    ("transition-property", "transition-property: ${0};"),
    ("transition-timing-function", "transition-timing-function: ${0};"),
    ("unicode-bidi", "unicode-bidi: ${0};"),
    ("unicode-range", "unicode-range: ${0};"),
    ("user-select", "user-select: ${0};"),
    ("user-zoom", "user-zoom: ${0};"),
    ("vector-effect", "vector-effect: ${0};"),
    ("vertical-align", "vertical-align: ${0};"),
    ("visibility", "visibility: ${0};"),
    ("voice-balance", "voice-balance: ${0};"),
    ("voice-duration", "voice-duration: ${0};"),
    ("voice-family", "voice-family: ${0};"),
    ("voice-pitch", "voice-pitch: ${0};"),
    ("voice-range", "voice-range: ${0};"),
    ("voice-rate", "voice-rate: ${0};"),
    ("voice-stress", "voice-stress: ${0};"),
    ("voice-volume", "voice-volume: ${0};"),
    ("white-space", "white-space: ${0};"),
    ("widows", "widows: ${0};"),
    ("width", "width: ${0};"),
    ("will-change", "will-change: ${0};"),
    ("word-break", "word-break: ${0};"),
    ("word-spacing", "word-spacing: ${0};"),
    ("word-wrap", "word-wrap: ${0};"),
    ("wrap-after", "wrap-after: ${0};"),
    ("wrap-before", "wrap-before: ${0};"),
    ("wrap-flow", "wrap-flow: ${0};"),
    ("wrap-inside", "wrap-inside: ${0};"),
    ("wrap-through", "wrap-through: ${0};"),
    ("writing-mode", "writing-mode: ${0};"),
    ("x", "x: ${0};"),
    ("y", "y: ${0};"),
    ("z-index", "z-index: ${0};"),
    ("zoom", "zoom: ${0}; "),
]

value_for_name = {
    "-moz-box-sizing": [("border-box",), ("content-box",)],
    "-moz-column-count": [("auto",), v.integer, v.calc],
    "-moz-column-fill": [("auto",), ("balance",), ("balance-all",)],
    "-moz-column-gap": [("normal",), v.length, v.calc],
    "-moz-column-rule": [("medium",), ("thick",), ("thin",), v.length, v.calc] + [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)] + v.color,
    "-moz-column-rule-color": v.color,
    "-moz-column-rule-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "-moz-column-rule-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "-moz-column-span": [("all",), ("none",)],
    "-moz-column-width": [("auto",), v.length, v.calc],
    "-moz-columns": [("auto",), v.integer, v.length, v.calc],
    "-moz-font-feature-settings": [("normal",), ("off",), ("on",), v.integer, v.string, v.calc],
    "-moz-font-language-override": [("normal",), v.string],
    "-moz-hyphens": [("auto",), ("manual",), ("none",)],
    "-moz-tab-size": [v.integer, v.length, v.calc],
    "-moz-text-align-last": [("auto",), ("center",), ("end",), ("justify",), ("left",), ("right",), ("start",)],
    "-moz-text-decoration-color": v.color,
    "-moz-text-decoration-line": [("blink",), ("line-through",), ("none",), ("overline",), ("underline",)],
    "-moz-text-decoration-skip": [("box-decoration",), ("edges",), ("ink",), ("none",), ("objects",), ("spaces",)],
    "-moz-text-decoration-style": [("dashed",), ("dotted",), ("double",), ("solid",), ("wavy",)],
    "-moz-user-select": [("all",), ("auto",), ("contain",), ("none",), ("text",)],
    "-ms-backface-visibility": [("hidden",), ("visible",)],
    "-ms-flex": [("auto",), ("main-size",), ("none",), v.length, v.number, v.percentage, v.calc],
    "-ms-flex-direction": [("column",), ("column-reverse",), ("row",), ("row-reverse",)],
    "-ms-flex-flow": [("column",), ("column-reverse",), ("nowrap",), ("row",), ("row-reverse",), ("wrap",), ("wrap-reverse",)],
    "-ms-flex-wrap": [("nowrap",), ("wrap",), ("wrap-reverse",)],
    "-ms-flow-from": [("inherit",), ("none",), v.ident],
    "-ms-flow-into": [("content",), ("element",), ("none",)],
    "-ms-grid-column": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-ms-grid-row": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-ms-hyphens": [("auto",), ("manual",), ("none",)],
    "-ms-overflow-x": [("auto",), ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)],
    "-ms-overflow-y": [("auto",), ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)],
    "-ms-perspective": [("none",), v.length, v.calc],
    "-ms-perspective-origin": v.position,
    "-ms-scroll-snap-type": [("mandatory",), ("none",), ("proximity",)],
    "-ms-text-align-last": [("auto",), ("center",), ("end",), ("justify",), ("left",), ("right",), ("start",)],
    "-ms-text-justify": [("auto",), ("distribute",), ("inter-word",), ("none",)],
    "-ms-transform": [("none",)] + v.transform,
    "-ms-transform-origin": v.position,
    "-ms-transform-style": [("flat",), ("preserve-3d",)],
    "-ms-user-select": [("all",), ("auto",), ("contain",), ("none",), ("text",)],
    "-ms-word-wrap": [("break-word",), ("normal",)],
    "-ms-wrap-flow": [("auto",), ("both",), ("clear",), ("end",), ("maximum",), ("minimum",), ("start",)],
    "-ms-wrap-through": [("none",), ("wrap",)],
    "-ms-writing-mode": [("horizontal-tb",), ("vertical-lr",), ("vertical-rl",)],
    "-webkit-align-content": [("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("space-around",), ("space-between",), ("space-evenly",), ("start",), ("stretch",), ("unsafe",)],
    "-webkit-align-items": [("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "-webkit-align-self": [("auto",), ("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "-webkit-animation": [("alternate",), ("alternate-reverse",), ("backwards",), ("both",), ("forwards",), ("infinite",), ("none",), ("normal",), ("paused",), ("reverse",), ("running",), v.ident, v.number, v.time, v.calc],
    "-webkit-animation-delay": [v.time, v.calc],
    "-webkit-animation-direction": [("alternate",), ("alternate-reverse",), ("normal",), ("reverse",)],
    "-webkit-animation-duration": [v.time, v.calc],
    "-webkit-animation-fill-mode": [("backwards",), ("both",), ("forwards",), ("none",)],
    "-webkit-animation-iteration-count": [("infinite",), v.number, v.calc],
    "-webkit-animation-name": [("none",), v.ident],
    "-webkit-animation-play-state": [("paused",), ("running",)],
    "-webkit-animation-timing-function": [v.timing_function],
    "-webkit-backface-visibility": [("hidden",), ("visible",)],
    "-webkit-border-image": [("auto",), ("fill",), ("none",), ("repeat",), ("round",), ("space",), ("stretch",), v.length, v.number, v.percentage, v.calc] + v.image,
    "-webkit-box-decoration-break": [("clone",), ("slice",)],
    "-webkit-break-after": [("always",), ("auto",), ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",), ("column",), ("left",), ("page",), ("recto",), ("region",), ("right",), ("verso",)],
    "-webkit-break-before": [("always",), ("auto",), ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",), ("column",), ("left",), ("page",), ("recto",), ("region",), ("right",), ("verso",)],
    "-webkit-break-inside": [("auto",), ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",)],
    "-webkit-clip-path": [("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("none",), ("padding-box",), ("stroke-box",), ("view-box",)] + v.basic_shape,
    "-webkit-column-count": [("auto",), v.integer, v.calc],
    "-webkit-column-fill": [("auto",), ("balance",), ("balance-all",)],
    "-webkit-column-gap": [("normal",), v.length, v.calc],
    "-webkit-column-rule": [("medium",), ("thick",), ("thin",), v.length, v.calc] + [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)] + v.color,
    "-webkit-column-rule-color": v.color,
    "-webkit-column-rule-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "-webkit-column-rule-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "-webkit-column-span": [("all",), ("none",)],
    "-webkit-column-width": [("auto",), v.length, v.calc],
    "-webkit-columns": [("auto",), v.integer, v.length, v.calc],
    "-webkit-flex": [("auto",), ("main-size",), ("none",), v.length, v.number, v.percentage, v.calc],
    "-webkit-flex-basis": [("auto",), ("content",), ("main-size",), v.length, v.percentage, v.calc],
    "-webkit-flex-direction": [("column",), ("column-reverse",), ("row",), ("row-reverse",)],
    "-webkit-flex-flow": [("column",), ("column-reverse",), ("nowrap",), ("row",), ("row-reverse",), ("wrap",), ("wrap-reverse",)],
    "-webkit-flex-grow": [v.number, v.calc],
    "-webkit-flex-shrink": [v.number, v.calc],
    "-webkit-flex-wrap": [("nowrap",), ("wrap",), ("wrap-reverse",)],
    "-webkit-flow-from": [("inherit",), ("none",), v.ident],
    "-webkit-flow-into": [("content",), ("element",), ("none",)],
    "-webkit-font-feature-settings": [("normal",), ("off",), ("on",), v.integer, v.string, v.calc],
    "-webkit-font-kerning": [("auto",), ("none",), ("normal",)],
    "-webkit-font-variant-ligatures": [("common-ligatures",), ("contextual",), ("discretionary-ligatures",), ("historical-ligatures",), ("no-common-ligatures",), ("no-contextual",), ("no-discretionary-ligatures",), ("no-historical-ligatures",), ("none",), ("normal",)],
    "-webkit-grid": [("auto",), ("column",), ("dense",), ("max-content",), ("min-content",), ("none",), ("row",), ("stack",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.string, v.calc, v.minmax, v.repeat],
    "-webkit-grid-area": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-auto-columns": [("auto",), ("max-content",), ("min-content",), v.flex, v.length, v.percentage, v.calc, v.minmax],
    "-webkit-grid-auto-flow": [("column",), ("dense",), ("row",), ("stack",)],
    "-webkit-grid-auto-rows": [("auto",), ("max-content",), ("min-content",), v.flex, v.length, v.percentage, v.calc, v.minmax],
    "-webkit-grid-column": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-column-end": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-column-gap": [v.length, v.calc],
    "-webkit-grid-column-start": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-gap": [v.length, v.calc],
    "-webkit-grid-row": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-row-end": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-row-gap": [v.length, v.calc],
    "-webkit-grid-row-start": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "-webkit-grid-template": [("auto",), ("max-content",), ("min-content",), ("none",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.string, v.calc, v.minmax, v.repeat],
    "-webkit-grid-template-areas": [("none",), v.string],
    "-webkit-grid-template-columns": [("auto",), ("max-content",), ("min-content",), ("none",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.calc, v.minmax, v.repeat],
    "-webkit-grid-template-rows": [("auto",), ("max-content",), ("min-content",), ("none",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.calc, v.minmax, v.repeat],
    "-webkit-hyphens": [("auto",), ("manual",), ("none",)],
    "-webkit-justify-content": [("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("space-around",), ("space-between",), ("space-evenly",), ("start",), ("stretch",), ("unsafe",)],
    "-webkit-justify-self": [("auto",), ("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "-webkit-order": [v.integer, v.calc],
    "-webkit-perspective": [("none",), v.length, v.calc],
    "-webkit-perspective-origin": v.position,
    "-webkit-region-fragment": [("auto",), ("break",)],
    "-webkit-ruby-position": [("inter-character",), ("left",), ("over",), ("right",), ("under",)],
    "-webkit-shape-image-threshold": [v.number, v.calc],
    "-webkit-shape-margin": [v.length, v.percentage, v.calc],
    "-webkit-shape-outside": [("border-box",), ("content-box",), ("margin-box",), ("none",), ("padding-box",), v.circle, v.ellipse, v.inset, v.polygon] + v.image,
    "-webkit-text-decoration-color": v.color,
    "-webkit-text-decoration-line": [("blink",), ("line-through",), ("none",), ("overline",), ("underline",)],
    "-webkit-text-decoration-skip": [("box-decoration",), ("edges",), ("ink",), ("none",), ("objects",), ("spaces",)],
    "-webkit-text-decoration-style": [("dashed",), ("dotted",), ("double",), ("solid",), ("wavy",)],
    "-webkit-text-emphasis": [("circle",), ("dot",), ("double-circle",), ("filled",), ("none",), ("open",), ("sesame",), ("triangle",), v.string] + v.color,
    "-webkit-text-emphasis-color": v.color,
    "-webkit-text-emphasis-position": [("left",), ("over",), ("right",), ("under",)],
    "-webkit-text-emphasis-style": [("circle",), ("dot",), ("double-circle",), ("filled",), ("none",), ("open",), ("sesame",), ("triangle",), v.string],
    "-webkit-text-orientation": [("mixed",), ("sideways",), ("upright",)],
    "-webkit-transform": [("none",)] + v.transform,
    "-webkit-transform-origin": v.position,
    "-webkit-transform-style": [("flat",), ("preserve-3d",)],
    "-webkit-transition": [("all",), ("none",), v.ident, v.time, v.calc] + v.timing_function,
    "-webkit-transition-delay": [v.time, v.calc],
    "-webkit-transition-duration": [v.time, v.calc],
    "-webkit-transition-property": [("all",), ("none",), v.ident],
    "-webkit-transition-timing-function": v.timing_function,
    "-webkit-user-select": [("all",), ("auto",), ("contain",), ("none",), ("text",)],
    "-webkit-writing-mode": [("horizontal-tb",), ("vertical-lr",), ("vertical-rl",)],
    "additive-symbols": [v.integer, v.ident, v.string] + v.image + [v.calc],
    "align-content": [("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("space-around",), ("space-between",), ("space-evenly",), ("start",), ("stretch",), ("unsafe",)],
    "align-items": [("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "align-self": [("auto",), ("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "alignment": [("bottom",), ("center",), ("left",), ("right",), ("top",)],
    "alignment-adjust": [("alphabetic",), ("auto",), ("baseline",), ("central",), ("hanging",), ("ideographic",), ("mathematical",), ("middle",), ("over-edge",), ("text-over-edge",), ("text-under-edge",), ("under-edge",), v.length, v.percentage, v.calc],
    "alignment-baseline": [("alphabetic",), ("baseline",), ("bottom",), ("center",), ("central",), ("mathematical",), ("middle",), ("text-bottom",), ("text-top",), ("top",)],
    "all": v.all_values,
    "animation": [("alternate",), ("alternate-reverse",), ("backwards",), ("both",), ("forwards",), ("infinite",), ("none",), ("normal",), ("paused",), ("reverse",), ("running",), v.ident, v.number, v.time, v.calc],
    "animation-delay": [v.time, v.calc],
    "animation-direction": [("alternate",), ("alternate-reverse",), ("normal",), ("reverse",)],
    "animation-duration": [v.time, v.calc],
    "animation-fill-mode": [("backwards",), ("both",), ("forwards",), ("none",)],
    "animation-iteration-count": [("infinite",), v.number, v.calc],
    "animation-name": [("none",), v.ident],
    "animation-play-state": [("paused",), ("running",)],
    "animation-timing-function": [v.timing_function],
    "backface-visibility": [("hidden",), ("visible",)],
    "background": [("auto",), ("border-box",), ("bottom",), ("center",), ("contain",), ("content-box",), ("cover",), ("fixed",), ("left",), ("local",), ("no-repeat",), ("none",), ("padding-box",), ("repeat",), ("repeat-x",), ("repeat-y",), ("right",), ("round",), ("scroll",), ("space",), ("top",), v.length, v.percentage, v.calc] + v.color + v.image,
    "background-attachment": [("fixed",), ("local",), ("scroll",)],
    "background-blend-mode": [("color",), ("color-burn",), ("color-dodge",), ("darken",), ("difference",), ("exclusion",), ("hard-light",), ("hue",), ("lighten",), ("luminosity",), ("multiply",), ("normal",), ("overlay",), ("saturation",), ("screen",), ("soft-light",)],
    "background-clip": [("border-box",), ("content-box",), ("padding-box",)],
    "background-color": v.color,
    "background-image": [("none",)] + v.image,
    "background-origin": [("border-box",), ("content-box",), ("padding-box",)],
    "background-position": v.position,
    "background-repeat": [("no-repeat",), ("repeat",), ("repeat-x",), ("repeat-y",), ("round",), ("space",)],
    "background-size": [("auto",), ("contain",), ("cover",), v.length, v.percentage, v.calc],
    "baseline-shift": [("sub",), ("super",), v.length, v.percentage, v.calc],
    "bleed": [("auto",), v.length, v.calc],
    "bookmark-label": [("none",), v.string, v.attr, v.content, v.counter, v.counters],
    "bookmark-level": [("none",), v.integer, v.calc],
    "bookmark-state": [("closed",), ("open",)],
    "border": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",), v.length, v.calc] + v.color,
    "border-bottom": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",), v.length, v.calc] + v.color,
    "border-bottom-color": v.color,
    "border-bottom-left-radius": [v.length, v.percentage, v.calc],
    "border-bottom-right-radius": [v.length, v.percentage, v.calc],
    "border-bottom-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "border-bottom-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "border-boundary": [("display",), ("none",), ("parent",)],
    "border-clip": [("normal",), v.length, v.percentage, v.calc],
    "border-clip-bottom": [("normal",), v.length, v.percentage, v.calc],
    "border-clip-left": [("normal",), v.length, v.percentage, v.calc],
    "border-clip-right": [("normal",), v.length, v.percentage, v.calc],
    "border-clip-top": [("normal",), v.length, v.percentage, v.calc],
    "border-collapse": [("collapse",), ("separate",)],
    "border-color": v.color,
    "border-image": [("auto",), ("fill",), ("none",), ("repeat",), ("round",), ("space",), ("stretch",), v.length, v.number, v.percentage, v.calc] + v.image,
    "border-image-outset": [v.length, v.number, v.calc],
    "border-image-repeat": [("repeat",), ("round",), ("space",), ("stretch",)],
    "border-image-slice": [("fill",), v.number, v.percentage, v.calc],
    "border-image-source": [("none",)] + v.image,
    "border-image-width": [("auto",), v.length, v.number, v.percentage, v.calc],
    "border-left": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",), v.length, v.calc] + v.color,
    "border-left-color": v.color,
    "border-left-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "border-left-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "border-limit": [("all",), ("bottom",), ("corners",), ("left",), ("right",), ("sides",), ("top",), v.length, v.percentage, v.calc],
    "border-radius": [v.length, v.percentage, v.calc],
    "border-right": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",), v.length, v.calc] + v.color,
    "border-right-color": v.color,
    "border-right-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "border-right-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "border-spacing": [v.length, v.calc],
    "border-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "border-top": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",), v.length, v.calc] + v.color,
    "border-top-color": v.color,
    "border-top-left-radius": [v.length, v.percentage, v.calc],
    "border-top-right-radius": [v.length, v.percentage, v.calc],
    "border-top-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "border-top-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "border-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "bottom": [("auto",), v.length, v.percentage, v.calc],
    "box-decoration-break": [("clone",), ("slice",)],
    "box-shadow": [("inset",), ("none",), v.length, v.calc] + v.color,
    "box-sizing": [("border-box",), ("content-box",)],
    "box-snap": [("after",), ("before",), ("center",), ("first-baseline",), ("last-baseline",), ("none",)],
    "box-suppress": [("discard",), ("hide",), ("show",)],
    "break-after": [("always",), ("auto",), ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",), ("column",), ("left",), ("page",), ("recto",), ("region",), ("right",), ("verso",)],
    "break-before": [("always",), ("auto",), ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",), ("column",), ("left",), ("page",), ("recto",), ("region",), ("right",), ("verso",)],
    "break-inside": [("auto",), ("avoid",), ("avoid-column",), ("avoid-page",), ("avoid-region",)],
    "caption-side": [("after",), ("before",), ("bottom",), ("left",), ("outside",), ("right",), ("top",)],
    "caret": [("auto"), ("bar",), ("block",), ("underscore",), v.color],
    "caret-color": [("auto"), v.color],
    "caret-shape": [("auto",), ("bar",), ("block",), ("underscore",)],
    "chains": [("none",), v.ident],
    "child-align": [("auto",), ("bottom",), ("left",), ("middle",), ("right",), ("top",)],
    "clear": [("both",), ("left",), ("none",), ("right",)],
    "clear-after": [("both",), ("bottom",), ("descendants",), ("end",), ("inside",), ("left",), ("none",), ("outside",), ("right",), ("start",), ("top",)],
    "clear-side": [("auto",), ("both",)],
    "clip-path": [("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("none",), ("padding-box",), ("stroke-box",), ("view-box",)] + v.basic_shape,
    "clip-rule": [("evenodd",), ("nonzero",)],
    "color": v.color,
    "color-adjust": [("economy",), ("exact",)],
    "color-correction": [("auto",), ("sRGB",)],
    "color-interpolation": [("auto",), ("linearRGB",), ("sRGB",)],
    "color-interpolation-filters": [("auto",), ("linearRGB",), ("sRGB",)],
    "color-rendering": [("auto",), ("optimizeQuality",), ("optimizeSpeed",)],
    "column-count": [("auto",), v.integer, v.calc],
    "column-fill": [("auto",), ("balance",), ("balance-all",)],
    "column-gap": [("normal",), v.length, v.calc],
    "column-rule": [("medium",), ("thick",), ("thin",), v.length, v.calc] + [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)] + v.color,
    "column-rule-color": v.color,
    "column-rule-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "column-rule-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "column-span": [("all",), ("none",)],
    "column-width": [("auto",), v.length, v.calc],
    "columns": [("auto",), v.integer, v.length, v.calc],
    "content": [("close-quote",), ("contents",), ("icon",), ("inhibit",), ("none",), ("normal",), ("no-close-quote",), ("no-open-quote",), ("open-quote",), v.string, v.attr, v.content, v.counter, v.counters, v.url],
    "corner-shape": [("bevel",), ("notch",), ("round",), ("scoop",)],
    "corners": [("bevel",), ("notch",), ("round",), ("scoop",), v.length, v.percentage, v.calc],
    "counter-increment": [("none",), v.ident, v.integer, v.calc],
    "counter-reset": [("none",), v.ident, v.integer, v.calc],
    "counter-set": [("none",), v.ident, v.integer, v.calc],
    "cue": [("none",), v.decibel, v.url],
    "cue-after": [("none",), v.decibel, v.url],
    "cue-before": [("none",), v.decibel, v.url],
    "cursor": [("alias",), ("all-scroll",), ("auto",), ("cell",), ("col-resize",), ("context-menu",), ("copy",), ("crosshair",), ("default",), ("e-resize",), ("ew-resize",), ("help",), ("move",), ("n-resize",), ("ne-resize",), ("nesw-resize",), ("no-drop",), ("none",), ("not-allowed",), ("ns-resize",), ("nw-resize",), ("nwse-resize",), ("pointer",), ("progress",), ("row-resize",), ("s-resize",), ("se-resize",), ("sw-resize",), ("text",), ("vertical-text",), ("w-resize",), ("wait",), ("zoom-in",), ("zoom-out",), v.number, v.url, v.calc],
    "cx": [v.length, v.percentage, v.calc],
    "cy": [v.length, v.percentage, v.calc],
    "d": [("none",), v.d_path],
    "direction": [("ltr",), ("rtl",)],
    "display": [("auto",), ("block",), ("block-level",), ("contents",), ("flex",), ("grid",), ("inline",), ("inline-block",), ("inline-flex",), ("inline-grid",), ("inline-level",), ("inline-list-item",), ("inline-table",), ("list-item",), ("none",), ("ruby",), ("ruby-base",), ("ruby-base-container",), ("ruby-text",), ("ruby-text-container",), ("run-in",), ("table",), ("table-caption",), ("table-cell",), ("table-column",), ("table-column-group",), ("table-footer-group",), ("table-header-group",), ("table-row",), ("table-row-group",)],
    "display-inside": [("auto",), ("block",), ("flex",), ("grid",), ("ruby",), ("table",)],
    "display-list": [("list-item",), ("none",)],
    "display-outside": [("block-level",), ("contents",), ("inline-level",), ("none",), ("ruby-base",), ("ruby-base-container",), ("ruby-text",), ("ruby-text-container",), ("run-in",), ("table-caption",), ("table-cell",), ("table-column",), ("table-column-group",), ("table-footer-group",), ("table-header-group",), ("table-row",), ("table-row-group",)],
    "dominant-baseline": [("alphabetic",), ("auto",), ("central",), ("hanging",), ("mathematical",), ("text-bottom",), ("text-top",)],
    "empty-cells": [("hide",), ("show",)],
    "fallback": [v.ident] + v.counter_style,
    "filter": [("none",), v.url] + v.filters,
    "fill": [("none",), ("context-stroke",), ("context-fill",), ("child",), v.child, v.color],
    "fill-opacity": [v.number, v.calc],
    "fill-rule": [("evenodd",), ("nonzero",)],
    "flex": [("auto",), ("content",), ("none",), v.length, v.number, v.percentage, v.calc],
    "flex-basis": [("auto",), ("content",), v.length, v.percentage, v.calc],
    "flex-direction": [("column",), ("column-reverse",), ("row",), ("row-reverse",)],
    "flex-flow": [("column",), ("column-reverse",), ("nowrap",), ("row",), ("row-reverse",), ("wrap",), ("wrap-reverse",)],
    "flex-grow": [v.number, v.calc],
    "flex-shrink": [v.number, v.calc],
    "flex-wrap": [("nowrap",), ("wrap",), ("wrap-reverse",)],
    "float": [("block-end",), ("block-start",), ("bottom",), ("inline-end",), ("inline-start",), ("left",), ("none",), ("right",), ("snap-block",), ("snap-inline",), ("top",), v.snap_block, v.snap_inline],
    "float": [("bottom",), ("bottom-corner",), ("contour",), ("end",), ("inside",), ("intrude",), ("left",), ("next-column",), ("next-page",), ("none",), ("outside",), ("right",), ("snap",), ("start",), ("top",), ("top-corner",), ("unless-room",)],
    "float-defer": [("last",), ("none",), v.integer, v.calc],
    "float-displace": [("auto",), ("block",), ("block-within-page",)],
    "float-offset": [v.length, v.percentage, v.calc],
    "float-reference": [("column",), ("inline",), ("page",), ("region",)],
    "float-wrap": [("none",), ("wrap",)],
    "flood-color": v.color + [v.icc_color],
    "flood-opacity": [v.number, v.percentage, v.calc],
    "flow": [("auto",), ("same",), ("*",), v.ident, v.string],
    "flow-from": [("inherit",), ("none",), v.ident],
    "flow-into": [("content",), ("element",), ("none",)],
    "font": [("100",), ("200",), ("300",), ("400",), ("500",), ("600",), ("700",), ("800",), ("900",), ("bold",), ("bolder",), ("caption",), ("condensed",), ("cursive",), ("expanded",), ("extra-condensed",), ("extra-expanded",), ("fantasy",), ("icon",), ("italic",), ("large",), ("larger",), ("lighter",), ("medium",), ("menu",), ("message-box",), ("monospace",), ("none",), ("normal",), ("oblique",), ("sans-serif",), ("semi-condensed",), ("semi-expanded",), ("serif",), ("small",), ("small-caps",), ("small-caption",), ("smaller",), ("status-bar",), ("ultra-condensed",), ("ultra-expanded",), ("x-large",), ("x-small",), ("xx-large",), ("xx-small",), v.length, v.number, v.percentage, v.string, v.calc],
    "font-family": [("cursive",), ("fantasy",), ("monospace",), ("sans-serif",), ("serif",), v.ident, v.string],
    "font-feature-settings": [("normal",), ("off",), ("on",), v.integer, v.string, v.calc],
    "font-kerning": [("auto",), ("none",), ("normal",)],
    "font-language-override": [("normal",), v.string],
    "font-size": [("large",), ("larger",), ("medium",), ("small",), ("smaller",), ("x-large",), ("x-small",), ("xx-large",), ("xx-small",), v.length, v.percentage, v.calc],
    "font-size-adjust": [("none",), v.number, v.calc],
    "font-stretch": [("condensed",), ("expanded",), ("extra-condensed",), ("extra-expanded",), ("normal",), ("semi-condensed",), ("semi-expanded",), ("ultra-condensed",), ("ultra-expanded",)],
    "font-style": [("italic",), ("normal",), ("oblique",)],
    "font-synthesis": [("none",), ("style",), ("weight",)],
    "font-variant": [("all-petite-caps",), ("all-small-caps",), ("common-ligatures",), ("contextual",), ("diagonal-fractions",), ("discretionary-ligatures",), ("full-width",), ("historical-forms",), ("historical-ligatures",), ("jis04",), ("jis78",), ("jis83",), ("jis90",), ("lining-nums",), ("no-common-ligatures",), ("no-contextual",), ("no-discretionary-ligatures",), ("no-historical-ligatures",), ("none",), ("normal",), ("oldstyle-nums",), ("ordinal",), ("petite-caps",), ("proportional-nums",), ("proportional-width",), ("ruby",), ("simplified",), ("slashed-zero",), ("small-caps",), ("stacked-fractions",), ("tabular-nums",), ("titling-caps",), ("traditional",), ("unicase",), v.annotation, v.character_variant, v.ornaments, v.styleset, v.stylistic, v.swash],
    "font-variant-alternates": [("historical-forms",), ("normal",), v.annotation, v.character_variant, v.ornaments, v.styleset, v.stylistic, v.swash],
    "font-variant-caps": [("all-petite-caps",), ("all-small-caps",), ("normal",), ("petite-caps",), ("small-caps",), ("titling-caps",), ("unicase",)],
    "font-variant-east-asian": [("full-width",), ("jis04",), ("jis78",), ("jis83",), ("jis90",), ("normal",), ("proportional-width",), ("ruby",), ("simplified",), ("traditional",)],
    "font-variant-ligatures": [("common-ligatures",), ("contextual",), ("discretionary-ligatures",), ("historical-ligatures",), ("no-common-ligatures",), ("no-contextual",), ("no-discretionary-ligatures",), ("no-historical-ligatures",), ("none",), ("normal",)],
    "font-variant-numeric": [("diagonal-fractions",), ("lining-nums",), ("normal",), ("oldstyle-nums",), ("ordinal",), ("proportional-nums",), ("slashed-zero",), ("stacked-fractions",), ("tabular-nums",)],
    "font-variant-position": [("normal",), ("sub",), ("super",)],
    "font-weight": [("100",), ("200",), ("300",), ("400",), ("500",), ("600",), ("700",), ("800",), ("900",), ("bold",), ("bolder",), ("lighter",), ("normal",)],
    "footnote-display": [("block",), ("compact",), ("inline",)],
    "footnote-policy": [("auto",), ("block",), ("line",)],
    "grid": [("auto",), ("column",), ("dense",), ("max-content",), ("min-content",), ("none",), ("row",), ("stack",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.string, v.calc, v.minmax, v.repeat],
    "grid-area": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-auto-columns": [("auto",), ("max-content",), ("min-content",), v.flex, v.length, v.percentage, v.calc, v.minmax],
    "grid-auto-flow": [("column",), ("dense",), ("row",), ("stack",)],
    "grid-auto-rows": [("auto",), ("max-content",), ("min-content",), v.flex, v.length, v.percentage, v.calc, v.minmax],
    "grid-column": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-column-end": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-column-start": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-row": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-row-end": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-row-start": [("auto",), ("span",), v.ident, v.integer, v.calc],
    "grid-template": [("auto",), ("max-content",), ("min-content",), ("none",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.string, v.calc, v.minmax, v.repeat],
    "grid-template-areas": [("none",), v.string],
    "grid-template-columns": [("auto",), ("max-content",), ("min-content",), ("none",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.calc, v.minmax, v.repeat],
    "grid-template-rows": [("auto",), ("max-content",), ("min-content",), ("none",), ("subgrid",), v.flex, v.ident, v.length, v.percentage, v.calc, v.minmax, v.repeat],
    "hanging-punctuation": [("allow-end",), ("first",), ("force-end",), ("last",), ("none",)],
    "height": [("auto",), ("available",), ("border-box",), ("complex",), ("content-box",), ("extend-to-zoom",), ("fit-content",), ("max-content",), ("min-content",), v.length, v.percentage, v.calc],
    "hyphenate-character": [("auto",), v.string],
    "hyphenate-limit-chars": [("auto"), v.integer, v.calc],
    "hyphenate-limit-last": [("always",), ("column",), ("none",), ("page",), ("spread",)],
    "hyphenate-limit-lines": [("no-limit",), v.integer, v.calc],
    "hyphenate-limit-zone": [v.percentage, v.length, v.calc],
    "hyphens": [("auto",), ("manual",), ("none",)],
    "image-orientation": [v.angle, v.calc],
    "image-rendering": [("auto",), ("optimizeQuality",), ("optimizeSpeed",)],
    "image-resolution": [("from-image",), ("snap",), v.resolution],
    "indent-edge-reset": [("border-edge",), ("content-edge",), ("margin-edge",), ("none",), ("padding-edge",)],
    "initial-letter": [("normal",), v.integer, v.number, v.calc],
    "initial-letter-align": [("alphabetic",), ("border-box",), ("hanging",), ("hebrew",), ("ideographic",)],
    "initial-letter-wrap": [("all",), ("first",), ("grid",), ("none",), v.length, v.percentage, v.calc],
    "inline-box-align": [("initial",), ("last",), v.integer, v.calc],
    "inline-size": [v.length, v.percentage, v.number, v.calc],
    "isolation": [("auto",), ("isolate",)],
    "justify-content": [("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("space-around",), ("space-between",), ("space-evenly",), ("start",), ("stretch",), ("unsafe",)],
    "justify-items": [("auto",), ("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("legacy",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "justify-self": [("auto",), ("baseline",), ("center",), ("end",), ("flex-end",), ("flex-start",), ("last-baseline",), ("left",), ("normal",), ("right",), ("safe",), ("self-end",), ("self-start",), ("start",), ("stretch",), ("unsafe",)],
    "left": [("auto",), v.length, v.percentage, v.calc],
    "letter-spacing": [("normal"), v.length, v.calc],
    "lighting-color": v.svg_color,
    "line-break": [("auto",), ("loose",), ("normal",), ("strict",)],
    "line-grid": [("create",), ("match-parent",)],
    "line-height": [("none",), ("normal",), v.length, v.number, v.percentage, v.calc],
    "line-snap": [("baseline",), ("contain",), ("none",)],
    "line-stacking": [("block-line-height",), ("consider-shifts",), ("disregard-shifts",), ("exclude-ruby",), ("grid-height",), ("include-ruby",), ("inline-line-height",), ("max-height",)],
    "line-stacking-ruby": [("exclude-ruby",), ("include-ruby",)],
    "line-stacking-shift": [("consider-shifts",), ("disregard-shifts",)],
    "line-stacking-strategy": [("block-line-height",), ("grid-height",), ("inline-line-height",), ("max-height",)],
    "list-style": [("inside",), ("none",), ("outside",), v.ident, v.string, v.symbols] + v.image + v.counter_style,
    "list-style-image": [("none",)] + v.image,
    "list-style-position": [("inside",), ("outside",)],
    "list-style-type": [("none",), v.ident, v.string, v.symbols] + v.counter_style,
    "margin": [("auto",), ("fill",), v.length, v.percentage, v.calc],
    "margin-bottom": [("auto",), ("fill",), v.length, v.percentage, v.calc],
    "margin-left": [("auto",), ("fill",), v.length, v.percentage, v.calc],
    "margin-right": [("auto",), ("fill",), v.length, v.percentage, v.calc],
    "margin-top": [("auto",), ("fill",), v.length, v.percentage, v.calc],
    "marker": [("none",), v.url],
    "marker-end": [("none",), v.url],
    "marker-mid": [("none",), v.url],
    "marker-side": [("list-container",), ("list-item",)],
    "marker-start": [("none",), v.url],
    "marks": [("crop",), ("cross",), ("none",)],
    "mask": [("add",), ("alpha",), ("auto",), ("border-box",), ("contain",), ("content-box",), ("cover",), ("exclude",), ("fill-box",), ("intersect",), ("luminance",), ("margin-box",), ("no-clip",), ("no-repeat",), ("none",), ("padding-box",), ("repeat",), ("repeat-x",), ("repeat-y",), ("round",), ("space",), ("stroke-box",), ("subtract",), ("view-box",), v.length, v.percentage, v.calc, v.url] + v.position + v.image,
    "mask-border": [("alpha",), ("auto",), ("fill",), ("luminance",), ("none",), ("repeat",), ("round",), ("space",), ("stretch",), v.length, v.number, v.percentage, v.calc] + v.image,
    "mask-border-mode": [("alpha",), ("luminance",)],
    "mask-border-outset": [v.length, v.number, v.calc],
    "mask-border-repeat": [("repeat",), ("round",), ("space",), ("stretch",)],
    "mask-border-slice": [("fill",), v.number, v.percentage, v.calc],
    "mask-border-source": [("none",)] + v.image,
    "mask-border-width": [("auto",), v.length, v.number, v.percentage, v.calc],
    "mask-clip": [("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("no-clip",), ("padding-box",), ("stroke-box",), ("view-box",)],
    "mask-composite": [("add",), ("exclude",), ("intersect",), ("subtract",)],
    "mask-image": [("none",), v.url] + v.image,
    "mask-mode": [("alpha",), ("auto",), ("luminance",)],
    "mask-origin": [("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("padding-box",), ("stroke-box",), ("view-box",)],
    "mask-position": v.position,
    "mask-repeat": [("no-repeat",), ("repeat",), ("repeat-x",), ("repeat-y",), ("round",), ("space",)],
    "mask-size": [("auto",), ("contain",), ("cover",), v.length, v.percentage, v.calc],
    "mask-type": [("alpha",), ("luminance",)],
    "max-height": [("available",), ("border-box",), ("content-box",), ("extend-to-zoom",), ("fit-content",), ("max-content",), ("min-content",), ("none",), v.length, v.percentage, v.calc],
    "max-lines": [("none",), v.integer, v.calc],
    "max-width": [("available",), ("border-box",), ("content-box",), ("extend-to-zoom",), ("fit-content",), ("max-content",), ("min-content",), ("none",), v.length, v.percentage, v.calc],
    "max-zoom": [("auto",), v.number, v.percentage, v.calc],
    "min-height": [("available",), ("auto",), ("border-box",), ("content-box",), ("extend-to-zoom",), ("fit-content",), ("max-content",), ("min-content",), v.length, v.percentage, v.calc],
    "min-width": [("available",), ("auto",), ("border-box",), ("content-box",), ("extend-to-zoom",), ("fit-content",), ("max-content",), ("min-content",), v.length, v.percentage, v.calc],
    "min-zoom": [("auto",), v.number, v.percentage, v.calc],
    "mix-blend-mode": [("color",), ("color-burn",), ("color-dodge",), ("darken",), ("difference",), ("exclusion",), ("hard-light",), ("hue",), ("lighten",), ("luminosity",), ("multiply",), ("normal",), ("overlay",), ("saturation",), ("screen",), ("soft-light",)],
    "motion": [("auto",), ("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("none",), ("padding-box",), ("reverse",), ("stroke-box",), ("view-box",), v.angle, v.circle, v.ellipse, v.inset, v.length, v.path, v.percentage, v.polygon, v.url, v.calc],
    "motion-offset": [v.length, v.percentage, v.calc],
    "motion-path": [("border-box",), ("content-box",), ("fill-box",), ("margin-box",), ("none",), ("padding-box",), ("stroke-box",), ("view-box",), v.circle, v.ellipse, v.inset, v.path, v.polygon, v.url],
    "motion-rotation": [("auto",), ("reverse",), v.angle, v.calc],
    "nav-down": [("auto",), ("current",), ("root",), ("<id>", "#${1:id}"), v.ident],
    "nav-left": [("auto",), ("current",), ("root",), ("<id>", "#${1:id}"), v.ident],
    "nav-right": [("auto",), ("current",), ("root",), ("<id>", "#${1:id}"), v.ident],
    "nav-up": [("auto",), ("current",), ("root",), ("<id>", "#${1:id}"), v.ident],
    "negative": [v.ident, v.string] + v.image,
    "object-fit": [("contain",), ("cover",), ("fill",), ("none",), ("scale-down",)],
    "object-position": v.position,
    "offset-after": [("auto",), v.length, v.percentage, v.calc],
    "offset-before": [("auto",), v.length, v.percentage, v.calc],
    "offset-end": [("auto",), v.length, v.percentage, v.calc],
    "offset-start": [("auto",), v.length, v.percentage, v.calc],
    "opacity": [v.number, v.percentage, v.calc],
    "order": [v.integer, v.calc],
    "orientation": [("auto",), ("landscape",), ("portrait",)],
    "orphans": [v.integer, v.calc],
    "outline": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("invert",), ("medium",), ("none",), ("outset",), ("ridge",), ("solid",), ("thick",), ("thin",), v.length, v.calc] + v.color,
    "outline-color": [("invert",)] + v.color,
    "outline-offset": [v.length, v.calc],
    "outline-style": [("dashed",), ("dotted",), ("double",), ("groove",), ("hidden",), ("inset",), ("none",), ("outset",), ("ridge",), ("solid",)],
    "outline-width": [("medium",), ("thick",), ("thin",), v.length, v.calc],
    "overflow": [("auto",), ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)],
    "overflow-wrap": [("break-word",), ("normal",)],
    "overflow-x": [("auto",), ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)],
    "overflow-y": [("auto",), ("fragments",), ("hidden",), ("paged-x",), ("paged-x-controls",), ("paged-y",), ("paged-y-controls",), ("scroll",), ("visible",)],
    "pad": [v.ident, v.integer, v.string, v.calc] + v.image,
    "padding": [("padding",), v.length, v.percentage, v.calc],
    "padding-bottom": [("padding",), v.length, v.percentage, v.calc],
    "padding-left": [("padding",), v.length, v.percentage, v.calc],
    "padding-right": [("padding",), v.length, v.percentage, v.calc],
    "padding-top": [("padding",), v.length, v.percentage, v.calc],
    "page": [("auto",), v.ident],
    "page-policy": [("first",), ("last",), ("start",)],
    "paint-order": [("fill",), ("markers",), ("normal",), ("stroke",)],
    "pause": [("medium",), ("none",), ("strong",), ("weak",), ("x-strong",), ("x-weak",), v.time],
    "pause-after": [("medium",), ("none",), ("strong",), ("weak",), ("x-strong",), ("x-weak",), v.time],
    "pause-before": [("medium",), ("none",), ("strong",), ("weak",), ("x-strong",), ("x-weak",), v.time],
    "perspective": [("none",), v.length, v.calc],
    "perspective-origin": v.position,
    "pointer-events": [("all",), ("auto",), ("bounding-box"), ("fill",), ("none",), ("painted",), ("stroke",), ("visible",), ("visibleFill",), ("visiblePainted",), ("visibleStroke",)],
    "polar-anchor": v.position,
    "polar-angle": [v.angle, v.calc],
    "polar-distance": [("closest-corner",), ("closest-side",), ("contain",), ("farthest-corner",), ("farthest-side",), v.length, v.percentage, v.calc],
    "polar-origin": [("auto",), v.position],
    "position": [("absolute",), ("center",), ("fixed",), ("page",), ("relative",), ("static",), ("sticky",)],
    "prefix": [v.ident, v.string] + v.image,
    "quotes": [("none",), v.string],
    "r": [v.length, v.percentage, v.calc],
    "range": [("auto",), ("infinite",), v.integer, v.calc],
    "region-fragment": [("auto",), ("break",)],
    "resize": [("both",), ("horizontal",), ("inherit",), ("none",), ("vertical",)],
    "resolution": [("auto",), ("device",), v.resolution],
    "rest": [("medium",), ("none",), ("strong",), ("weak",), ("x-strong",), ("x-weak",), v.time],
    "rest-after": [("medium",), ("none",), ("strong",), ("weak",), ("x-strong",), ("x-weak",), v.time],
    "rest-before": [("medium",), ("none",), ("strong",), ("weak",), ("x-strong",), ("x-weak",), v.time],
    "right": [("auto",), v.length, v.percentage, v.calc],
    "rotation": [v.angle],
    "rotation-point": v.position,
    "ruby-align": [("center",), ("space-around",), ("space-between",), ("start",)],
    "ruby-merge": [("auto",), ("collapse",), ("separate",)],
    "ruby-position": [("inter-character",), ("left",), ("over",), ("right",), ("under",)],
    "running": [v.ident],
    "r": [v.length, v.percentage, v.calc],
    "rx": [v.length, v.percentage, v.calc],
    "ry": [v.length, v.percentage, v.calc],
    "scroll-behavior": [("auto",), ("smooth",)],
    "scroll-snap-align": [("center",), ("end",), ("none",), ("start",)],
    "scroll-snap-margin": [v.length, v.percentage, v.calc],
    "scroll-snap-padding": [v.length, v.percentage, v.calc],
    "scroll-snap-type": [("mandatory",), ("none",), ("proximity",)],
    "shape-image-threshold": [v.number, v.calc],
    "shape-inside": [("auto",), ("display",), ("outside-shape",), ("shape-box",), v.circle, v.ellipse, v.inset, v.polygon] + v.image,
    "shape-margin": [v.length, v.percentage, v.calc],
    "shape-outside": [("border-box",), ("content-box",), ("margin-box",), ("none",), ("padding-box",), v.circle, v.ellipse, v.inset, v.polygon] + v.image,
    "shape-padding": [v.length, v.calc],
    "shape-rendering": [("auto",), ("crispEdges",), ("geometricPrecision",), ("optimizeSpeed",)],
    "shape-subtract": [("none",), ("display",), ("outside-shape",), ("shape-box",), v.circle, v.ellipse, v.inset, v.polygon] + v.image,
    "size": [("A3",), ("A4",), ("A5",), ("B4",), ("B5",), ("auto",), ("landscape",), ("ledger",), ("legal",), ("letter",), ("portrait",), v.length, v.calc],
    "speak": [("auto",), ("none",), ("normal",)],
    # there is also a speak-as descriptor for @counter-style. the values here are a mix of the two properties.
    "speak-as": [("auto",), ("bullets",), ("digits",), ("literal-punctuation",), ("no-punctuation",), ("normal",), ("numbers",), ("spell-out",), ("words",)],
    "src": [v.format_func, v.local, v.url],
    "stop-color": [v.svg_color],
    "stop-opacity": [v.number, v.calc],
    "string-set": [("none",), v.content, v.counter, v.counters, v.ident, v.string],
    "stroke": [("none",), ("context-stroke",), ("context-fill",), ("child",), v.child, v.color],
    "stroke-dasharray": [("none",), v.length, v.percentage, v.calc],
    "stroke-dashoffset": [v.length, v.percentage, v.calc],
    "stroke-linecap": [("butt",), ("round",), ("square",)],
    "stroke-linejoin": [("arcs",), ("bevel",), ("miter",), ("miter-clip",), ("round",)],
    "stroke-miterlimit": [v.number, v.calc],
    "stroke-opacity": [v.number, v.calc],
    "stroke-width": [v.length, v.percentage, v.calc],
    "suffix": [v.ident, v.string] + v.image,
    "symbols": [v.ident, v.string] + v.image,
    "system": [("additive",), ("alphabetic",), ("cyclic",), ("extends",), ("fixed",), ("numeric",), ("symbolic",), v.integer, v.calc] + v.counter_style,
    "tab-size": [v.integer, v.length, v.calc],
    "table-layout": [("auto",), ("fixed",)],
    "text-align": [("center",), ("end",), ("justify",), ("justify-all",), ("left",), ("match-parent",), ("right",), ("start",)],
    "text-align-last": [("auto",), ("center",), ("end",), ("justify",), ("left",), ("right",), ("start",)],
    "text-anchor": [("end",), ("middle",), ("start",)],
    "text-combine-upright": [("all",), ("digits",), ("none",), v.integer, v.calc],
    "text-decoration": [("blink",), ("dashed",), ("dotted",), ("double",), ("line-through",), ("none",), ("overline",), ("solid",), ("underline",), ("wavy",)] + v.color,
    "text-decoration-color": v.color,
    "text-decoration-fill": [("none",), ("context-stroke",), ("context-fill",), ("child",), v.child, v.color],
    "text-decoration-line": [("blink",), ("line-through",), ("none",), ("overline",), ("underline",)],
    "text-decoration-skip": [("box-decoration",), ("edges",), ("ink",), ("none",), ("objects",), ("spaces",)],
    "text-decoration-stroke": [("none",), ("context-stroke",), ("context-fill",), ("child",), v.child, v.color],
    "text-decoration-style": [("dashed",), ("dotted",), ("double",), ("solid",), ("wavy",)],
    "text-emphasis": [("circle",), ("dot",), ("double-circle",), ("filled",), ("none",), ("open",), ("sesame",), ("triangle",), v.string] + v.color,
    "text-emphasis-color": v.color,
    "text-emphasis-position": [("left",), ("over",), ("right",), ("under",)],
    "text-emphasis-style": [("circle",), ("dot",), ("double-circle",), ("filled",), ("none",), ("open",), ("sesame",), ("triangle",), v.string],
    "text-height": [("auto",), ("font-size",), ("max-size",), ("text-size",), v.number, v.calc],
    "text-indent": [("each-line",), ("hanging",), v.length, v.percentage, v.calc],
    "text-justify": [("auto",), ("distribute",), ("inter-word",), ("none",)],
    "text-orientation": [("mixed",), ("sideways",), ("upright",)],
    "text-overflow": [("clip",), ("ellipsis",), v.string],
    "text-rendering": [("auto",), ("geometricPrecision",), ("optimizeLegibility",), ("optimizeSpeed",)],
    "text-shadow": [("none",), v.length, v.calc] + v.color,
    "text-space-collapse": [("collapse",), ("discard",), ("preserve",), ("preserve-auto",), ("preserve-breaks",), ("preserve-spaces",), ("preserve-trim",)],
    "text-space-trim": [("discard-after",), ("discard-before",), ("none",), ("trim-inner",)],
    "text-spacing": [("allow-end",), ("ideograph-alpha",), ("ideograph-numeric",), ("no-compress",), ("none",), ("normal",), ("punctuation",), ("space-adjacent",), ("space-end",), ("space-start",), ("trim-adjacent",), ("trim-end",), ("trim-start",)],
    "text-transform": [("capitalize",), ("full-width",), ("lowercase",), ("none",), ("uppercase",)],
    "text-underline-position": [("auto",), ("left",), ("right",), ("under",)],
    "text-wrap": [("balance",), ("normal",), ("nowrap",)],
    "top": [("auto",), v.length, v.percentage, v.calc],
    "transform": [("none",)] + v.transform,
    "transform-box": [("border-box",), ("fill-box",), ("view-box",)],
    "transform-origin": v.position,
    "transform-style": [("flat",), ("preserve-3d",)],
    "transition": [("all",), ("background",), ("background-color",), ("background-image",), ("background-position",), ("background-size",), ("border",), ("border-bottom",), ("border-bottom-color",), ("border-bottom-left-radius",), ("border-bottom-right-radius",), ("border-bottom-width",), ("border-color",), ("border-left",), ("border-left-color",), ("border-left-width",), ("border-radius",), ("border-right",), ("border-right-color",), ("border-right-width",), ("border-top",), ("border-top-color",), ("border-top-left-radius",), ("border-top-right-radius",), ("border-top-width",), ("border-width",), ("bottom",), ("box-shadow",), ("clip",), ("color",), ("column-count",), ("column-gap",), ("column-rule",), ("column-rule-color",), ("column-rule-width",), ("column-width",), ("columns",), ("flex",), ("flex-basis",), ("flex-grow",), ("flex-shrink",), ("font",), ("font-size",), ("font-size-adjust",), ("font-stretch",), ("font-weight",), ("height",), ("left",), ("letter-spacing",), ("line-height",), ("margin",), ("margin-bottom",), ("margin-left",), ("margin-right",), ("margin-top",), ("max-height",), ("max-width",), ("min-height",), ("min-width",), ("none",), ("opacity",), ("order",), ("outline",), ("outline-color",), ("outline-offset",), ("outline-width",), ("padding",), ("padding-bottom",), ("padding-left",), ("padding-right",), ("padding-top",), ("perspective",), ("perspective-origin",), ("right",), ("shape-image-threshold",), ("shape-margin",), ("shape-outside",), ("text-decoration",), ("text-decoration-color",), ("text-indent",), ("text-shadow",), ("top",), ("transform",), ("transform-origin",), ("vertical-align",), ("visibility",), ("width",), ("word-spacing",), ("z-index",), v.time, v.calc] + v.timing_function,
    "transition-delay": [v.time, v.calc],
    "transition-duration": [v.time, v.calc],
    "transition-property": [("all",), ("none",), v.ident],
    "transition-timing-function": v.timing_function,
    "unicode-bidi": [("bidi-override",), ("embed",), ("isolate",), ("isolate-override",), ("normal",), ("plaintext",)],
    "unicode-range": [v.urange],
    "user-select": [("all",), ("auto",), ("contain",), ("none",), ("text",)],
    "user-zoom": [("fixed",), ("zoom",)],
    "vector-effect": [("none",), ("non-scaling-stroke",)],
    "vertical-align": [("alphabetic",), ("baseline",), ("bottom",), ("center",), ("central",), ("mathematical",), ("middle",), ("sub",), ("super",), ("text-bottom",), ("text-top",), ("top",), v.length, v.percentage, v.calc],
    "visibility": [("collapse",), ("hidden",), ("visible",)],
    "voice-balance": [("center",), ("left",), ("leftwards",), ("right",), ("rightwards",), v.number, v.calc],
    "voice-duration": [("auto",), v.time],
    "voice-family": [("child",), ("female",), ("male",), ("neutral",), ("old",), ("preserve",), ("young",), v.ident, v.integer, v.string, v.calc],
    "voice-pitch": [("absolute",), ("high",), ("low",), ("medium",), ("x-high",), ("x-low",), v.frequency, v.percentage, v.semitones, v.calc],
    "voice-range": [("absolute",), ("high",), ("low",), ("medium",), ("x-high",), ("x-low",), v.frequency, v.percentage, v.semitones, v.calc],
    "voice-rate": [("fast",), ("medium",), ("normal",), ("slow",), ("x-fast",), ("x-slow",), v.percentage, v.calc],
    "voice-stress": [("moderate",), ("none",), ("normal",), ("reduced",), ("strong",)],
    "voice-volume": [("loud",), ("medium",), ("silent",), ("soft",), ("x-loud",), ("x-soft",), v.decibel],
    "white-space": [("normal",), ("nowrap",), ("pre",), ("pre-line",), ("pre-wrap",), ("pre-wrap-auto",)],
    "widows": [v.integer, v.calc],
    "width": [("auto",), ("available",), ("border-box",), ("content-box",), ("extend-to-zoom",), ("fit-content",), ("max-content",), ("min-content",), v.length, v.percentage, v.calc],
    "will-change": [("auto",), ("contents",), ("scroll-position",), v.ident],
    "word-break": [("break-all",), ("keep-all",), ("normal",)],
    "word-spacing": [("normal",), v.length, v.percentage, v.calc],
    "word-wrap": [("break-word",), ("normal",)],
    "wrap-after": [("auto",), ("both",), ("clear",), ("end",), ("maximum",), ("minimum",), ("start",)],
    "wrap-before": [("auto",), ("both",), ("clear",), ("end",), ("maximum",), ("minimum",), ("start",)],
    "wrap-flow": [("auto",), ("both",), ("clear",), ("end",), ("maximum",), ("minimum",), ("start",)],
    "wrap-inside": [("auto",), ("avoid",)],
    "wrap-through": [("none",), ("wrap",)],
    "writing-mode": [("horizontal-tb",), ("sideways-lr",), ("sideways-rl",), ("vertical-lr",), ("vertical-rl",)],
    "x": [v.length, v.percentage, v.calc],
    "y": [v.length, v.percentage, v.calc],
    "z-index": [("auto",), v.integer, v.calc],
    "zoom": [("auto",), v.number, v.percentage, v.calc],
}
