#!/usr/bin/env python3


from CSS3.completions import values as v


names = [
    ("-moz-box-sizing", "-moz-box-sizing: ${0};"),
    ("-moz-column-count", "-moz-column-count: ${0};"),
    ("-moz-column-fill", "-moz-column-fill: ${0};"),
    ("-moz-column-gap", "-moz-column-gap: ${0};"),
    ("-moz-column-rule", "-moz-column-rule: ${0};"),
    ("-moz-column-rule-color", "-moz-column-rule-color: ${0};"),
    ("-moz-column-rule-style", "-moz-column-rule-style: ${0};"),
    ("-moz-column-rule-width", "-moz-column-rule-width: ${0};"),
    ("-moz-column-span", "-moz-column-span: ${0};"),
    ("-moz-column-width", "-moz-column-width: ${0};"),
    ("-moz-columns", "-moz-columns: ${0};"),
    ("-moz-font-feature-settings", "-moz-font-feature-settings: ${0};"),
    ("-moz-font-language-override", "-moz-font-language-override: ${0};"),
    ("-moz-hyphens", "-moz-hyphens: ${0};"),
    ("-moz-text-align-last", "-moz-text-align-last: ${0};"),
    ("-moz-text-decoration-color", "-moz-text-decoration-color: ${0};"),
    ("-moz-text-decoration-line", "-moz-text-decoration-line: ${0};"),
    ("-moz-text-decoration-style", "-moz-text-decoration-style: ${0};"),
    ("-ms-flow-from", "-ms-flow-from: ${0};"),
    ("-ms-flow-into", "-ms-flow-into: ${0};"),
    ("-ms-grid-column", "-ms-grid-column: ${0};"),
    ("-ms-grid-row", "-ms-grid-row: ${0};"),
    ("-ms-hyphens", "-ms-hyphens: ${0};"),
    ("-ms-ime-mode", "-ms-ime-mode: ${0};"),
    ("-ms-overflow-style", "-ms-overflow-style: ${0};"),
    ("-ms-overflow-x", "-ms-overflow-x: ${0};"),
    ("-ms-overflow-y", "-ms-overflow-y: ${0};"),
    ("-ms-text-align-last", "-ms-text-align-last: ${0};"),
    ("-ms-text-justify", "-ms-text-justify: ${0};"),
    ("-ms-transform", "-ms-transform: ${0};"),
    ("-ms-transform-origin", "-ms-transform-origin: ${0};"),
    ("-ms-transform-style", "-ms-transform-style: ${0};"),
    ("-ms-word-wrap", "-ms-word-wrap: ${0};"),
    ("-ms-wrap-flow", "-ms-wrap-flow: ${0};"),
    ("-ms-wrap-through", "-ms-wrap-through: ${0};"),
    ("-ms-writing-mode", "-ms-writing-mode: ${0};"),
    ("-webkit-align-content", "-webkit-align-content: ${0};"),
    ("-webkit-align-items", "-webkit-align-items: ${0};"),
    ("-webkit-align-self", "-webkit-align-self: ${0};"),
    ("-webkit-animation", "-webkit-animation: ${0};"),
    ("-webkit-animation-delay", "-webkit-animation-delay: ${0};"),
    ("-webkit-animation-direction", "-webkit-animation-direction: ${0};"),
    ("-webkit-animation-duration", "-webkit-animation-duration: ${0};"),
    ("-webkit-animation-fill-mode", "-webkit-animation-fill-mode: ${0};"),
    ("-webkit-animation-iteration-count", "-webkit-animation-iteration-count: ${0};"),
    ("-webkit-animation-name", "-webkit-animation-name: ${0};"),
    ("-webkit-animation-play-state", "-webkit-animation-play-state: ${0};"),
    ("-webkit-animation-timing-function", "-webkit-animation-timing-function: ${0};"),
    ("-webkit-backface-visibility", "-webkit-backface-visibility: ${0};"),
    ("-webkit-border-image", "-webkit-border-image: ${0};"),
    ("-webkit-break-after", "-webkit-break-after: ${0};"),
    ("-webkit-break-before", "-webkit-break-before: ${0};"),
    ("-webkit-break-inside", "-webkit-break-inside: ${0};"),
    ("-webkit-column-count", "-webkit-column-count: ${0};"),
    ("-webkit-column-fill", "-webkit-column-fill: ${0};"),
    ("-webkit-column-gap", "-webkit-column-gap: ${0};"),
    ("-webkit-column-rule", "-webkit-column-rule: ${0};"),
    ("-webkit-column-rule-color", "-webkit-column-rule-color: ${0};"),
    ("-webkit-column-rule-style", "-webkit-column-rule-style: ${0};"),
    ("-webkit-column-rule-width", "-webkit-column-rule-width: ${0};"),
    ("-webkit-column-span", "-webkit-column-span: ${0};"),
    ("-webkit-column-width", "-webkit-column-width: ${0};"),
    ("-webkit-columns", "-webkit-columns: ${0};"),
    ("-webkit-flex", "-webkit-flex: ${0};"),
    ("-webkit-flex-basis", "-webkit-flex-basis: ${0};"),
    ("-webkit-flex-direction", "-webkit-flex-direction: ${0};"),
    ("-webkit-flex-flow", "-webkit-flex-flow: ${0};"),
    ("-webkit-flex-grow", "-webkit-flex-grow: ${0};"),
    ("-webkit-flex-shrink", "-webkit-flex-shrink: ${0};"),
    ("-webkit-flex-wrap", "-webkit-flex-wrap: ${0};"),
    ("-webkit-flow-from", "-webkit-flow-from: ${0};"),
    ("-webkit-flow-into", "-webkit-flow-into: ${0};"),
    ("-webkit-font-feature-settings", "-webkit-font-feature-settings: ${0};"),
    ("-webkit-font-kerning", "-webkit-font-kerning: ${0};"),
    ("-webkit-font-variant-ligatures", "-webkit-font-variant-ligatures: ${0};"),
    ("-webkit-grid-column", "-webkit-grid-column: ${0};"),
    ("-webkit-grid-row", "-webkit-grid-row: ${0};"),
    ("-webkit-hyphens", "-webkit-hyphens: ${0};"),
    ("-webkit-justify-content", "-webkit-justify-content: ${0};"),
    ("-webkit-order", "-webkit-order: ${0};"),
    ("-webkit-perspective", "-webkit-perspective: ${0};"),
    ("-webkit-perspective-origin", "-webkit-perspective-origin: ${0};"),
    ("-webkit-region-fragment", "-webkit-region-fragment: ${0};"),
    ("-webkit-transform", "-webkit-transform: ${0};"),
    ("-webkit-transform-origin", "-webkit-transform-origin: ${0};"),
    ("-webkit-transform-style", "-webkit-transform-style: ${0};"),
    ("-webkit-transition", "-webkit-transition: ${0};"),
    ("-webkit-transition-delay", "-webkit-transition-delay: ${0};"),
    ("-webkit-transition-duration", "-webkit-transition-duration: ${0};"),
    ("-webkit-transition-property", "-webkit-transition-property: ${0};"),
    ("-webkit-transition-timing-function", "-webkit-transition-timing-function: ${0};"),
    ("additive-symbols", "additive-symbols: ${0};"),
    ("align-content", "align-content: ${0};"),
    ("align-items", "align-items: ${0};"),
    ("align-self", "align-self: ${0};"),
    ("alignment", "alignment: ${0};"),
    ("alignment-adjust", "alignment-adjust: ${0};"),
    ("alignment-baseline", "alignment-baseline: ${0};"),
    ("all", "all: ${0};"),
    ("animation", "animation: ${0};"),
    ("animation-delay", "animation-delay: ${0};"),
    ("animation-direction", "animation-direction: ${0};"),
    ("animation-duration", "animation-duration: ${0};"),
    ("animation-fill-mode", "animation-fill-mode: ${0};"),
    ("animation-iteration-count", "animation-iteration-count: ${0};"),
    ("animation-name", "animation-name: ${0};"),
    ("animation-play-state", "animation-play-state: ${0};"),
    ("animation-timing-function", "animation-timing-function: ${0};"),
    ("backface-visibility", "backface-visibility: ${0};"),
    ("background", "background: ${0};"),
    ("background-attachment", "background-attachment: ${0};"),
    ("background-clip", "background-clip: ${0};"),
    ("background-color", "background-color: ${0};"),
    ("background-image", "background-image: ${0};"),
    ("background-origin", "background-origin: ${0};"),
    ("background-position", "background-position: ${0};"),
    ("background-repeat", "background-repeat: ${0};"),
    ("background-size", "background-size: ${0};"),
    ("baseline-shift", "baseline-shift: ${0};"),
    ("bleed", "bleed: ${0};"),
    ("bookmark-label", "bookmark-label: ${0};"),
    ("bookmark-level", "bookmark-level: ${0};"),
    ("bookmark-state", "bookmark-state: ${0};"),
    ("border", "border: ${0};"),
    ("border-bottom", "border-bottom: ${0};"),
    ("border-bottom-color", "border-bottom-color: ${0};"),
    ("border-bottom-left-radius", "border-bottom-left-radius: ${0};"),
    ("border-bottom-right-radius", "border-bottom-right-radius: ${0};"),
    ("border-bottom-style", "border-bottom-style: ${0};"),
    ("border-bottom-width", "border-bottom-width: ${0};"),
    ("border-clip", "border-clip: ${0};"),
    ("border-clip-bottom", "border-clip-bottom: ${0};"),
    ("border-clip-left", "border-clip-left: ${0};"),
    ("border-clip-right", "border-clip-right: ${0};"),
    ("border-clip-top", "border-clip-top: ${0};"),
    ("border-collapse", "border-collapse: ${0};"),
    ("border-color", "border-color: ${0};"),
    ("border-image", "border-image: ${0};"),
    ("border-image-outset", "border-image-outset: ${0};"),
    ("border-image-repeat", "border-image-repeat: ${0};"),
    ("border-image-slice", "border-image-slice: ${0};"),
    ("border-image-source", "border-image-source: ${0};"),
    ("border-image-width", "border-image-width: ${0};"),
    ("border-left", "border-left: ${0};"),
    ("border-left-color", "border-left-color: ${0};"),
    ("border-left-style", "border-left-style: ${0};"),
    ("border-left-width", "border-left-width: ${0};"),
    ("border-limit", "border-limit: ${0};"),
    ("border-radius", "border-radius: ${0};"),
    ("border-right", "border-right: ${0};"),
    ("border-right-color", "border-right-color: ${0};"),
    ("border-right-style", "border-right-style: ${0};"),
    ("border-right-width", "border-right-width: ${0};"),
    ("border-spacing", "border-spacing: ${0};"),
    ("border-style", "border-style: ${0};"),
    ("border-top", "border-top: ${0};"),
    ("border-top-color", "border-top-color: ${0};"),
    ("border-top-left-radius", "border-top-left-radius: ${0};"),
    ("border-top-right-radius", "border-top-right-radius: ${0};"),
    ("border-top-style", "border-top-style: ${0};"),
    ("border-top-width", "border-top-width: ${0};"),
    ("border-width", "border-width: ${0};"),
    ("bottom", "bottom: ${0};"),
    ("box-decoration-break", "box-decoration-break: ${0};"),
    ("box-shadow", "box-shadow: ${0};"),
    ("box-sizing", "box-sizing: ${0};"),
    ("box-snap", "box-snap: ${0};"),
    ("break-after", "break-after: ${0};"),
    ("break-before", "break-before: ${0};"),
    ("break-inside", "break-inside: ${0};"),
    ("caption-side", "caption-side: ${0};"),
    ("chains", "chains: ${0};"),
    ("child-align", "child-align: ${0};"),
    ("clear", "clear: ${0};"),
    ("clear-after", "clear-after: ${0};"),
    ("clear-side", "clear-side: ${0};"),
    ("clip-path", "clip-path: ${0};"),
    ("clip-rule", "clip-rule: ${0};"),
    ("color", "color: ${0};"),
    ("color-adjust", "color-adjust: ${0};"),
    ("color-correction", "color-correction: ${0};"),
    ("color-interpolation", "color-interpolation: ${0};"),
    ("color-interpolation-filters", "color-interpolation-filters: ${0};"),
    ("column-count", "column-count: ${0};"),
    ("column-fill", "column-fill: ${0};"),
    ("column-gap", "column-gap: ${0};"),
    ("column-rule", "column-rule: ${0};"),
    ("column-rule-color", "column-rule-color: ${0};"),
    ("column-rule-style", "column-rule-style: ${0};"),
    ("column-rule-width", "column-rule-width: ${0};"),
    ("column-span", "column-span: ${0};"),
    ("column-width", "column-width: ${0};"),
    ("columns", "columns: ${0};"),
    ("contain", "contain: ${0};"),
    ("content", "content: ${0};"),
    ("corner-shape", "corner-shape: ${0};"),
    ("corners", "corners: ${0};"),
    ("counter-increment", "counter-increment: ${0};"),
    ("counter-reset", "counter-reset: ${0};"),
    ("counter-set", "counter-set: ${0};"),
    ("cue", "cue: ${0};"),
    ("cue-after", "cue-after: ${0};"),
    ("cue-before", "cue-before: ${0};"),
    ("cursor", "cursor: ${0};"),
    ("direction", "direction: ${0};"),
    ("display", "display: ${0};"),
    ("display-box", "display-box: ${0};"),
    ("display-extras", "display-extras: ${0};"),
    ("display-inside", "display-inside: ${0};"),
    ("display-outside", "display-outside: ${0};"),
    ("dominant-baseline", "dominant-baseline: ${0};"),
    ("empty-cells", "empty-cells: ${0};"),
    ("fallback", "fallback: ${0};"),
    ("filter", "filter: ${0};"),
    ("flex", "flex: ${0};"),
    ("flex-basis", "flex-basis: ${0};"),
    ("flex-direction", "flex-direction: ${0};"),
    ("flex-flow", "flex-flow: ${0};"),
    ("flex-grow", "flex-grow: ${0};"),
    ("flex-shrink", "flex-shrink: ${0};"),
    ("flex-wrap", "flex-wrap: ${0};"),
    ("float", "float: ${0};"),
    ("float-defer-column", "float-defer-column: ${0};"),
    ("float-defer-page", "float-defer-page: ${0};"),
    ("float-displace", "float-displace: ${0};"),
    ("float-offset", "float-offset: ${0};"),
    ("float-wrap", "float-wrap: ${0};"),
    ("flood-color", "flood-color: ${0};"),
    ("flood-opacity", "flood-opacity: ${0};"),
    ("flow", "flow: ${0};"),
    ("flow-from", "flow-from: ${0};"),
    ("flow-into", "flow-into: ${0};"),
    ("font", "font: ${0};"),
    ("font-family", "font-family: ${0};"),
    ("font-feature-settings", "font-feature-settings: ${0};"),
    ("font-kerning", "font-kerning: ${0};"),
    ("font-language-override", "font-language-override: ${0};"),
    ("font-size", "font-size: ${0};"),
    ("font-size-adjust", "font-size-adjust: ${0};"),
    ("font-stretch", "font-stretch: ${0};"),
    ("font-style", "font-style: ${0};"),
    ("font-synthesis", "font-synthesis: ${0};"),
    ("font-variant", "font-variant: ${0};"),
    ("font-variant-alternates", "font-variant-alternates: ${0};"),
    ("font-variant-caps", "font-variant-caps: ${0};"),
    ("font-variant-east-asian", "font-variant-east-asian: ${0};"),
    ("font-variant-ligatures", "font-variant-ligatures: ${0};"),
    ("font-variant-numeric", "font-variant-numeric: ${0};"),
    ("font-variant-position", "font-variant-position: ${0};"),
    ("font-weight", "font-weight: ${0};"),
    ("footnote-display", "footnote-display: ${0};"),
    ("footnote-policy", "footnote-policy: ${0};"),
    ("grid", "grid: ${0};"),
    ("grid-area", "grid-area: ${0};"),
    ("grid-auto-columns", "grid-auto-columns: ${0};"),
    ("grid-auto-flow", "grid-auto-flow: ${0};"),
    ("grid-auto-rows", "grid-auto-rows: ${0};"),
    ("grid-column", "grid-column: ${0};"),
    ("grid-column-end", "grid-column-end: ${0};"),
    ("grid-column-start", "grid-column-start: ${0};"),
    ("grid-row", "grid-row: ${0};"),
    ("grid-row-end", "grid-row-end: ${0};"),
    ("grid-row-start", "grid-row-start: ${0};"),
    ("grid-template", "grid-template: ${0};"),
    ("grid-template-areas", "grid-template-areas: ${0};"),
    ("grid-template-columns", "grid-template-columns: ${0};"),
    ("grid-template-rows", "grid-template-rows: ${0};"),
    ("hanging-punctuation", "hanging-punctuation: ${0};"),
    ("height", "height: ${0};"),
    ("hyphens", "hyphens: ${0};"),
    ("icon", "icon: ${0};"),
    ("image-orientation", "image-orientation: ${0};"),
    ("image-rendering", "image-rendering: ${0};"),
    ("image-resolution", "image-resolution: ${0};"),
    ("ime-mode", "ime-mode: ${0};"),
    ("indent-edge-reset", "indent-edge-reset: ${0};"),
    ("initial-letters", "initial-letters: ${0};"),
    ("inline-box-align", "inline-box-align: ${0};"),
    ("justify-content", "justify-content: ${0};"),
    ("justify-items", "justify-items: ${0};"),
    ("justify-self", "justify-self: ${0};"),
    ("left", "left: ${0};"),
    ("letter-spacing", "letter-spacing: ${0};"),
    ("lighting-color", "lighting-color: ${0};"),
    ("line-box-contain", "line-box-contain: ${0};"),
    ("line-break", "line-break: ${0};"),
    ("line-grid", "line-grid: ${0};"),
    ("line-height", "line-height: ${0};"),
    ("line-slack", "line-slack: ${0};"),
    ("line-snap", "line-snap: ${0};"),
    ("line-stacking", "line-stacking: ${0};"),
    ("line-stacking-ruby", "line-stacking-ruby: ${0};"),
    ("line-stacking-shift", "line-stacking-shift: ${0};"),
    ("line-stacking-strategy", "line-stacking-strategy: ${0};"),
    ("list-style", "list-style: ${0};"),
    ("list-style-image", "list-style-image: ${0};"),
    ("list-style-position", "list-style-position: ${0};"),
    ("list-style-type", "list-style-type: ${0};"),
    ("margin", "margin: ${0};"),
    ("margin-bottom", "margin-bottom: ${0};"),
    ("margin-left", "margin-left: ${0};"),
    ("margin-right", "margin-right: ${0};"),
    ("margin-top", "margin-top: ${0};"),
    ("marker-side", "marker-side: ${0};"),
    ("marks", "marks: ${0};"),
    ("marquee-direction", "marquee-direction: ${0};"),
    ("marquee-play-count", "marquee-play-count: ${0};"),
    ("marquee-speed", "marquee-speed: ${0};"),
    ("marquee-style", "marquee-style: ${0};"),
    ("mask", "mask: ${0};"),
    ("mask-border", "mask-border: ${0};"),
    ("mask-border-outset", "mask-border-outset: ${0};"),
    ("mask-border-repeat", "mask-border-repeat: ${0};"),
    ("mask-border-slice", "mask-border-slice: ${0};"),
    ("mask-border-source", "mask-border-source: ${0};"),
    ("mask-border-width", "mask-border-width: ${0};"),
    ("mask-clip", "mask-clip: ${0};"),
    ("mask-composite", "mask-composite: ${0};"),
    ("mask-image", "mask-image: ${0};"),
    ("mask-mode", "mask-mode: ${0};"),
    ("mask-origin", "mask-origin: ${0};"),
    ("mask-position", "mask-position: ${0};"),
    ("mask-repeat", "mask-repeat: ${0};"),
    ("mask-size", "mask-size: ${0};"),
    ("mask-type", "mask-type: ${0};"),
    ("max-height", "max-height: ${0};"),
    ("max-lines", "max-lines: ${0};"),
    ("max-width", "max-width: ${0};"),
    ("max-zoom", "max-zoom: ${0};"),
    ("min-height", "min-height: ${0};"),
    ("min-width", "min-width: ${0};"),
    ("min-zoom", "min-zoom: ${0};"),
    ("move-to", "move-to: ${0};"),
    ("nav-down", "nav-down: ${0};"),
    ("nav-index", "nav-index: ${0};"),
    ("nav-left", "nav-left: ${0};"),
    ("nav-right", "nav-right: ${0};"),
    ("nav-up", "nav-up: ${0};"),
    ("negative", "negative: ${0};"),
    ("object-fit", "object-fit: ${0};"),
    ("object-position", "object-position: ${0};"),
    ("offset-after", "offset-after: ${0};"),
    ("offset-before", "offset-before: ${0};"),
    ("offset-end", "offset-end: ${0};"),
    ("offset-start", "offset-start: ${0};"),
    ("opacity", "opacity: ${0};"),
    ("order", "order: ${0};"),
    ("orientation", "orientation: ${0};"),
    ("orphans", "orphans: ${0};"),
    ("outline", "outline: ${0};"),
    ("outline-color", "outline-color: ${0};"),
    ("outline-offset", "outline-offset: ${0};"),
    ("outline-style", "outline-style: ${0};"),
    ("outline-width", "outline-width: ${0};"),
    ("overflow", "overflow: ${0};"),
    ("overflow-style", "overflow-style: ${0};"),
    ("overflow-wrap", "overflow-wrap: ${0};"),
    ("overflow-x", "overflow-x: ${0};"),
    ("overflow-y", "overflow-y: ${0};"),
    ("pad", "pad: ${0};"),
    ("padding", "padding: ${0};"),
    ("padding-bottom", "padding-bottom: ${0};"),
    ("padding-left", "padding-left: ${0};"),
    ("padding-right", "padding-right: ${0};"),
    ("padding-top", "padding-top: ${0};"),
    ("page", "page: ${0};"),
    ("page-break-after", "page-break-after: ${0};"),
    ("page-break-before", "page-break-before: ${0};"),
    ("page-break-inside", "page-break-inside: ${0};"),
    ("page-policy", "page-policy: ${0};"),
    ("pause", "pause: ${0};"),
    ("pause-after", "pause-after: ${0};"),
    ("pause-before", "pause-before: ${0};"),
    ("perspective", "perspective: ${0};"),
    ("perspective-origin", "perspective-origin: ${0};"),
    ("pointer-events", "pointer-events: ${0};"),
    ("position", "position: ${0};"),
    ("prefix", "prefix: ${0};"),
    ("presentation-level", "presentation-level: ${0};"),
    ("quotes", "quotes: ${0};"),
    ("range", "range: ${0};"),
    ("region-fragment", "region-fragment: ${0};"),
    ("resize", "resize: ${0};"),
    ("resolution", "resolution: ${0};"),
    ("rest", "rest: ${0};"),
    ("rest-after", "rest-after: ${0};"),
    ("rest-before", "rest-before: ${0};"),
    ("right", "right: ${0};"),
    ("rotation", "rotation: ${0};"),
    ("rotation-point", "rotation-point: ${0};"),
    ("ruby-align", "ruby-align: ${0};"),
    ("ruby-merge", "ruby-merge: ${0};"),
    ("ruby-position", "ruby-position: ${0};"),
    ("running", "running: ${0};"),
    ("shape-image-threshold", "shape-image-threshold: ${0};"),
    ("shape-margin", "shape-margin: ${0};"),
    ("shape-outside", "shape-outside: ${0};"),
    ("size", "size: ${0};"),
    ("speak", "speak: ${0};"),
    ("speak-as", "speak-as: ${0};"),
    ("src", "src: ${0};"),
    ("string-set", "string-set: ${0};"),
    ("suffix", "suffix: ${0};"),
    ("symbols", "symbols: ${0};"),
    ("system", "system: ${0};"),
    ("tab-size", "tab-size: ${0};"),
    ("table-layout", "table-layout: ${0};"),
    ("target", "target: ${0};"),
    ("target-name", "target-name: ${0};"),
    ("target-new", "target-new: ${0};"),
    ("target-position", "target-position: ${0};"),
    ("text-align", "text-align: ${0};"),
    ("text-align-last", "text-align-last: ${0};"),
    ("text-combine-upright", "text-combine-upright: ${0};"),
    ("text-decoration", "text-decoration: ${0};"),
    ("text-decoration-color", "text-decoration-color: ${0};"),
    ("text-decoration-line", "text-decoration-line: ${0};"),
    ("text-decoration-skip", "text-decoration-skip: ${0};"),
    ("text-decoration-style", "text-decoration-style: ${0};"),
    ("text-emphasis", "text-emphasis: ${0};"),
    ("text-emphasis-color", "text-emphasis-color: ${0};"),
    ("text-emphasis-position", "text-emphasis-position: ${0};"),
    ("text-emphasis-style", "text-emphasis-style: ${0};"),
    ("text-height", "text-height: ${0};"),
    ("text-indent", "text-indent: ${0};"),
    ("text-justify", "text-justify: ${0};"),
    ("text-orientation", "text-orientation: ${0};"),
    ("text-overflow", "text-overflow: ${0};"),
    ("text-shadow", "text-shadow: ${0};"),
    ("text-transform", "text-transform: ${0};"),
    ("text-underline-position", "text-underline-position: ${0};"),
    ("top", "top: ${0};"),
    ("transform", "transform: ${0};"),
    ("transform-origin", "transform-origin: ${0};"),
    ("transform-style", "transform-style: ${0};"),
    ("transition", "transition: ${0};"),
    ("transition-delay", "transition-delay: ${0};"),
    ("transition-duration", "transition-duration: ${0};"),
    ("transition-property", "transition-property: ${0};"),
    ("transition-timing-function", "transition-timing-function: ${0};"),
    ("unicode-bidi", "unicode-bidi: ${0};"),
    ("unicode-range", "unicode-range: ${0};"),
    ("user-zoom", "user-zoom: ${0};"),
    ("vertical-align", "vertical-align: ${0};"),
    ("visibility", "visibility: ${0};"),
    ("voice-balance", "voice-balance: ${0};"),
    ("voice-duration", "voice-duration: ${0};"),
    ("voice-family", "voice-family: ${0};"),
    ("voice-pitch", "voice-pitch: ${0};"),
    ("voice-range", "voice-range: ${0};"),
    ("voice-rate", "voice-rate: ${0};"),
    ("voice-stress", "voice-stress: ${0};"),
    ("voice-volume", "voice-volume: ${0};"),
    ("white-space", "white-space: ${0};"),
    ("widows", "widows: ${0};"),
    ("width", "width: ${0};"),
    ("will-change", "will-change: ${0};"),
    ("word-break", "word-break: ${0};"),
    ("word-spacing", "word-spacing: ${0};"),
    ("word-wrap", "word-wrap: ${0};"),
    ("wrap-flow", "wrap-flow: ${0};"),
    ("wrap-through", "wrap-through: ${0};"),
    ("writing-mode", "writing-mode: ${0};"),
    ("z-index", "z-index: ${0};"),
    ("zoom", "zoom: ${0}; ")
]

value_for_name = {
    "-moz-box-sizing": [v.calc],
    "-moz-column-count": [],
    "-moz-column-fill": [],
    "-moz-column-gap": [],
    "-moz-column-rule": [],
    "-moz-column-rule-color": [],
    "-moz-column-rule-style": [],
    "-moz-column-rule-width": [],
    "-moz-column-span": [],
    "-moz-column-width": [],
    "-moz-columns": [],
    "-moz-font-feature-settings": [],
    "-moz-font-language-override": [],
    "-moz-hyphens": [],
    "-moz-text-align-last": [],
    "-moz-text-decoration-color": [],
    "-moz-text-decoration-line": [],
    "-moz-text-decoration-style": [],
    "-ms-flow-from": [],
    "-ms-flow-into": [],
    "-ms-grid-column": [],
    "-ms-grid-row": [],
    "-ms-hyphens": [],
    "-ms-ime-mode": [],
    "-ms-overflow-style": [],
    "-ms-overflow-x": [],
    "-ms-overflow-y": [],
    "-ms-text-align-last": [],
    "-ms-text-justify": [],
    "-ms-transform": [],
    "-ms-transform-origin": [],
    "-ms-transform-style": [],
    "-ms-word-wrap": [],
    "-ms-wrap-flow": [],
    "-ms-wrap-through": [],
    "-ms-writing-mode": [],
    "-webkit-align-content": [],
    "-webkit-align-items": [],
    "-webkit-align-self": [],
    "-webkit-animation": [],
    "-webkit-animation-delay": [],
    "-webkit-animation-direction": [],
    "-webkit-animation-duration": [],
    "-webkit-animation-fill-mode": [],
    "-webkit-animation-iteration-count": [],
    "-webkit-animation-name": [],
    "-webkit-animation-play-state": [],
    "-webkit-animation-timing-function": [],
    "-webkit-backface-visibility": [],
    "-webkit-border-image": [],
    "-webkit-break-after": [],
    "-webkit-break-before": [],
    "-webkit-break-inside": [],
    "-webkit-column-count": [],
    "-webkit-column-fill": [],
    "-webkit-column-gap": [],
    "-webkit-column-rule": [],
    "-webkit-column-rule-color": [],
    "-webkit-column-rule-style": [],
    "-webkit-column-rule-width": [],
    "-webkit-column-span": [],
    "-webkit-column-width": [],
    "-webkit-columns": [],
    "-webkit-flex": [],
    "-webkit-flex-basis": [],
    "-webkit-flex-direction": [],
    "-webkit-flex-flow": [],
    "-webkit-flex-grow": [],
    "-webkit-flex-shrink": [],
    "-webkit-flex-wrap": [],
    "-webkit-flow-from": [],
    "-webkit-flow-into": [],
    "-webkit-font-feature-settings": [],
    "-webkit-font-kerning": [],
    "-webkit-font-variant-ligatures": [],
    "-webkit-grid-column": [],
    "-webkit-grid-row": [],
    "-webkit-hyphens": [],
    "-webkit-justify-content": [],
    "-webkit-order": [],
    "-webkit-perspective": [],
    "-webkit-perspective-origin": [],
    "-webkit-region-fragment": [],
    "-webkit-transform": [],
    "-webkit-transform-origin": [],
    "-webkit-transform-style": [],
    "-webkit-transition": [],
    "-webkit-transition-delay": [],
    "-webkit-transition-duration": [],
    "-webkit-transition-property": [],
    "-webkit-transition-timing-function": [],
    "additive-symbols": [],
    "align-content": [],
    "align-items": [],
    "align-self": [],
    "alignment": [],
    "alignment-adjust": [],
    "alignment-baseline": [],
    "all": [],
    "animation": [],
    "animation-delay": [],
    "animation-direction": [],
    "animation-duration": [],
    "animation-fill-mode": [],
    "animation-iteration-count": [],
    "animation-name": [],
    "animation-play-state": [],
    "animation-timing-function": [],
    "backface-visibility": [],
    "background": [],
    "background-attachment": [],
    "background-clip": [],
    "background-color": [],
    "background-image": [],
    "background-origin": [],
    "background-position": [],
    "background-repeat": [],
    "background-size": [],
    "baseline-shift": [],
    "bleed": [],
    "bookmark-label": [],
    "bookmark-level": [],
    "bookmark-state": [],
    "border": [],
    "border-bottom": [],
    "border-bottom-color": [],
    "border-bottom-left-radius": [],
    "border-bottom-right-radius": [],
    "border-bottom-style": [],
    "border-bottom-width": [],
    "border-clip": [],
    "border-clip-bottom": [],
    "border-clip-left": [],
    "border-clip-right": [],
    "border-clip-top": [],
    "border-collapse": [],
    "border-color": [],
    "border-image": [],
    "border-image-outset": [],
    "border-image-repeat": [],
    "border-image-slice": [],
    "border-image-source": [],
    "border-image-width": [],
    "border-left": [],
    "border-left-color": [],
    "border-left-style": [],
    "border-left-width": [],
    "border-limit": [],
    "border-radius": [],
    "border-right": [],
    "border-right-color": [],
    "border-right-style": [],
    "border-right-width": [],
    "border-spacing": [],
    "border-style": [],
    "border-top": [],
    "border-top-color": [],
    "border-top-left-radius": [],
    "border-top-right-radius": [],
    "border-top-style": [],
    "border-top-width": [],
    "border-width": [],
    "bottom": [],
    "box-decoration-break": [],
    "box-shadow": [],
    "box-sizing": [],
    "box-snap": [],
    "break-after": [],
    "break-before": [],
    "break-inside": [],
    "caption-side": [],
    "chains": [],
    "child-align": [],
    "clear": [],
    "clear-after": [],
    "clear-side": [],
    "clip-path": [],
    "clip-rule": [],
    "color": [],
    "color-adjust": [],
    "color-correction": [],
    "color-interpolation": [],
    "color-interpolation-filters": [],
    "column-count": [],
    "column-fill": [],
    "column-gap": [],
    "column-rule": [],
    "column-rule-color": [],
    "column-rule-style": [],
    "column-rule-width": [],
    "column-span": [],
    "column-width": [],
    "columns": [],
    "content": [],
    "corner-shape": [],
    "corners": [],
    "counter-increment": [],
    "counter-reset": [],
    "counter-set": [],
    "cue": [],
    "cue-after": [],
    "cue-before": [],
    "cursor": [],
    "direction": [],
    "display": [],
    "display-box": [],
    "display-extras": [],
    "display-inside": [],
    "display-outside": [],
    "dominant-baseline": [],
    "empty-cells": [],
    "fallback": [],
    "filter": [],
    "flex": [],
    "flex-basis": [],
    "flex-direction": [],
    "flex-flow": [],
    "flex-grow": [],
    "flex-shrink": [],
    "flex-wrap": [],
    "float": [],
    "float-defer-column": [],
    "float-defer-page": [],
    "float-displace": [],
    "float-offset": [],
    "float-wrap": [],
    "flood-color": [],
    "flood-opacity": [],
    "flow": [],
    "flow-from": [],
    "flow-into": [],
    "font": [],
    "font-family": [],
    "font-feature-settings": [],
    "font-kerning": [],
    "font-language-override": [],
    "font-size": [],
    "font-size-adjust": [],
    "font-stretch": [],
    "font-style": [],
    "font-synthesis": [],
    "font-variant": [],
    "font-variant-alternates": [],
    "font-variant-caps": [],
    "font-variant-east-asian": [],
    "font-variant-ligatures": [],
    "font-variant-numeric": [],
    "font-variant-position": [],
    "font-weight": [],
    "footnote-display": [],
    "footnote-policy": [],
    "grid": [],
    "grid-area": [],
    "grid-auto-columns": [],
    "grid-auto-flow": [],
    "grid-auto-rows": [],
    "grid-column": [],
    "grid-column-end": [],
    "grid-column-start": [],
    "grid-row": [],
    "grid-row-end": [],
    "grid-row-start": [],
    "grid-template": [],
    "grid-template-areas": [],
    "grid-template-columns": [],
    "grid-template-rows": [],
    "hanging-punctuation": [],
    "height": [],
    "hyphens": [],
    "icon": [],
    "image-orientation": [],
    "image-rendering": [],
    "image-resolution": [],
    "ime-mode": [],
    "indent-edge-reset": [],
    "initial-letters": [],
    "inline-box-align": [],
    "justify-content": [],
    "justify-items": [],
    "justify-self": [],
    "left": [],
    "letter-spacing": [],
    "lighting-color": [],
    "line-box-contain": [],
    "line-break": [],
    "line-grid": [],
    "line-height": [],
    "line-slack": [],
    "line-snap": [],
    "line-stacking": [],
    "line-stacking-ruby": [],
    "line-stacking-shift": [],
    "line-stacking-strategy": [],
    "list-style": [],
    "list-style-image": [],
    "list-style-position": [],
    "list-style-type": [],
    "margin": [],
    "margin-bottom": [],
    "margin-left": [],
    "margin-right": [],
    "margin-top": [],
    "marker-side": [],
    "marks": [],
    "marquee-direction": [],
    "marquee-play-count": [],
    "marquee-speed": [],
    "marquee-style": [],
    "mask": [],
    "mask-border": [],
    "mask-border-outset": [],
    "mask-border-repeat": [],
    "mask-border-slice": [],
    "mask-border-source": [],
    "mask-border-width": [],
    "mask-clip": [],
    "mask-composite": [],
    "mask-image": [],
    "mask-mode": [],
    "mask-origin": [],
    "mask-position": [],
    "mask-repeat": [],
    "mask-size": [],
    "mask-type": [],
    "max-height": [],
    "max-lines": [],
    "max-width": [],
    "max-zoom": [],
    "min-height": [],
    "min-width": [],
    "min-zoom": [],
    "move-to": [],
    "nav-down": [],
    "nav-index": [],
    "nav-left": [],
    "nav-right": [],
    "nav-up": [],
    "negative": [],
    "object-fit": [],
    "object-position": [],
    "offset-after": [],
    "offset-before": [],
    "offset-end": [],
    "offset-start": [],
    "opacity": [],
    "order": [],
    "orientation": [],
    "orphans": [],
    "outline": [],
    "outline-color": [],
    "outline-offset": [],
    "outline-style": [],
    "outline-width": [],
    "overflow": [],
    "overflow-style": [],
    "overflow-wrap": [],
    "overflow-x": [],
    "overflow-y": [],
    "pad": [],
    "padding": [],
    "padding-bottom": [],
    "padding-left": [],
    "padding-right": [],
    "padding-top": [],
    "page": [],
    "page-break-after": [],
    "page-break-before": [],
    "page-break-inside": [],
    "page-policy": [],
    "pause": [],
    "pause-after": [],
    "pause-before": [],
    "perspective": [],
    "perspective-origin": [],
    "pointer-events": [],
    "position": [],
    "prefix": [],
    "presentation-level": [],
    "quotes": [],
    "range": [],
    "region-fragment": [],
    "resize": [],
    "resolution": [],
    "rest": [],
    "rest-after": [],
    "rest-before": [],
    "right": [],
    "rotation": [],
    "rotation-point": [],
    "ruby-align": [],
    "ruby-merge": [],
    "ruby-position": [],
    "running": [],
    "shape-image-threshold": [],
    "shape-margin": [],
    "shape-outside": [],
    "size": [],
    "speak": [],
    "speak-as": [],
    "src": [],
    "string-set": [],
    "suffix": [],
    "symbols": [],
    "system": [],
    "tab-size": [],
    "table-layout": [],
    "target": [],
    "target-name": [],
    "target-new": [],
    "target-position": [],
    "text-align": [],
    "text-align-last": [],
    "text-combine-upright": [],
    "text-decoration": [],
    "text-decoration-color": [],
    "text-decoration-line": [],
    "text-decoration-skip": [],
    "text-decoration-style": [],
    "text-emphasis": [],
    "text-emphasis-color": [],
    "text-emphasis-position": [],
    "text-emphasis-style": [],
    "text-height": [],
    "text-indent": [],
    "text-justify": [],
    "text-orientation": [],
    "text-overflow": [],
    "text-shadow": [],
    "text-transform": [],
    "text-underline-position": [],
    "top": [],
    "transform": [],
    "transform-origin": [],
    "transform-style": [],
    "transition": [],
    "transition-delay": [],
    "transition-duration": [],
    "transition-property": [],
    "transition-timing-function": [],
    "unicode-bidi": [],
    "unicode-range": [],
    "user-zoom": [],
    "vertical-align": [],
    "visibility": [],
    "voice-balance": [],
    "voice-duration": [],
    "voice-family": [],
    "voice-pitch": [],
    "voice-range": [],
    "voice-rate": [],
    "voice-stress": [],
    "voice-volume": [],
    "white-space": [],
    "widows": [],
    "width": [],
    "will-change": [],
    "word-break": [],
    "word-spacing": [],
    "word-wrap": [],
    "wrap-flow": [],
    "wrap-through": [],
    "writing-mode": [],
    "z-index": [],
    "zoom": []
}
