# @-rules that can appear inside other @-rules.
nestable_at_rules = [
    ("@counter-style", "@counter-style ${1:name} {\n\t${2}\n}"),
    ("@font-face", "@font-face {\n\t${1}\n}"),
    ("@font-feature-values", "@font-feature-values ${1:font-family} {\n\t${2}\n}"),
    ("@keyframes", "@keyframes ${1:name} {\n\t${2}\n}"),
    ("@media", "@media ${1:media-query-list} {\n\t${2}\n}"),
    ("@page", "@page ${1} {\n\t${2}\n}"),
    ("@viewport", "@viewport ${1} {\n\t${2}\n}"),
    ("@supports", "@supports ${1} {\n\t${2}\n}"),
]

at_rules = [
    ("@charset", '@charset "UTF-8";'),
    ("@color-profile", "@color-profile {\n\t${2}\n}"),
    ("@custom-media", "@custom-media --${1:name} ${2:media-query-list};"),
    ("@import", "@import ${1:path} ${2:media-query-list};"),
    ("@namespace", "@namespace ${1};"),
] + nestable_at_rules

at_page_selectors = [
    (":blank",),
    (":first",),
    (":left",),
    (":recto",),
    (":right",),
    (":verso",),
]

page_margin_boxes = [
    ("@bottom-center", "@bottom-center {\n\t${1}\n}"),
    ("@bottom-left", "@bottom-left {\n\t${1}\n}"),
    ("@bottom-left-corner", "@bottom-left-corner {\n\t${1}\n}"),
    ("@bottom-right", "@bottom-right {\n\t${1}\n}"),
    ("@bottom-right-corner", "@bottom-right-corner {\n\t${1}\n}"),
    ("@left-bottom", "@left-bottom {\n\t${1}\n}"),
    ("@left-middle", "@left-middle {\n\t${1}\n}"),
    ("@left-top", "@left-top {\n\t${1}\n}"),
    ("@right-bottom", "@right-bottom {\n\t${1}\n}"),
    ("@right-middle", "@right-middle {\n\t${1}\n}"),
    ("@right-top", "@right-top {\n\t${1}\n}"),
    ("@top-center", "@top-center {\n\t${1}\n}"),
    ("@top-left", "@top-left {\n\t${1}\n}"),
    ("@top-left-corner", "@top-left-corner {\n\t${1}\n}"),
    ("@top-right", "@top-right {\n\t${1}\n}"),
    ("@top-right-corner", "@top-right-corner {\n\t${1}\n}"),
]

font_feature_types = [
    ("@annotation", "@annotation {\n\t${1}\n}"),
    ("@character-variant", "@character-variant {\n\t${1}\n}"),
    ("@ornaments", "@ornaments {\n\t${1}\n}"),
    ("@styleset", "@styleset {\n\t${1}\n}"),
    ("@stylistic", "@stylistic {\n\t${1}\n}"),
    ("@swash", "@swash {\n\t${1}\n}"),
]

html_tags = [
    ("a",),
    ("abbr",),
    ("address",),
    ("area",),
    ("article",),
    ("aside",),
    ("audio",),
    ("b",),
    ("base",),
    ("bdi",),
    ("bdo",),
    ("blockquote",),
    ("body",),
    ("br",),
    ("button",),
    ("canvas",),
    ("caption",),
    ("cite",),
    ("code",),
    ("col",),
    ("colgroup",),
    ("data",),
    ("datalist",),
    ("dd",),
    ("del",),
    ("details",),
    ("dfn",),
    ("dialog",),
    ("div",),
    ("dl",),
    ("dt",),
    ("em",),
    ("embed",),
    ("fieldset",),
    ("figcaption",),
    ("figure",),
    ("footer",),
    ("form",),
    ("h1",),
    ("h2",),
    ("h3",),
    ("h4",),
    ("h5",),
    ("h6",),
    ("head",),
    ("header",),
    ("hr",),
    ("html",),
    ("i",),
    ("iframe",),
    ("img",),
    ("input",),
    ("ins",),
    ("kbd",),
    ("label",),
    ("legend",),
    ("li",),
    ("link",),
    ("main",),
    ("map",),
    ("mark",),
    ("menu",),
    ("menuitem",),
    ("meta",),
    ("meter",),
    ("nav",),
    ("noscript",),
    ("object",),
    ("ol",),
    ("optgroup",),
    ("option",),
    ("output",),
    ("p",),
    ("param",),
    ("picture",),
    ("pre",),
    ("progress",),
    ("q",),
    ("rb",),
    ("rp",),
    ("rt",),
    ("rtc",),
    ("ruby",),
    ("s",),
    ("samp",),
    ("script",),
    ("section",),
    ("select",),
    ("small",),
    ("source",),
    ("span",),
    ("strong",),
    ("style",),
    ("sub",),
    ("summary",),
    ("sup",),
    ("table",),
    ("tbody",),
    ("td",),
    ("template",),
    ("textarea",),
    ("tfoot",),
    ("th",),
    ("thead",),
    ("time",),
    ("title",),
    ("tr",),
    ("track",),
    ("u",),
    ("ul",),
    ("var",),
    ("video",),
    ("wbr",),
]

keyframes_selector = [
    ("from", "from {\n\t${1}\n}"),
    ("to", "to {\n\t${1}\n}"),
]

pseudo_classes = [
    ("active",),
    ("any-link",),
    ("blank",),
    ("checked",),
    ("current",),
    ("default",),
    ("dir()", "dir($1)"),
    ("disabled",),
    ("drop",),
    ("drop()", "drop($1)"),
    ("empty",),
    ("enabled",),
    ("first-child",),
    ("first-of-type",),
    ("focus",),
    ("focus-within",),
    ("future",),
    ("has()", "has($1)"),
    ("host",),
    ("host()", "host($1)"),
    ("host-context()", "host-context($1)"),
    ("hover",),
    ("in-range",),
    ("indeterminate",),
    ("input-placeholder",),
    ("invalid",),
    ("lang()", "lang($1)"),
    ("last-child",),
    ("last-of-type",),
    ("link",),
    ("matches()", "matches($1)"),
    ("not()", "not($1)"),
    ("nth-child()", "nth-child($1)"),
    ("nth-column()", "nth-column($1)"),
    ("nth-last-child()", "nth-last-child($1)"),
    ("nth-last-column()", "nth-last-column($1)"),
    ("nth-last-of-type()", "nth-last-of-type($1)"),
    ("nth-of-type()", "nth-of-type($1)"),
    ("only-child",),
    ("only-of-type",),
    ("optional",),
    ("out-of-range",),
    ("past",),
    ("paused",),
    ("placeholder-shown",),
    ("playing",),
    ("read-only",),
    ("read-write",),
    ("required",),
    ("root",),
    ("scope",),
    ("scope-context()", "scope-context($1)"),
    ("target",),
    ("user-invalid",),
    ("valid",),
    ("visited",),

    # TODO: vendor prefixed pseudo-classes here
]

pseudo_elements = [
    ("after",),
    ("attr()", "attr($1)"),
    ("before",),
    ("content",),
    ("first-letter",),
    ("first-line",),
    ("grammar-error",),
    ("inactive-selection",),
    ("input-placeholder",),
    ("marker",),
    ("placeholder",),
    ("region",),
    ("selection",),
    ("shadow",),
    ("slotted()", "slotted($1)"),
    ("spelling-error",),

    # TODO: vendor prefixed pseudo-elements here
]

at_rules.sort()
